//
//  Lesson.m
//  Vocavularist
//
//  Created by Devine Lu Linvega on 2015-05-10.
//  Copyright (c) 2015 XXIIVV. All rights reserved.
//

#import "Lesson.h"
#import "xxiivvViewController.h"

NSArray * currentLesson;

@implementation Lesson

-(Lesson*)initWithLessonMode :(lessonMode)lessonMode
{
	if( lessonMode == kanjiKana ){ currentLesson = [self japaneseLesson]; }
	else{ currentLesson = [self russianLesson]; }
	
	return self;
}

-(NSString*)question:(int)lessonId
{
	return currentLesson[lessonId][0];
}

-(NSUInteger)length
{
	return [currentLesson count];
}

-(NSArray*)mistakesFromLessonId:(int)lessonId :(lessonMode)lessonMode
{
	// Make potential answers
	NSRange targetRange = NSMakeRange(0, lessonId+4);
	if(lessonId > 200){ targetRange = NSMakeRange(0, lessonId+1); }
	NSMutableArray * newArray = [NSMutableArray arrayWithArray:[currentLesson subarrayWithRange:targetRange]];
	
	[newArray removeObjectAtIndex:lessonId];
	
	newArray = [self shuffleArray:newArray];
	
	int targetField = (int)[newArray[0] count] -1;
	
	if( lessonMode == kanji ){ targetField = 2; }
	
	return @[newArray[0][targetField],newArray[1][targetField],newArray[2][targetField]];
}

-(NSString*)answerFromLessonId:(int)lessonId :(lessonMode)lessonMode
{
	return @"-";
	int targetField = (int)[currentLesson[lessonId] count] -1;
	
	if( lessonMode == kanjiKana ){ targetField = 2; }
	return currentLesson[lessonId][targetField];
}

- (NSMutableArray*)shuffleArray:(NSMutableArray*)targetArray
{
	NSUInteger count = [targetArray count];
	for (NSUInteger i = 0; i < count; ++i) {
		NSInteger remainingCount = count - i;
		NSInteger exchangeIndex = i + arc4random_uniform((u_int32_t )remainingCount);
		[targetArray exchangeObjectAtIndex:i withObjectAtIndex:exchangeIndex];
	}
	
	return targetArray;
}


-(NSArray*)russianLesson
{
	NSLog(@"! LESSON | Loading Russian");
	
	return @[
		@[@"друг", @"friend"],
		@[@"большой", @"big, large, important"],
		@[@"и", @"and, though"],
		@[@"в", @"in, at"],
		@[@"не", @"not"],
		@[@"он", @"he"],
		@[@"на", @"on, it, at, to"],
		@[@"я", @"I"],
		@[@"что", @"what, that, why"],
		@[@"тот", @"that"],
		@[@"с", @"with, and, from, of"],
		@[@"а", @"while, and, but"],
		@[@"весь", @"all, everything"],
		@[@"это", @"that, this, it"],
		@[@"как", @"how, what, as, like"],
		@[@"она", @"she"],
		@[@"по", @"on, along, by"],
		@[@"но", @"but"],
		@[@"они", @"they"],
		@[@"к", @"to, for, by"],
		@[@"у", @"by, with, of"],
		@[@"ты", @"you, thou"],
		@[@"из", @"from, of, in"],
		@[@"мы", @"we"],
		@[@"за", @"behind, over, at, after"],
		@[@"вы", @"you"],
		@[@"так", @"so, thus, then"],
		@[@"же", @"and, asfor, but, same"],
		@[@"от", @"from, of, for"],
		@[@"сказать", @"tosay, tospeak"],
		@[@"этот", @"this"],
		@[@"который", @"which, who, that"],
		@[@"мочь", @"beable"],
		@[@"человек", @"man, person"],
		@[@"о", @"of, about, against"],
		@[@"один", @"one, some, alone"],
		@[@"ещё", @"still, yet"],
		@[@"бы", @"would"],
		@[@"такой", @"such, so, some"],
		@[@"только", @"only, merely, but"],
		@[@"себя", @"myself, himself, herself", @"pron"],
		@[@"своё", @"my, our"],
		@[@"какой", @"what, which, how"],
		@[@"когда", @"when, while, as"],
		@[@"уже", @"already, bynow"],
		@[@"для", @"for, to"],
		@[@"вот", @"here, there, this is, that's"],
		@[@"кто", @"who, that, some"],
		@[@"да", @"yes, but"],
		@[@"говорить", @"to say, to tell, to speak"],
		@[@"год", @"year"],
		@[@"знать", @"to know, beaware"],
		@[@"мой", @"my, mine"],
		@[@"до", @"to, up to, about, before"],
		@[@"или", @"or"],
		@[@"если", @"if"],
		@[@"время", @"time, season"],
		@[@"рука", @"hand, arm"],
		@[@"нет", @"no, not, but"],
		@[@"самый", @"most, thevery, thesame"],
		@[@"ни", @"nota, not, neither"],
		@[@"стать", @"become, begin, come"],
		@[@"даже", @"even"],
		@[@"другой", @"other, another, different"],
		@[@"наш", @"our, ours"],
		@[@"свой", @"my, our, your"],
		@[@"ну", @"now, right, well, comeon"],
		@[@"под", @"under, for, towards, to"],
		@[@"где", @"where"],
		@[@"дело", @"business, affair, matter"],
		@[@"есть", @"toeat, tobe"],
		@[@"сам", @"myself, yourself"],
		@[@"раз", @"time, once, since"],
		@[@"чтобы", @"that, inorderthat"],
		@[@"два", @"two"],
		@[@"там", @"there, then"],
		@[@"чем", @"instead of"],
		@[@"глаз", @"eye, sight"],
		@[@"жизнь", @"life"],
		@[@"первый", @"first, front, former"],
		@[@"день", @"day"],
		@[@"тут", @"here, now, then"],
		@[@"во", @"in, at - super, exactly"],
		@[@"ничто", @"nothing"],
		@[@"потом", @"afterwards, then"],
		@[@"очень", @"very"],
		@[@"со", @"with"],
		@[@"хотеть", @"towant, like"],
		@[@"ли", @"whether, if"],
		@[@"при", @"attached to, in the presence of, by"],
		@[@"голова", @"head, mind, brains"],
		@[@"надо", @"over, above, ought to"],
		@[@"без", @"without"],
		@[@"видеть", @"to see"],
		@[@"идти", @"to go, come"],
		@[@"теперь", @"now, nowadays"],
		@[@"тоже", @"also, aswell, too"],
		@[@"стоять", @"tostand, be, standup"],
		@[@"дом", @"house, home"],
		@[@"сейчас", @"now, presently, soon"],
		@[@"можно", @"onecan"],
		@[@"после", @"after, afterwards"],
		@[@"слово", @"word"],
		@[@"здесь", @"here"],
		@[@"думать", @"to think, to believe"],
		@[@"место", @"place, seat"],
		@[@"спросить", @"to ask"],
		@[@"через", @"through, across"],
		@[@"лицо", @"face, person"],
		@[@"что", @"what, which, that"],
		@[@"тогда", @"then"],
		@[@"ведь", @"you see, you know"],
		@[@"хороший", @"good, nice"],
		@[@"каждый", @"each, every"],
		@[@"новый", @"new, modern"],
		@[@"жить", @"to live"],
		@[@"должный", @"due, proper"],
		@[@"смотреть", @"to look, watch"],
		@[@"почему", @"why"],
		@[@"потому", @"that's why"],
		@[@"сторона", @"side, party"],
		@[@"просто", @"simply"],
		@[@"нога", @"foot, leg"],
		@[@"сидеть", @"to sit"],
		@[@"понять", @"to understand, realize"],
		@[@"иметь", @"to have, own"],
		@[@"конечный", @"final, last"],
		@[@"делать", @"todo, make"],
		@[@"вдруг", @"suddenly"],
		@[@"над", @"above, over"],
		@[@"взять", @"to take"],
		@[@"никто", @"nobody"],
		@[@"сделать", @"todo, make, finish"],
		@[@"дверь", @"door"],
		@[@"перед", @"before, in front of"],
		@[@"нужный", @"necessary"],
		@[@"понимать", @"to understand"],
		@[@"казаться", @"to seem, appear"],
		@[@"работа", @"work, job"],
		@[@"три", @"three"],
		@[@"ваш", @"yours"],
		@[@"уж", @"really, already"],
		@[@"земля", @"earth, land, soil"],
		@[@"конец", @"end, distance"],
		@[@"несколько", @"several,some"],
		@[@"час", @"hour, time"],
		@[@"голос", @"voice"],
		@[@"город", @"town, city"],
		@[@"последний", @"last, the latest, new"],
		@[@"пока", @"for the present"],
		@[@"хорошо", @"well"],
		@[@"давать", @"to give, let, allow"],
		@[@"вода", @"water"],
		@[@"более", @"more"],
		@[@"хотя", @"although"],
		@[@"всегда", @"always"],
		@[@"второй", @"second"],
		@[@"куда", @"where, what for, much"],
		@[@"пойти", @"to go"],
		@[@"стол", @"table, desk, board"],
		@[@"ребёнок", @"child, kid, infant"],
		@[@"увидеть", @"to see"],
		@[@"сила", @"strength, force"],
		@[@"отец", @"father"],
		@[@"женщина", @"woman"],
		@[@"машина", @"car, machine, engine"],
		@[@"случай", @"case, occasion, incident"],
		@[@"ночь", @"night"],
		@[@"сразу", @"atonce, rightaway, just"],
		@[@"мир", @"world"],
		@[@"совсем", @"quite, entirely, totally"],
		@[@"остаться", @"to remain,stay"],
		@[@"об", @"about, of"],
		@[@"вид", @"appearance, look, view"],
		@[@"выйти", @"togoout, comeout, appear"],
		@[@"дать", @"to give"],
		@[@"работать", @"to work"],
		@[@"любить", @"to love"],
		@[@"старый", @"old"],
		@[@"почти", @"almost"],
		@[@"ряд", @"row, line"],
		@[@"оказаться", @"find oneself, turnout"],
		@[@"начало", @"beginning, origin, source"],
		@[@"твой", @"your, yours"],
		@[@"вопрос", @"question, matter, problem"],
		@[@"много", @"many, much"],
		@[@"война", @"war"],
		@[@"снова", @"again"],
		@[@"ответить", @"to answer, reply"],
		@[@"между", @"between, among"],
		@[@"подумать", @"to think"],
		@[@"опять", @"again"],
		@[@"белый", @"white"],
		@[@"деньги", @"money"],
		@[@"значить", @"to mean, signify"],
		@[@"про", @"about, for"],
		@[@"лишь", @"only, as soon as"],
		@[@"минута", @"minute, moment"],
		@[@"жена", @"wife"],
		@[@"посмотреть", @"to take a look, watch, inspect"],
		@[@"правда", @"truth"],
		@[@"главный", @"main, chief"],
		@[@"страна", @"country"],
		@[@"свет", @"light, world"],
		@[@"ждать", @"to wait"],
		@[@"мать", @"mother"],
		@[@"будто", @"as if, as though"],
		@[@"никогда", @"never"],
		@[@"товарищ", @"comrade, friend"],
		@[@"дорога", @"road, way, journey"],
		@[@"однако", @"however, though"],
		@[@"лежать", @"to lie, be situated"],
		@[@"именно", @"namely, just"],
		@[@"окно", @"window, windowsill"],
		@[@"никакой", @"no, none"],
		@[@"найти", @"to find, discover, consider"],
		@[@"писать", @"to write"],
		@[@"комната", @"a room"],
		@[@"Москва", @"Moscow"],
		@[@"часть", @"part, share, department"],
		@[@"вообще", @"in general, altogether, on the whole"],
		@[@"книга", @"a book"],
		@[@"маленький", @"small,little"],
		@[@"улица", @"street"],
		@[@"решить", @"to decide, solve"],
		@[@"далекий", @"distant, remote"],
		@[@"душа", @"soul, spirit"],
		@[@"чуть", @"hardly, slightly"],
		@[@"вернуться", @"to return"],
		@[@"утро", @"morning"],
		@[@"некоторый", @"some"],
		@[@"считать", @"to count, consider"],
		@[@"сколько", @"how much, how many"],
		@[@"помнить", @"to remember"],
		@[@"вечер", @"evening"],
		@[@"пол", @"floor, sex"],
		@[@"таки", @"after all"],
		@[@"получить", @"to receive, get, obtain"],
		@[@"народ", @"people, nation"],
		@[@"плечо", @"shoulder, upperarm"],
		@[@"хоть", @"even, if you want, though"],
		@[@"сегодня", @"today"],
		@[@"бог", @"god"],
		@[@"вместе", @"together"],
		@[@"взгляд", @"look, glance, view"],
		@[@"ходить", @"to go, walk"],
		@[@"зачем", @"what for, why"],
		@[@"советский", @"Soviet"],
		@[@"русский", @"Russian"],
		@[@"бывать", @"be, visit, happen"],
		@[@"полный", @"full, complete"],
		@[@"прийти", @"tocome,arrive"],
		@[@"палец", @"finger,toe"],
		@[@"Россия", @"Russia"],
		@[@"любой", @"any,every"],
		@[@"история", @"history,story,event"],
		@[@"наконец", @"atlast,finally"],
		@[@"мысль", @"thought,idea"],
		@[@"узнать", @"toknow,learn,recognize"],
		@[@"назад", @"back,backwards"],
		@[@"общий", @"general,common"],
		@[@"заметить", @"tonotice,observe"],
		@[@"словно", @"asif,like"],
		@[@"прошлый", @"past"],
		@[@"уйти", @"to leave,go away"],
		@[@"известный", @"well-known,famous"],
		@[@"давно", @"longago"],
		@[@"слышать", @"tohear"],
		@[@"слушать", @"tolisten,hear"],
		@[@"бояться", @"tobeafraid,fear"],
		@[@"сын", @"son"],
		@[@"нельзя", @"itisimpossible,can't"],
		@[@"прямо", @"straight,frankly"],
		@[@"долго", @"foralongtime"],
		@[@"быстро", @"fast,quickly"],
		@[@"лес", @"forest"],
		@[@"похожий", @"similar,alike"],
		@[@"пора", @"time;pore"],
		@[@"пять", @"five"],
		@[@"глядеть", @"tolook,gaze"],
		@[@"оно", @"it"],
		@[@"сесть", @"tosit"],
		@[@"имя", @"name"],
		@[@"ж", @"and,asfor,but"],
		@[@"разговор", @"talk,conversation"],
		@[@"тело", @"body"],
		@[@"молодой", @"young;bridegroom(asa)"],
		@[@"стена", @"wall"],
		@[@"красный", @"red"],
		@[@"читать", @"toread"],
		@[@"право", @"right"],
		@[@"старик", @"oldman"],
		@[@"ранний", @"early"],
		@[@"хотеться", @"want,like"],
		@[@"мама", @"mummy,mum"],
		@[@"оставаться", @"toremain,stay"],
		@[@"высокий", @"tall,high"],
		@[@"путь", @"way,track,path"],
		@[@"поэтому", @"therefore"],
		@[@"совершенно", @"absolutely,quite"],
		@[@"кроме", @"except,besides"],
		@[@"тысяча", @"athousand"],
		@[@"месяц", @"month"],
		@[@"брать", @"totake;hire"],
		@[@"написать", @"towrite"],
		@[@"целый", @"intact,whole,entire"],
		@[@"огромный", @"huge,enormous"],
		@[@"начинать", @"tobegin"],
		@[@"спина", @"back"],
		@[@"настоящий", @"present;real,true"],
		@[@"пусть", @"let's,though"],
		@[@"язык", @"tongue,language"],
		@[@"точно", @"exactly"],
		@[@"среди", @"among"],
		@[@"чувствовать", @"tofeel"],
		@[@"сердце", @"heart"],
		@[@"вести", @"tolead"],
		@[@"иногда", @"sometimes"],
		@[@"мальчик", @"boy"],
		@[@"успеть", @"tobeintime,besuccessful"],
		@[@"небо", @"sky"],
		@[@"живой", @"living,live,lively"],
		@[@"смерть", @"death"],
		@[@"продолжать", @"tocontinue"],
		@[@"девушка", @"girl,miss"],
		@[@"образ", @"shape,form,image"],
		@[@"ко", @"to,towards,by"],
		@[@"забыть", @"toforget"],
		@[@"вокруг", @"around"],
		@[@"письмо", @"letter"],
		@[@"власть", @"power"],
		@[@"чёрный", @"black"],
		@[@"пройти", @"topass,goby,beover"],
		@[@"появиться", @"toappear,showup"],
		@[@"воздух", @"air"],
		@[@"разный", @"different"],
		@[@"выходить", @"togoout;nurse"],
		@[@"просить", @"toask"],
		@[@"брат", @"brother"],
		@[@"собственный", @"one'sown"],
		@[@"отношение", @"relationship,attitude"],
		@[@"затем", @"then,afterthat"],
		@[@"пытаться", @"totry"],
		@[@"показать", @"toshow,display"],
		@[@"вспомнить", @"toremember,recall"],
		@[@"система", @"system"],
		@[@"четыре", @"four"],
		@[@"квартира", @"flat,apartment"],
		@[@"держать", @"tohold,keep"],
		@[@"также", @"also,aswell,too"],
		@[@"любовь", @"love"],
		@[@"солдат", @"soldier"],
		@[@"откуда", @"where…from"],
		@[@"чтоб", @"that,inorderthat,"],
		@[@"называть", @"tocall,name,"],
		@[@"третий", @"third"],
		@[@"хозяин", @"master,boss,host"],
		@[@"вроде", @"like,notunlike"],
		@[@"уходить", @"toleave,goaway"],
		@[@"подойти", @"toapproach,comeup"],
		@[@"поднять", @"tolift,raise"],
		@[@"особенно", @"especially,particularly"],
		@[@"спрашивать", @"toask,inquire"],
		@[@"начальник", @"chief,head,superior"],
		@[@"оба", @"both"],
		@[@"бросить", @"tothrow"],
		@[@"школа", @"school"],
		@[@"парень", @"boy,fellow,guy"],
		@[@"кровь", @"blood"],
		@[@"двадцать", @"twenty"],
		@[@"солнце", @"sun"],
		@[@"неделя", @"week"],
		@[@"послать", @"tosend,dispatch"],
		@[@"находиться", @"tobefound,turnup"],
		@[@"ребята", @"guys,children"],
		@[@"поставить", @"toput,place,set"],
		@[@"встать", @"togetup,rise,standup"],
		@[@"например", @"forexample,forinstance"],
		@[@"шаг", @"step"],
		@[@"мужчина", @"man,male"],
		@[@"равно", @"alike,inlikemanner"],
		@[@"нос", @"nose"],
		@[@"мало", @"little,few,"],
		@[@"внимание", @"attention"],
		@[@"капитан", @"captain,master"],
		@[@"ухо", @"ear"],
		@[@"туда", @"there"],
		@[@"сюда", @"here"],
		@[@"играть", @"toplay"],
		@[@"следовать", @"tofollow,comenext"],
		@[@"рассказать", @"totell,narrate"],
		@[@"великий", @"great"],
		@[@"действительно", @"indeed,really"],
		@[@"слишком", @"too,toomuch"],
		@[@"тяжёлый", @"heavy"],
		@[@"спать", @"tosleep"],
		@[@"оставить", @"to leave, abandon"],
		@[@"войти", @"to enter, come in"],
		@[@"длинный", @"long"],
		@[@"чувство", @"feeling"],
		@[@"молчать", @"to keep silence"],
		@[@"рассказывать", @"to tell, narrate,"],
		@[@"отвечать", @"to answer, reply,"],
		@[@"становиться", @"to stand, to become"],
		@[@"остановиться", @"to stop"],
		@[@"берег", @"bank, shore, coast"],
		@[@"семья", @"family"],
		@[@"искать", @"to search"],
		@[@"генерал", @"general"],
		@[@"момент", @"moment, instant"],
		@[@"десять", @"ten"],
		@[@"начать", @"to begin"],
		@[@"следующий", @"next, following"],
		@[@"личный", @"personal"],
		@[@"уйти", @"to leave,go away"],
		@[@"труд", @"labour,work"],
		@[@"верить", @"to believe"],
		@[@"группа", @"group"],
		@[@"немного", @"alittle"],
		@[@"впрочем", @"however,though"],
		@[@"видно", @"evidently,obviously"],
		@[@"являться", @"to appear"],
		@[@"муж", @"husband"],
		@[@"разве", @"really?, perhaps"],
		@[@"движение", @"movement"],
		@[@"порядок", @"order"],
		@[@"ответ", @"answer, reply"],
		@[@"тихо", @"quietly, softly, slowly"],
		@[@"знакомый", @"familiar, acquainted"],
		@[@"газета", @"newspaper"],
		@[@"помощь", @"help"],
		@[@"сильный", @"strong, powerful"],
		@[@"скорый", @"quick, fast"],
		@[@"собака", @"dog"],
		@[@"дерево", @"tree"],
		@[@"снег", @"snow"],
		@[@"сон", @"dream"],
		@[@"смысл", @"sense, meaning, purpose"],
		@[@"смочь", @"to be able"],
		@[@"против", @"against, opposite, contrary to"],
		@[@"бежать", @"to run, hurry"],
		@[@"двор", @"yard, court"],
		@[@"форма", @"form, shape, uniform"],
		@[@"простой", @"simple, easy, plain"],
		@[@"приехать", @"to arrive, come"],
		@[@"иной", @"different, other"],
		@[@"кричать", @"to cry, shout"],
		@[@"возможность", @"possibility, opportunity, chance"],
		@[@"общество", @"society"],
		@[@"зеленый", @"green"],
		@[@"грудь", @"breast, chest"],
		@[@"угол", @"corner, angle"],
		@[@"открыть", @"to open"],
		@[@"происходить", @"to happen, occur, takeplace"],
		@[@"ладно", @"inharmony ,well, allright"],
		@[@"черный", @"black"],
		@[@"век", @"century, age"],
		@[@"карман", @"pocket"],
		@[@"ехать", @"togo, ride, drive, travel"],
		@[@"немец", @"German"],
		@[@"наверное", @"probably, most likely"],
		@[@"губа", @"lip"],
		@[@"дядя", @"uncle"],
		@[@"приходить", @"to come, arrive"],
		@[@"часто", @"often"],
		@[@"домой", @"home"],
		@[@"огонь", @"fire"],
		@[@"писатель", @"writer"],
		@[@"армия", @"army"],
		@[@"состояние", @"state, condition, fortune"],
		@[@"зуб", @"tooth"],
		@[@"очередь", @"line, queue, turn"],
		@[@"кой", @"which"],
		@[@"подняться", @"torise, climb"],
		@[@"камень", @"stone"],
		@[@"гость", @"guest"],
		@[@"показаться", @"to appear, come insight"],
		@[@"ветер", @"wind"],
		@[@"собираться", @"to gather together, assemble"],
		@[@"попасть", @"to hit, to find one self"],
		@[@"принять", @"to take, admit, accept"],
		@[@"сначала", @"at first, from the beginning"],
		@[@"либо", @"or"],
		@[@"поехать", @"to depart, setoff"],
		@[@"услышать", @"to hear"],
		@[@"уметь", @"to beable, know, can"],
		@[@"случиться", @"to happen"],
		@[@"странный", @"strange"],
		@[@"единственный", @"only, sole"],
		@[@"рота", @"company(military)"],
		@[@"закон", @"law, act, statue"],
		@[@"короткий", @"short"],
		@[@"море", @"sea"],
		@[@"добрый", @"kind"],
		@[@"темный", @"dark"],
		@[@"гора", @"mountain, hill"],
		@[@"врач", @"physician, doctor"],
		@[@"край", @"border, edge, land, country"],
		@[@"стараться", @"totry, endeavour"],
		@[@"лучший", @"better,best"]
	];
}

-(NSArray*)japaneseLesson
{
	NSLog(@"! LESSON | Loading Japanese");
	
	return @[
	 @[@"日", @"ひ", @"sun"],
	 @[@"一", @"ひと", @"one"],
	 @[@"国", @"コク", @"country"],
	 @[@"人", @"ひと", @"person"],
	 @[@"年", @"ネン", @"year"],
	 @[@"大", @"おお", @"big"],
	 @[@"十", @"とお", @"ten"],
	 @[@"二", @"ふた", @"two"],
	 @[@"本", @"ホン", @"book"],
	 @[@"中", @"なか", @"inside"],
	 @[@"長", @"ながい", @"long"],
	 @[@"出", @"でる", @"exit"],
	 @[@"三", @"み", @"three"],
	 @[@"時", @"とき", @"hour"],
	 @[@"行", @"いく", @"going"],
	 @[@"見", @"みる", @"see"],
	 @[@"月", @"ゲツ", @"moon"],
	 @[@"後", @"のち", @"back"],
	 @[@"前", @"まえ", @"before"],
	 @[@"生", @"いきる", @"life"],
	 @[@"五", @"いつ", @"five"],
	 @[@"間", @"あいだ", @"space"],
	 @[@"上", @"うえ", @"above"],
	 @[@"東", @"トウ", @"east"],
	 @[@"四", @"よ", @"four"],
	 @[@"今", @"コン", @"now"],
	 @[@"金", @"かね", @"gold"],
	 @[@"九", @"ここの", @"nine"],
	 @[@"入", @"いる", @"enter"],
	 @[@"学", @"ガク", @"study"],
	 @[@"高", @"たかい", @"high"],
	 @[@"円", @"まるい", @"yen"],
	 @[@"子", @"こ", @"child"],
	 @[@"外", @"そと", @"outside"],
	 @[@"八", @"や", @"eight"],
	 @[@"六", @"む", @"six"],
	 @[@"下", @"した", @"low"],
	 @[@"来", @"くる", @"come"],
	 @[@"気", @"いき", @"spirit"],
	 @[@"小", @"ちいさい", @"small"],
	 @[@"七", @"なな", @"seven"],
	 @[@"山", @"サン", @"mountain"],
	 @[@"話", @"はなす", @"talk"],
	 @[@"女", @"おんな", @"woman"],
	 @[@"北", @"ホク", @"north"],
	 @[@"午", @"うま", @"noon"],
	 @[@"百", @"ヒャク", @"hundred"],
	 @[@"書", @"かく", @"write"],
	 @[@"先", @"さき", @"before"],
	 @[@"名", @"な", @"name"],
	 @[@"川", @"セン", @"river"],
	 @[@"千", @"セン", @"thousand"],
	 @[@"水", @"みず", @"water"],
	 @[@"半", @"ハン", @"half"],
	 @[@"男", @"おとこ", @"male"],
	 @[@"西", @"セイ", @"west"],
	 @[@"電", @"デン", @"electricity"],
	 @[@"校", @"コウ", @"exam"],
	 @[@"語", @"かたる", @"speech"],
	 @[@"土", @"ド", @"soil"],
	 @[@"木", @"き", @"wood"],
	 @[@"聞", @"きく", @"ask"],
	 @[@"食", @"くう", @"eat"],
	 @[@"車", @"シャ", @"car"],
	 @[@"何", @"なに", @"what"],
	 @[@"南", @"ナン", @"south"],
	 @[@"万", @"マン", @"10000"],
	 @[@"毎", @"ごと", @"every"],
	 @[@"白", @"しろ", @"white"],
	 @[@"天", @"あまつ", @"sky"],
	 @[@"母", @"はは", @"mama"],
	 @[@"火", @"ひ", @"fire"],
	 @[@"右", @"ウ", @"right"],
	 @[@"読", @"よむ", @"read"],
	 @[@"友", @"ユウ", @"friend"],
	 @[@"左", @"サ", @"left"],
	 @[@"休", @"やすむ", @"rest"],
	 @[@"父", @"ちち", @"father"],
	 @[@"雨", @"あめ", @"rain"],
	 @[@"会", @"あう", @"meet"],
	 @[@"同", @"おなじ", @"same"],
	 @[@"事", @"こと", @"fact"],
	 @[@"自", @"みずから", @"oneself"],
	 @[@"社", @"シャ", @"firm"],
	 @[@"発", @"たつ", @"emit"],
	 @[@"者", @"もの", @"person"],
	 @[@"地", @"チ", @"earth"],
	 @[@"業", @"ギョウ", @"arts"],
	 @[@"方", @"かた", @"person"],
	 @[@"新", @"あたらしい", @"new"],
	 @[@"場", @"ば", @"place"],
	 @[@"員", @"イ", @"member"],
	 @[@"立", @"たつ", @"stand up"],
	 @[@"開", @"ひらく", @"open"],
	 @[@"手", @"て", @"hand"],
	 @[@"力", @"リョク", @"exert"],
	 @[@"問", @"とう", @"ask"],
	 @[@"代", @"かわる", @"age"],
	 @[@"明", @"あかり", @"light"],
	 @[@"動", @"うごく", @"move"],
	 @[@"京", @"キョウ", @"capital"],
	 @[@"目", @"め", @"eye"],
	 @[@"通", @"とおる", @"avenue"],
	 @[@"言", @"いう", @"say"],
	 @[@"理", @"リ", @"truth"],
	 @[@"体", @"からだ", @"body"],
	 @[@"田", @"デン", @"rice paddy"],
	 @[@"主", @"ぬし", @"lord"],
	 @[@"題", @"ダイ", @"topic"],
	 @[@"意", @"", @"mind"],
	 @[@"不", @"フ", @"bad"],
	 @[@"作", @"つくる", @"make"],
	 @[@"用", @"ヨウ", @"use"],
	 @[@"度", @"たび", @"time"],
	 @[@"強", @"つよい", @"strong"],
	 @[@"公", @"コウ", @"prince"],
	 @[@"持", @"もつ", @"have"],
	 @[@"野", @"の", @"field"],
	 @[@"以", @"イ", @"because"],
	 @[@"思", @"おもう", @"think"],
	 @[@"家", @"いえ", @"home"],
	 @[@"世", @"よ", @"world"],
	 @[@"多", @"おおい", @"much"],
	 @[@"正", @"ただしい", @"justice"],
	 @[@"安", @"やすい", @"low"],
	 @[@"院", @"イン", @"Inst."],
	 @[@"心", @"りっしんべん", @"mind"],
	 @[@"界", @"カイ", @"world"],
	 @[@"教", @"おしえる", @"faith"],
	 @[@"文", @"ふみ", @"art"],
	 @[@"元", @"ゲン", @"origin"],
	 @[@"重", @"え", @"-fold"],
	 @[@"近", @"キン", @"akin"],
	 @[@"考", @"かんがえる", @"consider"],
	 @[@"画", @"えがく", @"picture"],
	 @[@"海", @"カイ", @"sea"],
	 @[@"売", @"うる", @"sell"],
	 @[@"知", @"しる", @"know"],
	 @[@"道", @"ドウ", @"moral"],
	 @[@"集", @"あつまる", @"meet"],
	 @[@"別", @"わかれる", @"fork"],
	 @[@"物", @"もの", @"thing"],
	 @[@"使", @"つかう", @"use"],
	 @[@"品", @"しな", @"goods"],
	 @[@"計", @"はかる", @"plan"],
	 @[@"死", @"しぬ", @"die"],
	 @[@"特", @"トク", @"special"],
	 @[@"私", @"わたくし", @"I"],
	 @[@"始", @"はじめる", @"begin"],
	 @[@"朝", @"チョウ", @"epoch"],
	 @[@"運", @"はこぶ", @"lot"],
	 @[@"終", @"おわる", @"end"],
	 @[@"台", @"うてな", @"a stand"],
	 @[@"広", @"ひろい", @"wide"],
	 @[@"住", @"すむ", @"live"],
	 @[@"真", @"ま", @"true"],
	 @[@"有", @"ユウ", @"have"],
	 @[@"口", @"くち", @"mouth"],
	 @[@"少", @"すくない", @"few"],
	 @[@"町", @"まち", @"town"],
	 @[@"料", @"リョウ", @"fee"],
	 @[@"工", @"コウ", @"craft"],
	 @[@"建", @"たてる", @"build"],
	 @[@"空", @"そら", @"sky"],
	 @[@"急", @"いそぐ", @"steep"],
	 @[@"止", @"とまる", @"halt"],
	 @[@"送", @"おくる", @"send"],
	 @[@"切", @"きる", @"cut"],
	 @[@"転", @"ころがる", @"change"],
	 @[@"研", @"ケン", @"polish"],
	 @[@"足", @"あし", @"leg"],
	 @[@"究", @"キュウ", @"study"],
	 @[@"楽", @"たのしい", @"ease"],
	 @[@"起", @"おきる", @"rouse"],
	 @[@"着", @"きる", @"don"],
	 @[@"店", @"みせ", @"shop"],
	 @[@"病", @"やむ", @"ill"],
	 @[@"質", @"たち", @"matter"],
	 @[@"待", @"まつ", @"wait"],
	 @[@"試", @"こころみる", @"try"],
	 @[@"族", @"ゾ", @"tribe"],
	 @[@"銀", @"ギン", @"silver"],
	 @[@"早", @"はやい", @"fast"],
	 @[@"映", @"うつる", @"reflect"],
	 @[@"親", @"おや", @"parent"],
	 @[@"験", @"あかし", @"effect"],
	 @[@"英", @"エイ", @"English"],
	 @[@"医", @"いやす", @"doctor"],
	 @[@"仕", @"つかえる", @"doing"],
	 @[@"去", @"さる", @"past"],
	 @[@"味", @"あじ", @"taste"],
	 @[@"写", @"うつす", @"copy"],
	 @[@"字", @"あざ", @"word"],
	 @[@"答", @"こたえる", @"answer"],
	 @[@"夜", @"よ", @"night"],
	 @[@"音", @"おと", @"noise"],
	 @[@"注", @"そそぐ", @"pour"],
	 @[@"帰", @"かえる", @"lead to"],
	 @[@"古", @"ふるい", @"old"],
	 @[@"歌", @"うた", @"sing"],
	 @[@"買", @"かう", @"buy"],
	 @[@"悪", @"わるい", @"bad"],
	 @[@"図", @"え", @"map"],
	 @[@"週", @"シュウ", @"week"],
	 @[@"室", @"むろ", @"room"],
	 @[@"歩", @"あるく", @"walk"],
	 @[@"風", @"かぜ", @"air"],
	 @[@"紙", @"かみ", @"paper"],
	 @[@"黒", @"くろ", @"black"],
	 @[@"花", @"カ", @"flower"],
	 @[@"春", @"シュン", @"springtime"],
	 @[@"赤", @"あか", @"red"],
	 @[@"青", @"あお", @"blue"],
	 @[@"館", @"やかた", @"palace"],
	 @[@"屋", @"オク", @"shop"],
	 @[@"色", @"ショク", @"color"],
	 @[@"走", @"ソウ", @"run"],
	 @[@"秋", @"あき", @"autumn"],
	 @[@"夏", @"なつ", @"summer"],
	 @[@"習", @"ならう", @"learn"],
	 @[@"駅", @"エキ", @"station"],
	 @[@"洋", @"ヨ", @"ocean"],
	 @[@"旅", @"たび", @"trip"],
	 @[@"服", @"フ", @"obey"],
	 @[@"夕", @"セキ", @"evening"],
	 @[@"借", @"かりる", @"rent"],
	 @[@"曜", @"ヨ", @"weekday"],
	 @[@"飲", @"のむ", @"take"],
	 @[@"肉", @"ニク", @"meat"],
	 @[@"貸", @"かす", @"lend"],
	 @[@"堂", @"ドウ", @"hall"],
	 @[@"鳥", @"チョウ", @"bird"],
	 @[@"飯", @"ハン", @"meal"],
	 @[@"勉", @"ベン", @"exertion"],
	 @[@"冬", @"ふゆ", @"winter"],
	 @[@"昼", @"ひる", @"noon"],
	 @[@"茶", @"チャ", @"tea"],
	 @[@"弟", @"テイ", @"younger brother"],
	 @[@"牛", @"ギュウ", @"cow"],
	 @[@"魚", @"うお", @"fish"],
	 @[@"兄", @"ケイ", @"big brother"],
	 @[@"犬", @"いぬ", @"dog"],
	 @[@"妹", @"マイ", @"younger sister"],
	 @[@"姉", @"あね", @"elder sister"],
	 @[@"漢", @"カ", @"China"],
	 @[@"政", @"まつりごと", @"politics"],
	 @[@"議", @"", @"debate"],
	 @[@"民", @"ミン", @"nation"],
	 @[@"連", @"つらなる", @"lead"],
	 @[@"対", @"あいて", @"even"],
	 @[@"部", @"ブ", @"dept"],
	 @[@"合", @"あう", @"0.1"],
	 @[@"市", @"シ", @"city"],
	 @[@"内", @"ナイ", @"home"],
	 @[@"相", @"あい", @"phase"],
	 @[@"定", @"さだめる", @"fix"],
	 @[@"回", @"まわる", @"game"],
	 @[@"選", @"えらぶ", @"elect"],
	 @[@"米", @"こめ", @"USA"],
	 @[@"実", @"み", @"truth"],
	 @[@"関", @"せき", @"barrier"],
	 @[@"決", @"きめる", @"fix"],
	 @[@"全", @"まったく", @"all"],
	 @[@"表", @"おもて", @"table"],
	 @[@"戦", @"いくさ", @"war"],
	 @[@"経", @"へる", @"warp"],
	 @[@"最", @"もっとも", @"most"],
	 @[@"現", @"あらわれる", @"actual"],
	 @[@"調", @"しらべる", @"tone"],
	 @[@"化", @"ばける", @"delude"],
	 @[@"当", @"あたる", @"hit"],
	 @[@"約", @"ヤク", @"shrink"],
	 @[@"首", @"シュ", @"neck"],
	 @[@"法", @"ホウ", @"law"],
	 @[@"性", @"さが", @"sex"],
	 @[@"要", @"ヨウ", @"need"],
	 @[@"制", @"セイ", @"law"],
	 @[@"治", @"おさめる", @"govt"],
	 @[@"務", @"ム", @"task"],
	 @[@"成", @"なる", @"get"],
	 @[@"期", @"キ", @"time"],
	 @[@"取", @"とる", @"take"],
	 @[@"都", @"ト", @"capital"],
	 @[@"和", @"やわらぐ", @"peace"],
	 @[@"機", @"はた", @"machine"],
	 @[@"平", @"たいら", @"flat"],
	 @[@"加", @"くわえる", @"add"],
	 @[@"受", @"うける", @"get"],
	 @[@"続", @"つづく", @"series"],
	 @[@"進", @"すすむ", @"proceed"],
	 @[@"数", @"かず", @"law"],
	 @[@"記", @"キ", @"scribe"],
	 @[@"初", @"はじめ", @"beginning"],
	 @[@"指", @"ゆび", @"finger"],
	 @[@"権", @"おもり", @"power"],
	 @[@"支", @"しんよう", @"branch"],
	 @[@"産", @"うむ", @"bear"],
	 @[@"点", @"つける", @"mark"],
	 @[@"報", @"むくいる", @"news"],
	 @[@"済", @"すむ", @"finish"],
	 @[@"活", @"いきる", @"living"],
	 @[@"原", @"ゲン", @"field"],
	 @[@"共", @"とも", @"all"],
	 @[@"得", @"える", @"get"],
	 @[@"解", @"とく", @"key"],
	 @[@"交", @"まじわる", @"mixing"],
	 @[@"資", @"", @"data"],
	 @[@"予", @"あらかじめ", @"I"],
	 @[@"向", @"むく", @"defy"],
	 @[@"際", @"きわ", @"side"],
	 @[@"勝", @"かつ", @"win"],
	 @[@"面", @"おも", @"face"],
	 @[@"告", @"コク", @"tell"],
	 @[@"反", @"そる", @"anti-"],
	 @[@"判", @"わかる", @"seal"],
	 @[@"認", @"みとめる", @"witness"],
	 @[@"参", @"まいる", @"die"],
	 @[@"利", @"リ", @"profit"],
	 @[@"組", @"くむ", @"braid"],
	 @[@"信", @"シ", @"truth"],
	 @[@"在", @"ザイ", @"exist"],
	 @[@"件", @"くだん", @"case"],
	 @[@"側", @"かわ", @"lean"],
	 @[@"任", @"まかせる", @"duty"],
	 @[@"引", @"ひく", @"tug"],
	 @[@"求", @"もとめる", @"want"],
	 @[@"所", @"ところ", @"place"],
	 @[@"次", @"つぐ", @"next"],
	 @[@"昨", @"サク", @"previous"],
	 @[@"論", @"ロン", @"argument"],
	 @[@"官", @"カン", @"bureaucrat"],
	 @[@"増", @"ます", @"add"],
	 @[@"係", @"かかる", @"duty"],
	 @[@"感", @"カン", @"feeling"],
	 @[@"情", @"なさけ", @"facts"],
	 @[@"投", @"なげる", @"join"],
	 @[@"示", @"しめす", @"show"],
	 @[@"変", @"かわる", @"change"],
	 @[@"打", @"うつ", @"hit"],
	 @[@"直", @"ただちに", @"fix"],
	 @[@"両", @"てる", @"two"],
	 @[@"式", @"シ", @"rite"],
	 @[@"確", @"たしか", @"firm"],
	 @[@"果", @"はたす", @"end"],
	 @[@"容", @"ヨウ", @"form"],
	 @[@"必", @"かならず", @"certain"],
	 @[@"演", @"エン", @"act"],
	 @[@"歳", @"とし", @"age"],
	 @[@"争", @"あらそう", @"argue"],
	 @[@"談", @"ダン", @"talk"],
	 @[@"能", @"ノウ", @"skill"],
	 @[@"位", @"くらい", @"some"],
	 @[@"置", @"おく", @"put"],
	 @[@"流", @"ながれる", @"flow"],
	 @[@"格", @"カク", @"rank"],
	 @[@"疑", @"うたがう", @"doubt"],
	 @[@"過", @"すぎる", @"error"],
	 @[@"局", @"つぼね", @"board"],
	 @[@"放", @"はなす", @"fire"],
	 @[@"常", @"つね", @"usual"],
	 @[@"状", @"ジョウ", @"form"],
	 @[@"球", @"キュウ", @"ball"],
	 @[@"職", @"ショク", @"work"],
	 @[@"与", @"あたえる", @"give"],
	 @[@"供", @"そなえる", @"offer"],
	 @[@"役", @"ヤク", @"war"],
	 @[@"構", @"かまえる", @"build"],
	 @[@"割", @"わる", @"cut"],
	 @[@"費", @"ついやす", @"cost"],
	 @[@"付", @"つける", @"attach"],
	 @[@"由", @"よし", @"a reason"],
	 @[@"説", @"セツ", @"rumor"],
	 @[@"難", @"かたい", @"defect"],
	 @[@"優", @"やさしい", @"excel"],
	 @[@"夫", @"おっと", @"man"],
	 @[@"収", @"おさめる", @"pay"],
	 @[@"断", @"たつ", @"warn"],
	 @[@"石", @"セキ", @"stone"],
	 @[@"違", @"ちがう", @"differ"],
	 @[@"消", @"きえる", @"cancel"],
	 @[@"神", @"かみ", @"mind"],
	 @[@"番", @"バン", @"turn"],
	 @[@"規", @"", @"measure"],
	 @[@"術", @"すべ", @"art"],
	 @[@"備", @"そなえる", @"equip"],
	 @[@"宅", @"タ", @"home"],
	 @[@"害", @"ガイ", @"harm"],
	 @[@"配", @"くばる", @"exile"],
	 @[@"警", @"いましめる", @"admonish"],
	 @[@"育", @"そだつ", @"rear"],
	 @[@"席", @"むしろ", @"mat"],
	 @[@"訪", @"おとずれる", @"visit"],
	 @[@"乗", @"のる", @"join"],
	 @[@"残", @"のこる", @"balance"],
	 @[@"想", @"おもう", @"idea"],
	 @[@"声", @"こえ", @"voice"],
	 @[@"念", @"ネン", @"idea"],
	 @[@"助", @"たすける", @"help"],
	 @[@"労", @"ろうする", @"toil"],
	 @[@"例", @"たとえる", @"usage"],
	 @[@"然", @"しか", @"so"],
	 @[@"限", @"かぎる", @"limit"],
	 @[@"追", @"ツイ", @"chase"],
	 @[@"商", @"ショウ", @"selling"],
	 @[@"葉", @"ヨウ", @"lobe"],
	 @[@"伝", @"つたわる", @"follow"],
	 @[@"働", @"はたらく", @"work"],
	 @[@"形", @"かた", @"form"],
	 @[@"景", @"ケ", @"view"],
	 @[@"落", @"おちる", @"drop"],
	 @[@"好", @"このむ", @"fond"],
	 @[@"退", @"しりぞく", @"repel"],
	 @[@"頭", @"あたま", @"head"],
	 @[@"負", @"まける", @"-"],
	 @[@"渡", @"わたる", @"ford"],
	 @[@"失", @"うしなう", @"loss"],
	 @[@"差", @"さす", @"margin"],
	 @[@"末", @"すえ", @"tip"],
	 @[@"守", @"まもる", @"obey"],
	 @[@"若", @"わかい", @"if"],
	 @[@"種", @"たね", @"kind"],
	 @[@"美", @"ビ", @"beauty"],
	 @[@"命", @"いのち", @"life"],
	 @[@"福", @"フ", @"luck"],
	 @[@"望", @"のぞむ", @"hope"],
	 @[@"非", @"あらず", @"un-"],
	 @[@"観", @"みる", @"look"],
	 @[@"察", @"サツ", @"judge"],
	 @[@"段", @"ダン", @"steps"],
	 @[@"横", @"よこ", @"side"],
	 @[@"深", @"ふかい", @"deep"],
	 @[@"申", @"もうす", @"3-5PM"],
	 @[@"様", @"さま", @"way"],
	 @[@"財", @"ザイ", @"money"],
	 @[@"港", @"みなと", @"harbor"],
	 @[@"識", @"シ", @"know"],
	 @[@"呼", @"コ", @"call"],
	 @[@"達", @"タツ", @"reach"],
	 @[@"良", @"よい", @"good"],
	 @[@"候", @"そうろう", @"season"],
	 @[@"程", @"ほど", @"law"],
	 @[@"満", @"みちる", @"full"],
	 @[@"敗", @"やぶれる", @"defeat"],
	 @[@"値", @"ね", @"cost"],
	 @[@"突", @"つく", @"stab"],
	 @[@"光", @"ひかる", @"ray"],
	 @[@"路", @"じ", @"road"],
	 @[@"科", @"", @"course"],
	 @[@"積", @"つむ", @"stack"],
	 @[@"他", @"ほか", @"other"],
	 @[@"処", @"ところ", @"act"],
	 @[@"太", @"ふとい", @"thick"],
	 @[@"客", @"キャク", @"guest"],
	 @[@"否", @"いな", @"no"],
	 @[@"師", @"", @"war"],
	 @[@"登", @"のぼる", @"ascend"],
	 @[@"易", @"やさしい", @"easy"],
	 @[@"速", @"はやい", @"fast"],
	 @[@"存", @"ソン", @"feel"],
	 @[@"飛", @"とぶ", @"fly"],
	 @[@"殺", @"ころす", @"kill"],
	 @[@"号", @"さけぶ", @"item"],
	 @[@"単", @"ひとえ", @"one"],
	 @[@"座", @"すわる", @"sit"],
	 @[@"破", @"やぶる", @"rip"],
	 @[@"除", @"のぞく", @"3)"],
	 @[@"完", @"カン", @"end"],
	 @[@"降", @"おりる", @"fall"],
	 @[@"責", @"せめる", @"blame"],
	 @[@"捕", @"とらえる", @"catch"],
	 @[@"危", @"あぶない", @"fear"],
	 @[@"給", @"たまう", @"wage"],
	 @[@"苦", @"くるしい", @"trial"],
	 @[@"迎", @"ゲイ", @"meet"],
	 @[@"園", @"エン", @"yard"],
	 @[@"具", @"そなえる", @"tool"],
	 @[@"辞", @"やめる", @"word"],
	 @[@"因", @"よる", @"cause"],
	 @[@"馬", @"うま", @"horse"],
	 @[@"愛", @"アイ", @"love"],
	 @[@"富", @"とむ", @"enrich"],
	 @[@"彼", @"かれ", @"he"],
	 @[@"未", @"いまだ", @"un-"],
	 @[@"舞", @"まう", @"flit"],
	 @[@"亡", @"ない", @"dying"],
	 @[@"冷", @"つめたい", @"cool"],
	 @[@"適", @"かなう", @"rare"],
	 @[@"婦", @"", @"wife"],
	 @[@"寄", @"よる", @"send"],
	 @[@"込", @"こむ", @"mixture"],
	 @[@"顔", @"かお", @"face"],
	 @[@"類", @"たぐい", @"kind"],
	 @[@"余", @"あまる", @"other"],
	 @[@"王", @"オウ", @"rule"],
	 @[@"返", @"かえす", @"fade"],
	 @[@"妻", @"サイ", @"wife"],
	 @[@"背", @"せ", @"back"],
	 @[@"熱", @"ネツ", @"heat"],
	 @[@"宿", @"やど", @"inn"],
	 @[@"薬", @"ヤク", @"enamel"]
	 ];
}

@end
