//
//  Lesson.m
//  Vocavularist
//
//  Created by Devine Lu Linvega on 2015-05-10.
//  Copyright (c) 2015 XXIIVV. All rights reserved.
//

#import "Lesson.h"
#import "xxiivvViewController.h"

NSArray * currentLesson;

@implementation Lesson

-(Lesson*)initWithLessonMode :(lessonMode)lessonMode
{
	if( lessonMode == kanjiKana ){ currentLesson = [self japaneseLesson]; }
    else if (lessonMode == korean) { currentLesson = [self koreanLesson]; }
	else{ currentLesson = [self russianLesson]; }
	
	return self;
}

-(NSString*)question:(int)lessonId
{
	return currentLesson[lessonId][0];
}

-(NSUInteger)length
{
	return [currentLesson count];
}

-(NSArray*)mistakesFromLessonId:(int)lessonId :(lessonMode)lessonMode
{
	// Make potential answers
	NSRange targetRange = NSMakeRange(0, lessonId+4);
	if(lessonId > 200){ targetRange = NSMakeRange(0, lessonId+1); }
	NSMutableArray * newArray = [NSMutableArray arrayWithArray:[currentLesson subarrayWithRange:targetRange]];
	
	[newArray removeObjectAtIndex:lessonId];
	
	newArray = [self shuffleArray:newArray];
	
	int targetField = (int)[newArray[0] count] -1;
	
	if( lessonMode == kanji ){ targetField = 2; }
	
	return @[newArray[0][targetField],newArray[1][targetField],newArray[2][targetField]];
}

-(NSString*)answerFromLessonId:(int)lessonId :(lessonMode)lessonMode
{
	int targetField = (int)[currentLesson[lessonId] count] -1;
	
	if( lessonMode == kanjiKana ){ targetField = 2; }
	return currentLesson[lessonId][targetField];
}

- (NSMutableArray*)shuffleArray:(NSMutableArray*)targetArray
{
	NSUInteger count = [targetArray count];
	for (NSUInteger i = 0; i < count; ++i) {
		NSInteger remainingCount = count - i;
		NSInteger exchangeIndex = i + arc4random_uniform((u_int32_t )remainingCount);
		[targetArray exchangeObjectAtIndex:i withObjectAtIndex:exchangeIndex];
	}
	
	return targetArray;
}


-(NSArray*)russianLesson
{
	NSLog(@"! LESSON | Loading Russian");
	
	return @[
		@[@"друг", @"friend"],
		@[@"большой", @"big, large, important"],
		@[@"и", @"and, though"],
		@[@"в", @"in, at"],
		@[@"не", @"not"],
		@[@"он", @"he"],
		@[@"на", @"on, it, at, to"],
		@[@"я", @"I"],
		@[@"что", @"what, that, why"],
		@[@"тот", @"that"],
		@[@"с", @"with, and, from, of"],
		@[@"а", @"while, and, but"],
		@[@"весь", @"all, everything"],
		@[@"это", @"that, this, it"],
		@[@"как", @"how, what, as, like"],
		@[@"она", @"she"],
		@[@"по", @"on, along, by"],
		@[@"но", @"but"],
		@[@"они", @"they"],
		@[@"к", @"to, for, by"],
		@[@"у", @"by, with, of"],
		@[@"ты", @"you, thou"],
		@[@"из", @"from, of, in"],
		@[@"мы", @"we"],
		@[@"за", @"behind, over, at, after"],
		@[@"вы", @"you"],
		@[@"так", @"so, thus, then"],
		@[@"же", @"and, asfor, but, same"],
		@[@"от", @"from, of, for"],
		@[@"сказать", @"tosay, tospeak"],
		@[@"этот", @"this"],
		@[@"который", @"which, who, that"],
		@[@"мочь", @"beable"],
		@[@"человек", @"man, person"],
		@[@"о", @"of, about, against"],
		@[@"один", @"one, some, alone"],
		@[@"ещё", @"still, yet"],
		@[@"бы", @"would"],
		@[@"такой", @"such, so, some"],
		@[@"только", @"only, merely, but"],
		@[@"себя", @"myself, himself, herself", @"pron"],
		@[@"своё", @"my, our"],
		@[@"какой", @"what, which, how"],
		@[@"когда", @"when, while, as"],
		@[@"уже", @"already, bynow"],
		@[@"для", @"for, to"],
		@[@"вот", @"here, there, this is, that's"],
		@[@"кто", @"who, that, some"],
		@[@"да", @"yes, but"],
		@[@"говорить", @"to say, to tell, to speak"],
		@[@"год", @"year"],
		@[@"знать", @"to know, beaware"],
		@[@"мой", @"my, mine"],
		@[@"до", @"to, up to, about, before"],
		@[@"или", @"or"],
		@[@"если", @"if"],
		@[@"время", @"time, season"],
		@[@"рука", @"hand, arm"],
		@[@"нет", @"no, not, but"],
		@[@"самый", @"most, thevery, thesame"],
		@[@"ни", @"nota, not, neither"],
		@[@"стать", @"become, begin, come"],
		@[@"даже", @"even"],
		@[@"другой", @"other, another, different"],
		@[@"наш", @"our, ours"],
		@[@"свой", @"my, our, your"],
		@[@"ну", @"now, right, well, comeon"],
		@[@"под", @"under, for, towards, to"],
		@[@"где", @"where"],
		@[@"дело", @"business, affair, matter"],
		@[@"есть", @"toeat, tobe"],
		@[@"сам", @"myself, yourself"],
		@[@"раз", @"time, once, since"],
		@[@"чтобы", @"that, inorderthat"],
		@[@"два", @"two"],
		@[@"там", @"there, then"],
		@[@"чем", @"instead of"],
		@[@"глаз", @"eye, sight"],
		@[@"жизнь", @"life"],
		@[@"первый", @"first, front, former"],
		@[@"день", @"day"],
		@[@"тут", @"here, now, then"],
		@[@"во", @"in, at - super, exactly"],
		@[@"ничто", @"nothing"],
		@[@"потом", @"afterwards, then"],
		@[@"очень", @"very"],
		@[@"со", @"with"],
		@[@"хотеть", @"towant, like"],
		@[@"ли", @"whether, if"],
		@[@"при", @"attached to, in the presence of, by"],
		@[@"голова", @"head, mind, brains"],
		@[@"надо", @"over, above, ought to"],
		@[@"без", @"without"],
		@[@"видеть", @"to see"],
		@[@"идти", @"to go, come"],
		@[@"теперь", @"now, nowadays"],
		@[@"тоже", @"also, aswell, too"],
		@[@"стоять", @"tostand, be, standup"],
		@[@"дом", @"house, home"],
		@[@"сейчас", @"now, presently, soon"],
		@[@"можно", @"onecan"],
		@[@"после", @"after, afterwards"],
		@[@"слово", @"word"],
		@[@"здесь", @"here"],
		@[@"думать", @"to think, to believe"],
		@[@"место", @"place, seat"],
		@[@"спросить", @"to ask"],
		@[@"через", @"through, across"],
		@[@"лицо", @"face, person"],
		@[@"что", @"what, which, that"],
		@[@"тогда", @"then"],
		@[@"ведь", @"you see, you know"],
		@[@"хороший", @"good, nice"],
		@[@"каждый", @"each, every"],
		@[@"новый", @"new, modern"],
		@[@"жить", @"to live"],
		@[@"должный", @"due, proper"],
		@[@"смотреть", @"to look, watch"],
		@[@"почему", @"why"],
		@[@"потому", @"that's why"],
		@[@"сторона", @"side, party"],
		@[@"просто", @"simply"],
		@[@"нога", @"foot, leg"],
		@[@"сидеть", @"to sit"],
		@[@"понять", @"to understand, realize"],
		@[@"иметь", @"to have, own"],
		@[@"конечный", @"final, last"],
		@[@"делать", @"todo, make"],
		@[@"вдруг", @"suddenly"],
		@[@"над", @"above, over"],
		@[@"взять", @"to take"],
		@[@"никто", @"nobody"],
		@[@"сделать", @"todo, make, finish"],
		@[@"дверь", @"door"],
		@[@"перед", @"before, in front of"],
		@[@"нужный", @"necessary"],
		@[@"понимать", @"to understand"],
		@[@"казаться", @"to seem, appear"],
		@[@"работа", @"work, job"],
		@[@"три", @"three"],
		@[@"ваш", @"yours"],
		@[@"уж", @"really, already"],
		@[@"земля", @"earth, land, soil"],
		@[@"конец", @"end, distance"],
		@[@"несколько", @"several,some"],
		@[@"час", @"hour, time"],
		@[@"голос", @"voice"],
		@[@"город", @"town, city"],
		@[@"последний", @"last, the latest, new"],
		@[@"пока", @"for the present"],
		@[@"хорошо", @"well"],
		@[@"давать", @"to give, let, allow"],
		@[@"вода", @"water"],
		@[@"более", @"more"],
		@[@"хотя", @"although"],
		@[@"всегда", @"always"],
		@[@"второй", @"second"],
		@[@"куда", @"where, what for, much"],
		@[@"пойти", @"to go"],
		@[@"стол", @"table, desk, board"],
		@[@"ребёнок", @"child, kid, infant"],
		@[@"увидеть", @"to see"],
		@[@"сила", @"strength, force"],
		@[@"отец", @"father"],
		@[@"женщина", @"woman"],
		@[@"машина", @"car, machine, engine"],
		@[@"случай", @"case, occasion, incident"],
		@[@"ночь", @"night"],
		@[@"сразу", @"atonce, rightaway, just"],
		@[@"мир", @"world"],
		@[@"совсем", @"quite, entirely, totally"],
		@[@"остаться", @"to remain,stay"],
		@[@"об", @"about, of"],
		@[@"вид", @"appearance, look, view"],
		@[@"выйти", @"togoout, comeout, appear"],
		@[@"дать", @"to give"],
		@[@"работать", @"to work"],
		@[@"любить", @"to love"],
		@[@"старый", @"old"],
		@[@"почти", @"almost"],
		@[@"ряд", @"row, line"],
		@[@"оказаться", @"find oneself, turnout"],
		@[@"начало", @"beginning, origin, source"],
		@[@"твой", @"your, yours"],
		@[@"вопрос", @"question, matter, problem"],
		@[@"много", @"many, much"],
		@[@"война", @"war"],
		@[@"снова", @"again"],
		@[@"ответить", @"to answer, reply"],
		@[@"между", @"between, among"],
		@[@"подумать", @"to think"],
		@[@"опять", @"again"],
		@[@"белый", @"white"],
		@[@"деньги", @"money"],
		@[@"значить", @"to mean, signify"],
		@[@"про", @"about, for"],
		@[@"лишь", @"only, as soon as"],
		@[@"минута", @"minute, moment"],
		@[@"жена", @"wife"],
		@[@"посмотреть", @"to take a look, watch, inspect"],
		@[@"правда", @"truth"],
		@[@"главный", @"main, chief"],
		@[@"страна", @"country"],
		@[@"свет", @"light, world"],
		@[@"ждать", @"to wait"],
		@[@"мать", @"mother"],
		@[@"будто", @"as if, as though"],
		@[@"никогда", @"never"],
		@[@"товарищ", @"comrade, friend"],
		@[@"дорога", @"road, way, journey"],
		@[@"однако", @"however, though"],
		@[@"лежать", @"to lie, be situated"],
		@[@"именно", @"namely, just"],
		@[@"окно", @"window, windowsill"],
		@[@"никакой", @"no, none"],
		@[@"найти", @"to find, discover, consider"],
		@[@"писать", @"to write"],
		@[@"комната", @"a room"],
		@[@"Москва", @"Moscow"],
		@[@"часть", @"part, share, department"],
		@[@"вообще", @"in general, altogether, on the whole"],
		@[@"книга", @"a book"],
		@[@"маленький", @"small,little"],
		@[@"улица", @"street"],
		@[@"решить", @"to decide, solve"],
		@[@"далекий", @"distant, remote"],
		@[@"душа", @"soul, spirit"],
		@[@"чуть", @"hardly, slightly"],
		@[@"вернуться", @"to return"],
		@[@"утро", @"morning"],
		@[@"некоторый", @"some"],
		@[@"считать", @"to count, consider"],
		@[@"сколько", @"how much, how many"],
		@[@"помнить", @"to remember"],
		@[@"вечер", @"evening"],
		@[@"пол", @"floor, sex"],
		@[@"таки", @"after all"],
		@[@"получить", @"to receive, get, obtain"],
		@[@"народ", @"people, nation"],
		@[@"плечо", @"shoulder, upperarm"],
		@[@"хоть", @"even, if you want, though"],
		@[@"сегодня", @"today"],
		@[@"бог", @"god"],
		@[@"вместе", @"together"],
		@[@"взгляд", @"look, glance, view"],
		@[@"ходить", @"to go, walk"],
		@[@"зачем", @"what for, why"],
		@[@"советский", @"Soviet"],
		@[@"русский", @"Russian"],
		@[@"бывать", @"be, visit, happen"],
		@[@"полный", @"full, complete"],
		@[@"прийти", @"tocome,arrive"],
		@[@"палец", @"finger,toe"],
		@[@"Россия", @"Russia"],
		@[@"любой", @"any,every"],
		@[@"история", @"history,story,event"],
		@[@"наконец", @"atlast,finally"],
		@[@"мысль", @"thought,idea"],
		@[@"узнать", @"toknow,learn,recognize"],
		@[@"назад", @"back,backwards"],
		@[@"общий", @"general,common"],
		@[@"заметить", @"tonotice,observe"],
		@[@"словно", @"asif,like"],
		@[@"прошлый", @"past"],
		@[@"уйти", @"to leave,go away"],
		@[@"известный", @"well-known,famous"],
		@[@"давно", @"longago"],
		@[@"слышать", @"tohear"],
		@[@"слушать", @"tolisten,hear"],
		@[@"бояться", @"tobeafraid,fear"],
		@[@"сын", @"son"],
		@[@"нельзя", @"itisimpossible,can't"],
		@[@"прямо", @"straight,frankly"],
		@[@"долго", @"foralongtime"],
		@[@"быстро", @"fast,quickly"],
		@[@"лес", @"forest"],
		@[@"похожий", @"similar,alike"],
		@[@"пора", @"time;pore"],
		@[@"пять", @"five"],
		@[@"глядеть", @"tolook,gaze"],
		@[@"оно", @"it"],
		@[@"сесть", @"tosit"],
		@[@"имя", @"name"],
		@[@"ж", @"and,asfor,but"],
		@[@"разговор", @"talk,conversation"],
		@[@"тело", @"body"],
		@[@"молодой", @"young;bridegroom(asa)"],
		@[@"стена", @"wall"],
		@[@"красный", @"red"],
		@[@"читать", @"toread"],
		@[@"право", @"right"],
		@[@"старик", @"oldman"],
		@[@"ранний", @"early"],
		@[@"хотеться", @"want,like"],
		@[@"мама", @"mummy,mum"],
		@[@"оставаться", @"toremain,stay"],
		@[@"высокий", @"tall,high"],
		@[@"путь", @"way,track,path"],
		@[@"поэтому", @"therefore"],
		@[@"совершенно", @"absolutely,quite"],
		@[@"кроме", @"except,besides"],
		@[@"тысяча", @"athousand"],
		@[@"месяц", @"month"],
		@[@"брать", @"totake;hire"],
		@[@"написать", @"towrite"],
		@[@"целый", @"intact,whole,entire"],
		@[@"огромный", @"huge,enormous"],
		@[@"начинать", @"tobegin"],
		@[@"спина", @"back"],
		@[@"настоящий", @"present;real,true"],
		@[@"пусть", @"let's,though"],
		@[@"язык", @"tongue,language"],
		@[@"точно", @"exactly"],
		@[@"среди", @"among"],
		@[@"чувствовать", @"tofeel"],
		@[@"сердце", @"heart"],
		@[@"вести", @"tolead"],
		@[@"иногда", @"sometimes"],
		@[@"мальчик", @"boy"],
		@[@"успеть", @"tobeintime,besuccessful"],
		@[@"небо", @"sky"],
		@[@"живой", @"living,live,lively"],
		@[@"смерть", @"death"],
		@[@"продолжать", @"tocontinue"],
		@[@"девушка", @"girl,miss"],
		@[@"образ", @"shape,form,image"],
		@[@"ко", @"to,towards,by"],
		@[@"забыть", @"toforget"],
		@[@"вокруг", @"around"],
		@[@"письмо", @"letter"],
		@[@"власть", @"power"],
		@[@"чёрный", @"black"],
		@[@"пройти", @"topass,goby,beover"],
		@[@"появиться", @"toappear,showup"],
		@[@"воздух", @"air"],
		@[@"разный", @"different"],
		@[@"выходить", @"togoout;nurse"],
		@[@"просить", @"toask"],
		@[@"брат", @"brother"],
		@[@"собственный", @"one'sown"],
		@[@"отношение", @"relationship,attitude"],
		@[@"затем", @"then,afterthat"],
		@[@"пытаться", @"totry"],
		@[@"показать", @"toshow,display"],
		@[@"вспомнить", @"toremember,recall"],
		@[@"система", @"system"],
		@[@"четыре", @"four"],
		@[@"квартира", @"flat,apartment"],
		@[@"держать", @"tohold,keep"],
		@[@"также", @"also,aswell,too"],
		@[@"любовь", @"love"],
		@[@"солдат", @"soldier"],
		@[@"откуда", @"where…from"],
		@[@"чтоб", @"that,inorderthat,"],
		@[@"называть", @"tocall,name,"],
		@[@"третий", @"third"],
		@[@"хозяин", @"master,boss,host"],
		@[@"вроде", @"like,notunlike"],
		@[@"уходить", @"toleave,goaway"],
		@[@"подойти", @"toapproach,comeup"],
		@[@"поднять", @"tolift,raise"],
		@[@"особенно", @"especially,particularly"],
		@[@"спрашивать", @"toask,inquire"],
		@[@"начальник", @"chief,head,superior"],
		@[@"оба", @"both"],
		@[@"бросить", @"tothrow"],
		@[@"школа", @"school"],
		@[@"парень", @"boy,fellow,guy"],
		@[@"кровь", @"blood"],
		@[@"двадцать", @"twenty"],
		@[@"солнце", @"sun"],
		@[@"неделя", @"week"],
		@[@"послать", @"tosend,dispatch"],
		@[@"находиться", @"tobefound,turnup"],
		@[@"ребята", @"guys,children"],
		@[@"поставить", @"toput,place,set"],
		@[@"встать", @"togetup,rise,standup"],
		@[@"например", @"forexample,forinstance"],
		@[@"шаг", @"step"],
		@[@"мужчина", @"man,male"],
		@[@"равно", @"alike,inlikemanner"],
		@[@"нос", @"nose"],
		@[@"мало", @"little,few,"],
		@[@"внимание", @"attention"],
		@[@"капитан", @"captain,master"],
		@[@"ухо", @"ear"],
		@[@"туда", @"there"],
		@[@"сюда", @"here"],
		@[@"играть", @"toplay"],
		@[@"следовать", @"tofollow,comenext"],
		@[@"рассказать", @"totell,narrate"],
		@[@"великий", @"great"],
		@[@"действительно", @"indeed,really"],
		@[@"слишком", @"too,toomuch"],
		@[@"тяжёлый", @"heavy"],
		@[@"спать", @"tosleep"],
		@[@"оставить", @"to leave, abandon"],
		@[@"войти", @"to enter, come in"],
		@[@"длинный", @"long"],
		@[@"чувство", @"feeling"],
		@[@"молчать", @"to keep silence"],
		@[@"рассказывать", @"to tell, narrate,"],
		@[@"отвечать", @"to answer, reply,"],
		@[@"становиться", @"to stand, to become"],
		@[@"остановиться", @"to stop"],
		@[@"берег", @"bank, shore, coast"],
		@[@"семья", @"family"],
		@[@"искать", @"to search"],
		@[@"генерал", @"general"],
		@[@"момент", @"moment, instant"],
		@[@"десять", @"ten"],
		@[@"начать", @"to begin"],
		@[@"следующий", @"next, following"],
		@[@"личный", @"personal"],
		@[@"уйти", @"to leave,go away"],
		@[@"труд", @"labour,work"],
		@[@"верить", @"to believe"],
		@[@"группа", @"group"],
		@[@"немного", @"alittle"],
		@[@"впрочем", @"however,though"],
		@[@"видно", @"evidently,obviously"],
		@[@"являться", @"to appear"],
		@[@"муж", @"husband"],
		@[@"разве", @"really?, perhaps"],
		@[@"движение", @"movement"],
		@[@"порядок", @"order"],
		@[@"ответ", @"answer, reply"],
		@[@"тихо", @"quietly, softly, slowly"],
		@[@"знакомый", @"familiar, acquainted"],
		@[@"газета", @"newspaper"],
		@[@"помощь", @"help"],
		@[@"сильный", @"strong, powerful"],
		@[@"скорый", @"quick, fast"],
		@[@"собака", @"dog"],
		@[@"дерево", @"tree"],
		@[@"снег", @"snow"],
		@[@"сон", @"dream"],
		@[@"смысл", @"sense, meaning, purpose"],
		@[@"смочь", @"to be able"],
		@[@"против", @"against, opposite, contrary to"],
		@[@"бежать", @"to run, hurry"],
		@[@"двор", @"yard, court"],
		@[@"форма", @"form, shape, uniform"],
		@[@"простой", @"simple, easy, plain"],
		@[@"приехать", @"to arrive, come"],
		@[@"иной", @"different, other"],
		@[@"кричать", @"to cry, shout"],
		@[@"возможность", @"possibility, opportunity, chance"],
		@[@"общество", @"society"],
		@[@"зеленый", @"green"],
		@[@"грудь", @"breast, chest"],
		@[@"угол", @"corner, angle"],
		@[@"открыть", @"to open"],
		@[@"происходить", @"to happen, occur, takeplace"],
		@[@"ладно", @"inharmony ,well, allright"],
		@[@"черный", @"black"],
		@[@"век", @"century, age"],
		@[@"карман", @"pocket"],
		@[@"ехать", @"togo, ride, drive, travel"],
		@[@"немец", @"German"],
		@[@"наверное", @"probably, most likely"],
		@[@"губа", @"lip"],
		@[@"дядя", @"uncle"],
		@[@"приходить", @"to come, arrive"],
		@[@"часто", @"often"],
		@[@"домой", @"home"],
		@[@"огонь", @"fire"],
		@[@"писатель", @"writer"],
		@[@"армия", @"army"],
		@[@"состояние", @"state, condition, fortune"],
		@[@"зуб", @"tooth"],
		@[@"очередь", @"line, queue, turn"],
		@[@"кой", @"which"],
		@[@"подняться", @"torise, climb"],
		@[@"камень", @"stone"],
		@[@"гость", @"guest"],
		@[@"показаться", @"to appear, come insight"],
		@[@"ветер", @"wind"],
		@[@"собираться", @"to gather together, assemble"],
		@[@"попасть", @"to hit, to find one self"],
		@[@"принять", @"to take, admit, accept"],
		@[@"сначала", @"at first, from the beginning"],
		@[@"либо", @"or"],
		@[@"поехать", @"to depart, setoff"],
		@[@"услышать", @"to hear"],
		@[@"уметь", @"to beable, know, can"],
		@[@"случиться", @"to happen"],
		@[@"странный", @"strange"],
		@[@"единственный", @"only, sole"],
		@[@"рота", @"company(military)"],
		@[@"закон", @"law, act, statue"],
		@[@"короткий", @"short"],
		@[@"море", @"sea"],
		@[@"добрый", @"kind"],
		@[@"темный", @"dark"],
		@[@"гора", @"mountain, hill"],
		@[@"врач", @"physician, doctor"],
		@[@"край", @"border, edge, land, country"],
		@[@"стараться", @"totry, endeavour"],
		@[@"лучший", @"better,best"]
	];
}

-(NSArray*)japaneseLesson
{
	NSLog(@"! LESSON | Loading Japanese");
	
	return @[
	 @[@"日", @"ひ", @"sun"],
	 @[@"一", @"ひと", @"one"],
	 @[@"国", @"コク", @"country"],
	 @[@"人", @"ひと", @"person"],
	 @[@"年", @"ネン", @"year"],
	 @[@"大", @"おお", @"big"],
	 @[@"十", @"とお", @"ten"],
	 @[@"二", @"ふた", @"two"],
	 @[@"本", @"ホン", @"book"],
	 @[@"中", @"なか", @"inside"],
	 @[@"長", @"ながい", @"long"],
	 @[@"出", @"でる", @"exit"],
	 @[@"三", @"み", @"three"],
	 @[@"時", @"とき", @"hour"],
	 @[@"行", @"いく", @"going"],
	 @[@"見", @"みる", @"see"],
	 @[@"月", @"ゲツ", @"moon"],
	 @[@"後", @"のち", @"back"],
	 @[@"前", @"まえ", @"before"],
	 @[@"生", @"いきる", @"life"],
	 @[@"五", @"いつ", @"five"],
	 @[@"間", @"あいだ", @"space"],
	 @[@"上", @"うえ", @"above"],
	 @[@"東", @"トウ", @"east"],
	 @[@"四", @"よ", @"four"],
	 @[@"今", @"コン", @"now"],
	 @[@"金", @"かね", @"gold"],
	 @[@"九", @"ここの", @"nine"],
	 @[@"入", @"いる", @"enter"],
	 @[@"学", @"ガク", @"study"],
	 @[@"高", @"たかい", @"high"],
	 @[@"円", @"まるい", @"yen"],
	 @[@"子", @"こ", @"child"],
	 @[@"外", @"そと", @"outside"],
	 @[@"八", @"や", @"eight"],
	 @[@"六", @"む", @"six"],
	 @[@"下", @"した", @"low"],
	 @[@"来", @"くる", @"come"],
	 @[@"気", @"いき", @"spirit"],
	 @[@"小", @"ちいさい", @"small"],
	 @[@"七", @"なな", @"seven"],
	 @[@"山", @"サン", @"mountain"],
	 @[@"話", @"はなす", @"talk"],
	 @[@"女", @"おんな", @"woman"],
	 @[@"北", @"ホク", @"north"],
	 @[@"午", @"うま", @"noon"],
	 @[@"百", @"ヒャク", @"hundred"],
	 @[@"書", @"かく", @"write"],
	 @[@"先", @"さき", @"before"],
	 @[@"名", @"な", @"name"],
	 @[@"川", @"セン", @"river"],
	 @[@"千", @"セン", @"thousand"],
	 @[@"水", @"みず", @"water"],
	 @[@"半", @"ハン", @"half"],
	 @[@"男", @"おとこ", @"male"],
	 @[@"西", @"セイ", @"west"],
	 @[@"電", @"デン", @"electricity"],
	 @[@"校", @"コウ", @"exam"],
	 @[@"語", @"かたる", @"speech"],
	 @[@"土", @"ド", @"soil"],
	 @[@"木", @"き", @"wood"],
	 @[@"聞", @"きく", @"ask"],
	 @[@"食", @"くう", @"eat"],
	 @[@"車", @"シャ", @"car"],
	 @[@"何", @"なに", @"what"],
	 @[@"南", @"ナン", @"south"],
	 @[@"万", @"マン", @"10000"],
	 @[@"毎", @"ごと", @"every"],
	 @[@"白", @"しろ", @"white"],
	 @[@"天", @"あまつ", @"sky"],
	 @[@"母", @"はは", @"mama"],
	 @[@"火", @"ひ", @"fire"],
	 @[@"右", @"ウ", @"right"],
	 @[@"読", @"よむ", @"read"],
	 @[@"友", @"ユウ", @"friend"],
	 @[@"左", @"サ", @"left"],
	 @[@"休", @"やすむ", @"rest"],
	 @[@"父", @"ちち", @"father"],
	 @[@"雨", @"あめ", @"rain"],
	 @[@"会", @"あう", @"meet"],
	 @[@"同", @"おなじ", @"same"],
	 @[@"事", @"こと", @"fact"],
	 @[@"自", @"みずから", @"oneself"],
	 @[@"社", @"シャ", @"firm"],
	 @[@"発", @"たつ", @"emit"],
	 @[@"者", @"もの", @"person"],
	 @[@"地", @"チ", @"earth"],
	 @[@"業", @"ギョウ", @"arts"],
	 @[@"方", @"かた", @"person"],
	 @[@"新", @"あたらしい", @"new"],
	 @[@"場", @"ば", @"place"],
	 @[@"員", @"イ", @"member"],
	 @[@"立", @"たつ", @"stand up"],
	 @[@"開", @"ひらく", @"open"],
	 @[@"手", @"て", @"hand"],
	 @[@"力", @"リョク", @"exert"],
	 @[@"問", @"とう", @"ask"],
	 @[@"代", @"かわる", @"age"],
	 @[@"明", @"あかり", @"light"],
	 @[@"動", @"うごく", @"move"],
	 @[@"京", @"キョウ", @"capital"],
	 @[@"目", @"め", @"eye"],
	 @[@"通", @"とおる", @"avenue"],
	 @[@"言", @"いう", @"say"],
	 @[@"理", @"リ", @"truth"],
	 @[@"体", @"からだ", @"body"],
	 @[@"田", @"デン", @"rice paddy"],
	 @[@"主", @"ぬし", @"lord"],
	 @[@"題", @"ダイ", @"topic"],
	 @[@"意", @"", @"mind"],
	 @[@"不", @"フ", @"bad"],
	 @[@"作", @"つくる", @"make"],
	 @[@"用", @"ヨウ", @"use"],
	 @[@"度", @"たび", @"time"],
	 @[@"強", @"つよい", @"strong"],
	 @[@"公", @"コウ", @"prince"],
	 @[@"持", @"もつ", @"have"],
	 @[@"野", @"の", @"field"],
	 @[@"以", @"イ", @"because"],
	 @[@"思", @"おもう", @"think"],
	 @[@"家", @"いえ", @"home"],
	 @[@"世", @"よ", @"world"],
	 @[@"多", @"おおい", @"much"],
	 @[@"正", @"ただしい", @"justice"],
	 @[@"安", @"やすい", @"low"],
	 @[@"院", @"イン", @"Inst."],
	 @[@"心", @"りっしんべん", @"mind"],
	 @[@"界", @"カイ", @"world"],
	 @[@"教", @"おしえる", @"faith"],
	 @[@"文", @"ふみ", @"art"],
	 @[@"元", @"ゲン", @"origin"],
	 @[@"重", @"え", @"-fold"],
	 @[@"近", @"キン", @"akin"],
	 @[@"考", @"かんがえる", @"consider"],
	 @[@"画", @"えがく", @"picture"],
	 @[@"海", @"カイ", @"sea"],
	 @[@"売", @"うる", @"sell"],
	 @[@"知", @"しる", @"know"],
	 @[@"道", @"ドウ", @"moral"],
	 @[@"集", @"あつまる", @"meet"],
	 @[@"別", @"わかれる", @"fork"],
	 @[@"物", @"もの", @"thing"],
	 @[@"使", @"つかう", @"use"],
	 @[@"品", @"しな", @"goods"],
	 @[@"計", @"はかる", @"plan"],
	 @[@"死", @"しぬ", @"die"],
	 @[@"特", @"トク", @"special"],
	 @[@"私", @"わたくし", @"I"],
	 @[@"始", @"はじめる", @"begin"],
	 @[@"朝", @"チョウ", @"epoch"],
	 @[@"運", @"はこぶ", @"lot"],
	 @[@"終", @"おわる", @"end"],
	 @[@"台", @"うてな", @"a stand"],
	 @[@"広", @"ひろい", @"wide"],
	 @[@"住", @"すむ", @"live"],
	 @[@"真", @"ま", @"true"],
	 @[@"有", @"ユウ", @"have"],
	 @[@"口", @"くち", @"mouth"],
	 @[@"少", @"すくない", @"few"],
	 @[@"町", @"まち", @"town"],
	 @[@"料", @"リョウ", @"fee"],
	 @[@"工", @"コウ", @"craft"],
	 @[@"建", @"たてる", @"build"],
	 @[@"空", @"そら", @"sky"],
	 @[@"急", @"いそぐ", @"steep"],
	 @[@"止", @"とまる", @"halt"],
	 @[@"送", @"おくる", @"send"],
	 @[@"切", @"きる", @"cut"],
	 @[@"転", @"ころがる", @"change"],
	 @[@"研", @"ケン", @"polish"],
	 @[@"足", @"あし", @"leg"],
	 @[@"究", @"キュウ", @"study"],
	 @[@"楽", @"たのしい", @"ease"],
	 @[@"起", @"おきる", @"rouse"],
	 @[@"着", @"きる", @"don"],
	 @[@"店", @"みせ", @"shop"],
	 @[@"病", @"やむ", @"ill"],
	 @[@"質", @"たち", @"matter"],
	 @[@"待", @"まつ", @"wait"],
	 @[@"試", @"こころみる", @"try"],
	 @[@"族", @"ゾ", @"tribe"],
	 @[@"銀", @"ギン", @"silver"],
	 @[@"早", @"はやい", @"fast"],
	 @[@"映", @"うつる", @"reflect"],
	 @[@"親", @"おや", @"parent"],
	 @[@"験", @"あかし", @"effect"],
	 @[@"英", @"エイ", @"English"],
	 @[@"医", @"いやす", @"doctor"],
	 @[@"仕", @"つかえる", @"doing"],
	 @[@"去", @"さる", @"past"],
	 @[@"味", @"あじ", @"taste"],
	 @[@"写", @"うつす", @"copy"],
	 @[@"字", @"あざ", @"word"],
	 @[@"答", @"こたえる", @"answer"],
	 @[@"夜", @"よ", @"night"],
	 @[@"音", @"おと", @"noise"],
	 @[@"注", @"そそぐ", @"pour"],
	 @[@"帰", @"かえる", @"lead to"],
	 @[@"古", @"ふるい", @"old"],
	 @[@"歌", @"うた", @"sing"],
	 @[@"買", @"かう", @"buy"],
	 @[@"悪", @"わるい", @"bad"],
	 @[@"図", @"え", @"map"],
	 @[@"週", @"シュウ", @"week"],
	 @[@"室", @"むろ", @"room"],
	 @[@"歩", @"あるく", @"walk"],
	 @[@"風", @"かぜ", @"air"],
	 @[@"紙", @"かみ", @"paper"],
	 @[@"黒", @"くろ", @"black"],
	 @[@"花", @"カ", @"flower"],
	 @[@"春", @"シュン", @"springtime"],
	 @[@"赤", @"あか", @"red"],
	 @[@"青", @"あお", @"blue"],
	 @[@"館", @"やかた", @"palace"],
	 @[@"屋", @"オク", @"shop"],
	 @[@"色", @"ショク", @"color"],
	 @[@"走", @"ソウ", @"run"],
	 @[@"秋", @"あき", @"autumn"],
	 @[@"夏", @"なつ", @"summer"],
	 @[@"習", @"ならう", @"learn"],
	 @[@"駅", @"エキ", @"station"],
	 @[@"洋", @"ヨ", @"ocean"],
	 @[@"旅", @"たび", @"trip"],
	 @[@"服", @"フ", @"obey"],
	 @[@"夕", @"セキ", @"evening"],
	 @[@"借", @"かりる", @"rent"],
	 @[@"曜", @"ヨ", @"weekday"],
	 @[@"飲", @"のむ", @"take"],
	 @[@"肉", @"ニク", @"meat"],
	 @[@"貸", @"かす", @"lend"],
	 @[@"堂", @"ドウ", @"hall"],
	 @[@"鳥", @"チョウ", @"bird"],
	 @[@"飯", @"ハン", @"meal"],
	 @[@"勉", @"ベン", @"exertion"],
	 @[@"冬", @"ふゆ", @"winter"],
	 @[@"昼", @"ひる", @"noon"],
	 @[@"茶", @"チャ", @"tea"],
	 @[@"弟", @"テイ", @"younger brother"],
	 @[@"牛", @"ギュウ", @"cow"],
	 @[@"魚", @"うお", @"fish"],
	 @[@"兄", @"ケイ", @"big brother"],
	 @[@"犬", @"いぬ", @"dog"],
	 @[@"妹", @"マイ", @"younger sister"],
	 @[@"姉", @"あね", @"elder sister"],
	 @[@"漢", @"カ", @"China"],
	 @[@"政", @"まつりごと", @"politics"],
	 @[@"議", @"", @"debate"],
	 @[@"民", @"ミン", @"nation"],
	 @[@"連", @"つらなる", @"lead"],
	 @[@"対", @"あいて", @"even"],
	 @[@"部", @"ブ", @"dept"],
	 @[@"合", @"あう", @"0.1"],
	 @[@"市", @"シ", @"city"],
	 @[@"内", @"ナイ", @"home"],
	 @[@"相", @"あい", @"phase"],
	 @[@"定", @"さだめる", @"fix"],
	 @[@"回", @"まわる", @"game"],
	 @[@"選", @"えらぶ", @"elect"],
	 @[@"米", @"こめ", @"USA"],
	 @[@"実", @"み", @"truth"],
	 @[@"関", @"せき", @"barrier"],
	 @[@"決", @"きめる", @"fix"],
	 @[@"全", @"まったく", @"all"],
	 @[@"表", @"おもて", @"table"],
	 @[@"戦", @"いくさ", @"war"],
	 @[@"経", @"へる", @"warp"],
	 @[@"最", @"もっとも", @"most"],
	 @[@"現", @"あらわれる", @"actual"],
	 @[@"調", @"しらべる", @"tone"],
	 @[@"化", @"ばける", @"delude"],
	 @[@"当", @"あたる", @"hit"],
	 @[@"約", @"ヤク", @"shrink"],
	 @[@"首", @"シュ", @"neck"],
	 @[@"法", @"ホウ", @"law"],
	 @[@"性", @"さが", @"sex"],
	 @[@"要", @"ヨウ", @"need"],
	 @[@"制", @"セイ", @"law"],
	 @[@"治", @"おさめる", @"govt"],
	 @[@"務", @"ム", @"task"],
	 @[@"成", @"なる", @"get"],
	 @[@"期", @"キ", @"time"],
	 @[@"取", @"とる", @"take"],
	 @[@"都", @"ト", @"capital"],
	 @[@"和", @"やわらぐ", @"peace"],
	 @[@"機", @"はた", @"machine"],
	 @[@"平", @"たいら", @"flat"],
	 @[@"加", @"くわえる", @"add"],
	 @[@"受", @"うける", @"get"],
	 @[@"続", @"つづく", @"series"],
	 @[@"進", @"すすむ", @"proceed"],
	 @[@"数", @"かず", @"law"],
	 @[@"記", @"キ", @"scribe"],
	 @[@"初", @"はじめ", @"beginning"],
	 @[@"指", @"ゆび", @"finger"],
	 @[@"権", @"おもり", @"power"],
	 @[@"支", @"しんよう", @"branch"],
	 @[@"産", @"うむ", @"bear"],
	 @[@"点", @"つける", @"mark"],
	 @[@"報", @"むくいる", @"news"],
	 @[@"済", @"すむ", @"finish"],
	 @[@"活", @"いきる", @"living"],
	 @[@"原", @"ゲン", @"field"],
	 @[@"共", @"とも", @"all"],
	 @[@"得", @"える", @"get"],
	 @[@"解", @"とく", @"key"],
	 @[@"交", @"まじわる", @"mixing"],
	 @[@"資", @"", @"data"],
	 @[@"予", @"あらかじめ", @"I"],
	 @[@"向", @"むく", @"defy"],
	 @[@"際", @"きわ", @"side"],
	 @[@"勝", @"かつ", @"win"],
	 @[@"面", @"おも", @"face"],
	 @[@"告", @"コク", @"tell"],
	 @[@"反", @"そる", @"anti-"],
	 @[@"判", @"わかる", @"seal"],
	 @[@"認", @"みとめる", @"witness"],
	 @[@"参", @"まいる", @"die"],
	 @[@"利", @"リ", @"profit"],
	 @[@"組", @"くむ", @"braid"],
	 @[@"信", @"シ", @"truth"],
	 @[@"在", @"ザイ", @"exist"],
	 @[@"件", @"くだん", @"case"],
	 @[@"側", @"かわ", @"lean"],
	 @[@"任", @"まかせる", @"duty"],
	 @[@"引", @"ひく", @"tug"],
	 @[@"求", @"もとめる", @"want"],
	 @[@"所", @"ところ", @"place"],
	 @[@"次", @"つぐ", @"next"],
	 @[@"昨", @"サク", @"previous"],
	 @[@"論", @"ロン", @"argument"],
	 @[@"官", @"カン", @"bureaucrat"],
	 @[@"増", @"ます", @"add"],
	 @[@"係", @"かかる", @"duty"],
	 @[@"感", @"カン", @"feeling"],
	 @[@"情", @"なさけ", @"facts"],
	 @[@"投", @"なげる", @"join"],
	 @[@"示", @"しめす", @"show"],
	 @[@"変", @"かわる", @"change"],
	 @[@"打", @"うつ", @"hit"],
	 @[@"直", @"ただちに", @"fix"],
	 @[@"両", @"てる", @"two"],
	 @[@"式", @"シ", @"rite"],
	 @[@"確", @"たしか", @"firm"],
	 @[@"果", @"はたす", @"end"],
	 @[@"容", @"ヨウ", @"form"],
	 @[@"必", @"かならず", @"certain"],
	 @[@"演", @"エン", @"act"],
	 @[@"歳", @"とし", @"age"],
	 @[@"争", @"あらそう", @"argue"],
	 @[@"談", @"ダン", @"talk"],
	 @[@"能", @"ノウ", @"skill"],
	 @[@"位", @"くらい", @"some"],
	 @[@"置", @"おく", @"put"],
	 @[@"流", @"ながれる", @"flow"],
	 @[@"格", @"カク", @"rank"],
	 @[@"疑", @"うたがう", @"doubt"],
	 @[@"過", @"すぎる", @"error"],
	 @[@"局", @"つぼね", @"board"],
	 @[@"放", @"はなす", @"fire"],
	 @[@"常", @"つね", @"usual"],
	 @[@"状", @"ジョウ", @"form"],
	 @[@"球", @"キュウ", @"ball"],
	 @[@"職", @"ショク", @"work"],
	 @[@"与", @"あたえる", @"give"],
	 @[@"供", @"そなえる", @"offer"],
	 @[@"役", @"ヤク", @"war"],
	 @[@"構", @"かまえる", @"build"],
	 @[@"割", @"わる", @"cut"],
	 @[@"費", @"ついやす", @"cost"],
	 @[@"付", @"つける", @"attach"],
	 @[@"由", @"よし", @"a reason"],
	 @[@"説", @"セツ", @"rumor"],
	 @[@"難", @"かたい", @"defect"],
	 @[@"優", @"やさしい", @"excel"],
	 @[@"夫", @"おっと", @"man"],
	 @[@"収", @"おさめる", @"pay"],
	 @[@"断", @"たつ", @"warn"],
	 @[@"石", @"セキ", @"stone"],
	 @[@"違", @"ちがう", @"differ"],
	 @[@"消", @"きえる", @"cancel"],
	 @[@"神", @"かみ", @"mind"],
	 @[@"番", @"バン", @"turn"],
	 @[@"規", @"", @"measure"],
	 @[@"術", @"すべ", @"art"],
	 @[@"備", @"そなえる", @"equip"],
	 @[@"宅", @"タ", @"home"],
	 @[@"害", @"ガイ", @"harm"],
	 @[@"配", @"くばる", @"exile"],
	 @[@"警", @"いましめる", @"admonish"],
	 @[@"育", @"そだつ", @"rear"],
	 @[@"席", @"むしろ", @"mat"],
	 @[@"訪", @"おとずれる", @"visit"],
	 @[@"乗", @"のる", @"join"],
	 @[@"残", @"のこる", @"balance"],
	 @[@"想", @"おもう", @"idea"],
	 @[@"声", @"こえ", @"voice"],
	 @[@"念", @"ネン", @"idea"],
	 @[@"助", @"たすける", @"help"],
	 @[@"労", @"ろうする", @"toil"],
	 @[@"例", @"たとえる", @"usage"],
	 @[@"然", @"しか", @"so"],
	 @[@"限", @"かぎる", @"limit"],
	 @[@"追", @"ツイ", @"chase"],
	 @[@"商", @"ショウ", @"selling"],
	 @[@"葉", @"ヨウ", @"lobe"],
	 @[@"伝", @"つたわる", @"follow"],
	 @[@"働", @"はたらく", @"work"],
	 @[@"形", @"かた", @"form"],
	 @[@"景", @"ケ", @"view"],
	 @[@"落", @"おちる", @"drop"],
	 @[@"好", @"このむ", @"fond"],
	 @[@"退", @"しりぞく", @"repel"],
	 @[@"頭", @"あたま", @"head"],
	 @[@"負", @"まける", @"-"],
	 @[@"渡", @"わたる", @"ford"],
	 @[@"失", @"うしなう", @"loss"],
	 @[@"差", @"さす", @"margin"],
	 @[@"末", @"すえ", @"tip"],
	 @[@"守", @"まもる", @"obey"],
	 @[@"若", @"わかい", @"if"],
	 @[@"種", @"たね", @"kind"],
	 @[@"美", @"ビ", @"beauty"],
	 @[@"命", @"いのち", @"life"],
	 @[@"福", @"フ", @"luck"],
	 @[@"望", @"のぞむ", @"hope"],
	 @[@"非", @"あらず", @"un-"],
	 @[@"観", @"みる", @"look"],
	 @[@"察", @"サツ", @"judge"],
	 @[@"段", @"ダン", @"steps"],
	 @[@"横", @"よこ", @"side"],
	 @[@"深", @"ふかい", @"deep"],
	 @[@"申", @"もうす", @"3-5PM"],
	 @[@"様", @"さま", @"way"],
	 @[@"財", @"ザイ", @"money"],
	 @[@"港", @"みなと", @"harbor"],
	 @[@"識", @"シ", @"know"],
	 @[@"呼", @"コ", @"call"],
	 @[@"達", @"タツ", @"reach"],
	 @[@"良", @"よい", @"good"],
	 @[@"候", @"そうろう", @"season"],
	 @[@"程", @"ほど", @"law"],
	 @[@"満", @"みちる", @"full"],
	 @[@"敗", @"やぶれる", @"defeat"],
	 @[@"値", @"ね", @"cost"],
	 @[@"突", @"つく", @"stab"],
	 @[@"光", @"ひかる", @"ray"],
	 @[@"路", @"じ", @"road"],
	 @[@"科", @"", @"course"],
	 @[@"積", @"つむ", @"stack"],
	 @[@"他", @"ほか", @"other"],
	 @[@"処", @"ところ", @"act"],
	 @[@"太", @"ふとい", @"thick"],
	 @[@"客", @"キャク", @"guest"],
	 @[@"否", @"いな", @"no"],
	 @[@"師", @"", @"war"],
	 @[@"登", @"のぼる", @"ascend"],
	 @[@"易", @"やさしい", @"easy"],
	 @[@"速", @"はやい", @"fast"],
	 @[@"存", @"ソン", @"feel"],
	 @[@"飛", @"とぶ", @"fly"],
	 @[@"殺", @"ころす", @"kill"],
	 @[@"号", @"さけぶ", @"item"],
	 @[@"単", @"ひとえ", @"one"],
	 @[@"座", @"すわる", @"sit"],
	 @[@"破", @"やぶる", @"rip"],
	 @[@"除", @"のぞく", @"3)"],
	 @[@"完", @"カン", @"end"],
	 @[@"降", @"おりる", @"fall"],
	 @[@"責", @"せめる", @"blame"],
	 @[@"捕", @"とらえる", @"catch"],
	 @[@"危", @"あぶない", @"fear"],
	 @[@"給", @"たまう", @"wage"],
	 @[@"苦", @"くるしい", @"trial"],
	 @[@"迎", @"ゲイ", @"meet"],
	 @[@"園", @"エン", @"yard"],
	 @[@"具", @"そなえる", @"tool"],
	 @[@"辞", @"やめる", @"word"],
	 @[@"因", @"よる", @"cause"],
	 @[@"馬", @"うま", @"horse"],
	 @[@"愛", @"アイ", @"love"],
	 @[@"富", @"とむ", @"enrich"],
	 @[@"彼", @"かれ", @"he"],
	 @[@"未", @"いまだ", @"un-"],
	 @[@"舞", @"まう", @"flit"],
	 @[@"亡", @"ない", @"dying"],
	 @[@"冷", @"つめたい", @"cool"],
	 @[@"適", @"かなう", @"rare"],
	 @[@"婦", @"", @"wife"],
	 @[@"寄", @"よる", @"send"],
	 @[@"込", @"こむ", @"mixture"],
	 @[@"顔", @"かお", @"face"],
	 @[@"類", @"たぐい", @"kind"],
	 @[@"余", @"あまる", @"other"],
	 @[@"王", @"オウ", @"rule"],
	 @[@"返", @"かえす", @"fade"],
	 @[@"妻", @"サイ", @"wife"],
	 @[@"背", @"せ", @"back"],
	 @[@"熱", @"ネツ", @"heat"],
	 @[@"宿", @"やど", @"inn"],
	 @[@"薬", @"ヤク", @"enamel"]
	 ];
}

-(NSArray*)koreanLesson
{
    NSLog(@"! LESSON | Loading Korean");

    return @[
        @[@"것", @"a thing or an object"],
        @[@"하다", @"to do"],
        @[@"있다", @"to be"],
        @[@"수", @"way, method"],
        @[@"나", @"me"],
        @[@"없다", @"do not exist, absent"],
        @[@"않다", @"to not be, to not do"],
        @[@"사람", @"person"],
        @[@"우리", @"we, our"],
        @[@"그", @"he"],
        @[@"아니다", @"to not be"],
        @[@"보다", @"to try"],
        @[@"거", @"that thing"],
        @[@"보다", @"to see"],
        @[@"같다", @"to be similar"],
        @[@"주다", @"to give, to do for a person"],
        @[@"가다", @"to go"],
        @[@"년", @"year"],
        @[@"한", @"one, a single"],
        @[@"말", @"words, speaking"],
        @[@"일", @"work"],
        @[@"이", @"a person, a man/woman"],
        @[@"말하다", @"speak"],
        @[@"그러나", @"however or but still"],
        @[@"오다", @"to come"],
        @[@"알다", @"to know"],
        @[@"씨", @"~ mr."],
        @[@"그렇다", @"that is right or yes."],
        @[@"크다", @"to be big, large"],
        @[@"일", @"one day"],
        @[@"많다", @"many, much"],
        @[@"안", @"~ not ~ + verb"],
        @[@"좋다", @"to be good"],
        @[@"더", @"more"],
        @[@"받다", @"receive"],
        @[@"그것", @"that thing"],
        @[@"집", @"house"],
        @[@"나오다", @"come out"],
        @[@"그리고", @"and or and then"],
        @[@"문제", @"question, problem"],
        @[@"살다", @"to live"],
        @[@"저", @"that"],
        @[@"못하다", @"be impossible"],
        @[@"생각하다", @"to think"],
        @[@"모르다", @"to not know"],
        @[@"속", @"the inside"],
        @[@"만들다", @"to make"],
        @[@"앞", @"in front of, before"],
        @[@"어떤", @"what kind of, what sort of"],
        @[@"잘", @"well"],
        @[@"그녀", @"she"],
        @[@"먹다", @"eat, chow down on"],
        @[@"원", @"a unit of south korean money, krw"],
        @[@"생각", @"thought"],
        @[@"어떻다", @"how, what.. do you think of"],
        @[@"명", @"person counter"],
        @[@"다시", @"again"],
        @[@"다른", @"different"],
        @[@"이런", @"such, like this"],
        @[@"여자", @"woman, female"],
        @[@"개", @"unit or piece"],
        @[@"다", @"all, everything"],
        @[@"좀", @"a little"],
        @[@"싶다", @"want, hope"],
        @[@"가지다", @"to have or take or hold"],
        @[@"함께", @"together, with"],
        @[@"아이", @"child"],
        @[@"많이", @"a lot"],
        @[@"시간", @"time"],
        @[@"너", @"you"],
        @[@"나다", @"to be born"],
        @[@"이렇다", @"like this"],
        @[@"어머니", @"mom"],
        @[@"눈", @"eyes"],
        @[@"뭐", @"huh? (2) something"],
        @[@"다음", @"next"],
        @[@"누구", @"who"],
        @[@"곳", @"place"],
        @[@"여러", @"many, various"],
        @[@"안", @"inside"],
        @[@"하나", @"one"],
        @[@"버리다", @"(following a verb) the verb\'s action is over, perhaps in a sad way"],
        @[@"위", @"the upper part, above"],
        @[@"운동", @"motion, movement"],
        @[@"퍼센트", @"percent"],
        @[@"학교", @"school"],
        @[@"가장", @"most"],
        @[@"시작하다", @"to start, begin"],
        @[@"바로", @"right, correctly"],
        @[@"어느", @"some, a certain"],
        @[@"그래서", @"and so accordingly"],
        @[@"무엇", @"that thing, whatever"],
        @[@"모든", @"every one"],
        @[@"번", @"number, how many times"],
        @[@"그거", @"that thing"],
        @[@"돈", @"money"],
        @[@"그런데", @"but or however"],
        @[@"날", @"day"],
        @[@"여기", @"a hobby"],
        @[@"모두", @"everybody"],
        @[@"친구", @"a friend"],
        @[@"마음", @"heart"],
        @[@"후", @"after"],
        @[@"놓다", @"put, place"],
        @[@"아버지", @"father"],
        @[@"남자", @"boy"],
        @[@"어디", @"where?"],
        @[@"몸", @"body, physique"],
        @[@"얼굴", @"face"],
        @[@"왜", @"why?"],
        @[@"다르다", @"be different"],
        @[@"물", @"water"],
        @[@"만나다", @"meet"],
        @[@"내다", @"produce something"],
        @[@"쓰다", @"to write"],
        @[@"이것", @"this thing"],
        @[@"이번", @"this time"],
        @[@"길", @"road"],
        @[@"생활", @"lifestyle, livelihood"],
        @[@"쓰다", @"take (medicine)"],
        @[@"사이", @"space between 2 points; the relationship between 2 people"],
        @[@"내다", @"to see through, to make it through sth"],
        @[@"앉다", @"to sit down"],
        @[@"처음", @"first"],
        @[@"손", @"the hand"],
        @[@"몇", @"a few"],
        @[@"그때", @"then or at that time"],
        @[@"찾다", @"seek, look for"],
        @[@"시", @"time"],
        @[@"지금", @"now"],
        @[@"나가다", @"to go out"],
        @[@"이야기", @"conversation, talk"],
        @[@"사다", @"to buy, purchase"],
        @[@"아직", @"still"],
        @[@"잡다", @"seize, catch"],
        @[@"같이", @"together"],
        @[@"선생님", @"teacher"],
        @[@"서다", @"to stand"],
        @[@"못", @"cannot"],
        @[@"역사", @"history"],
        @[@"읽다", @"to read"],
        @[@"물론", @"of course"],
        @[@"책", @"a book"],
        @[@"일어나다", @"to rise, get up"],
        @[@"시장", @"market, fair"],
        @[@"넣다", @"put in, set in"],
        @[@"중요하다", @"to be important, weighty"],
        @[@"무슨", @"what, what kind of"],
        @[@"어렵다", @"to be hard, difficult"],
        @[@"힘", @"power"],
        @[@"너무", @"too much"],
        @[@"나라", @"a country"],
        @[@"부르다", @"to call"],
        @[@"자리", @"seat, spot"],
        @[@"죽다", @"die, pass away"],
        @[@"쪽", @"way, direction"],
        @[@"얘기", @"story"],
        @[@"학생", @"student"],
        @[@"엄마", @"mamma"],
        @[@"이름", @"name"],
        @[@"하나", @"one"],
        @[@"내리다", @"descend"],
        @[@"쉽다", @"to be easy"],
        @[@"필요하다", @"to need"],
        @[@"생기다", @"arise, occur, happen"],
        @[@"사용하다", @"to use"],
        @[@"남편", @"husband"],
        @[@"밖", @"the outside"],
        @[@"작다", @"small"],
        @[@"타다", @"ride (bus)"],
        @[@"대학", @"university"],
        @[@"가운데", @"in the middle"],
        @[@"보내다", @"send"],
        @[@"아주", @"extremely"],
        @[@"밤", @"night"],
        @[@"높다", @"high"],
        @[@"컴퓨터", @"computer"],
        @[@"먼저", @"first"],
        @[@"다니다", @"go to and from a aplace"],
        @[@"얼마나", @"how many, how much"],
        @[@"열다", @"open"],
        @[@"머리", @"head"],
        @[@"묻다", @"to ask"],
        @[@"아들", @"son, baby"],
        @[@"아", @"oh dear"],
        @[@"분", @"minutes"],
        @[@"곧", @"soon"],
        @[@"오늘", @"today"],
        @[@"서로", @"mutually, one another"],
        @[@"이거", @"this thing"],
        @[@"방", @"a room"],
        @[@"아침", @"morning"],
        @[@"웃다", @"to laugh, smile"],
        @[@"그래", @"so or yes or that’s right"],
        @[@"아름답다", @"to be beautiful"],
        @[@"끝", @"the end"],
        @[@"입", @"mouth"],
        @[@"뭐", @"huh? (2) something"],
        @[@"영화", @"a movie"],
        @[@"필요", @"need, requirement, necessity"],
        @[@"하늘", @"the sky"],
        @[@"정말", @"really"],
        @[@"밥", @"rice, a meal"],
        @[@"입다", @"to wear"],
        @[@"네", @"yes"],
        @[@"그림", @"a picture"],
        @[@"마시다", @"to drink"],
        @[@"치다", @"to attack, assault"],
        @[@"혼자", @"alone"],
        @[@"나가다", @"to advance, proceed, go forward"],
        @[@"이제", @"now"],
        @[@"교수", @"teaching or instruction"],
        @[@"술", @"alcohol"],
        @[@"사랑", @"love"],
        @[@"전화", @"telephone"],
        @[@"끝나다", @"to draw to a close or to end"],
        @[@"아빠", @"dad"],
        @[@"한번", @"once"],
        @[@"커피", @"coffee"],
        @[@"가슴", @"chest"],
        @[@"길다", @"to be long"],
        @[@"맛", @"flavor"],
        @[@"매우", @"very"],
        @[@"오르다", @"go up, climb, ascend"],
        @[@"음식", @"food"],
        @[@"꼭", @"for sure"],
        @[@"요즘", @"recently, nowadays"],
        @[@"계획", @"a plan or a project"],
        @[@"얼마", @"how many, how much"],
        @[@"계속", @"continuously"],
        @[@"아내", @"wife"],
        @[@"가족", @"family"],
        @[@"세", @"three"],
        @[@"차", @"a vehicle, train/auto car"],
        @[@"놀다", @"play, amuse oneself"],
        @[@"도시", @"city"],
        @[@"나이", @"age"],
        @[@"바꾸다", @"change, exchange"],
        @[@"좋아하다", @"to like, be fond of"],
        @[@"그리다", @"picture or draw a picture"],
        @[@"배우다", @"to learn"],
        @[@"옆", @"next to"],
        @[@"어", @"oh, well, why"],
        @[@"아래", @"the bottom, the lower part"],
        @[@"그럼", @"certainly or of course."],
        @[@"저", @"uh, well, ..."],
        @[@"배", @"a boat (boating)"],
        @[@"산", @"a mountain"],
        @[@"새", @"new"],
        @[@"하지만", @"but, nevertheless"],
        @[@"문", @"door"],
        @[@"꽃", @"flower"],
        @[@"그동안", @"during that time"],
        @[@"갑자기", @"suddenly"],
        @[@"바람", @"wind"],
        @[@"잘하다", @"to do well"],
        @[@"노래", @"song"],
        @[@"바다", @"sea"],
        @[@"힘들다", @"to be hard, difficult"],
        @[@"공부", @"study"],
        @[@"언니", @"older sister"],
        @[@"분", @"one part"],
        @[@"불", @"fire"],
        @[@"학년", @"a school year"],
        @[@"신문", @"a newspaper"],
        @[@"가지다", @"entertain or hold or have"],
        @[@"이해하다", @"to understand"],
        @[@"선생", @"teacher"],
        @[@"기분", @"mood"],
        @[@"옷", @"clothes"],
        @[@"전", @"before"],
        @[@"꿈", @"a dream"],
        @[@"할머니", @"grandmother"],
        @[@"회의", @"a meeting, a conference"],
        @[@"이야기하다", @"to talk"],
        @[@"나무", @"tree"],
        @[@"자다", @"to sleep"],
        @[@"걷다", @"to walk"],
        @[@"이때", @"at this time, moment"],
        @[@"시간", @"a length of time (한시간 동안)"],
        @[@"물건", @"a thing"],
        @[@"발", @"foot"],
        @[@"빨리", @"quickly"],
        @[@"시작되다", @"to begin, start"],
        @[@"말다", @"cease"],
        @[@"설명하다", @"to explain"],
        @[@"살", @"years old"],
        @[@"음악", @"music"],
        @[@"아프다", @"to hurt"],
        @[@"적다", @"to be small, few in number"],
        @[@"비", @"rain"],
        @[@"고향", @"hometown"],
        @[@"놀라다", @"be surprised"],
        @[@"울다", @"to cry, weep"],
        @[@"은행", @"a bank"],
        @[@"지내다", @"to pass, spend time"],
        @[@"결혼", @"marriage"],
        @[@"예", @"yes, certainly, right"],
        @[@"오후", @"the afternoon"],
        @[@"빠르다", @"be fast, quick"],
        @[@"아기", @"baby, infant"],
        @[@"아저씨", @"sir, calling an unknown male"],
        @[@"옛날", @"ancient times, antiquity"],
        @[@"달", @"the moon"],
        @[@"참", @"really, truly"],
        @[@"이곳", @"this place, here"],
        @[@"마지막", @"last, final"],
        @[@"병원", @"hospital"],
        @[@"경찰", @"the police"],
        @[@"저녁", @"evening"],
        @[@"그러면", @"if so or if that is the case"],
        @[@"넓다", @"broad"],
        @[@"시험", @"a test"],
        @[@"잠", @"sleep"],
        @[@"건강", @"health"],
        @[@"가깝다", @"close"],
        @[@"건물", @"building"],
        @[@"외국", @"a foreign country"],
        @[@"밑", @"the bottom"],
        @[@"어른", @"a man, an adult"],
        @[@"팔다", @"to sell"],
        @[@"열심히", @"enthusiastically, with zeal"],
        @[@"일하다", @"to work, labor"],
        @[@"팀", @"team"],
        @[@"부모", @"parents"],
        @[@"올라가다", @"to go up, ascend"],
        @[@"그날", @"that day or that same day"],
        @[@"자주", @"always, constantly"],
        @[@"담배", @"tobacco"],
        @[@"할아버지", @"grandfather"],
        @[@"태어나다", @"to be born, see the light of day"],
        @[@"벌써", @"already"],
        @[@"환자", @"a patient"],
        @[@"재미있다", @"interesting, fun"],
        @[@"가르치다", @"to teach"],
        @[@"대화", @"conversation"],
        @[@"올해", @"this year"],
        @[@"형", @"an elder brother"],
        @[@"모두", @"everything"],
        @[@"걸다", @"hang up or suspend"],
        @[@"멀다", @"to be far"],
        @[@"버스", @"bus"],
        @[@"잠시", @"for a little while"],
        @[@"사진", @"picture"],
        @[@"제일", @"the first"],
        @[@"아마", @"probably"],
        @[@"얘기하다", @"to tell a story"],
        @[@"조금", @"a little"],
        @[@"다리", @"leg"],
        @[@"아무", @"anybody, everybody"],
        @[@"항상", @"always"],
        @[@"해", @"a year"],
        @[@"잃다", @"to lose, to miss, to be deprived"],
        @[@"비슷하다", @"to resemble"],
        @[@"사랑하다", @"to love"],
        @[@"여름", @"summer, summertime"],
        @[@"싫다", @"to not like, to hate"],
        @[@"그러니까", @"and so it is that"],
        @[@"값", @"price"],
        @[@"언제나", @"everytime, always"],
        @[@"자동차", @"car"],
        @[@"개월", @"each and every month"],
        @[@"어린이", @"a youngster, a child"],
        @[@"공부하다", @"to study"],
        @[@"닦다", @"wipe clean, polish"],
        @[@"말씀", @"speech"],
        @[@"괜찮다", @"to be okay"],
        @[@"눈물", @"a tear"],
        @[@"아니", @"not"],
        @[@"주인", @"the head of a family, the owner"],
        @[@"반", @"half"],
        @[@"귀", @"ear"],
        @[@"미터", @"meter"],
        @[@"어떠하다", @"to be how"],
        @[@"배", @"abdomen"],
        @[@"아파트", @"apartment"],
        @[@"가끔", @"sometimes"],
        @[@"술", @"spoonful"],
        @[@"짧다", @"short, brief"],
        @[@"고맙다", @"to thank"],
        @[@"그곳", @"that place"],
        @[@"보다", @"more than, greater than ...."],
        @[@"바쁘다", @"busy"],
        @[@"나쁘다", @"to be bad"],
        @[@"게임", @"game"],
        @[@"잔", @"a cup, wine glass"],
        @[@"있다", @"to be"],
        @[@"언제", @"when, at what time"],
        @[@"내려오다", @"come down"],
        @[@"손님", @"customer"],
        @[@"뉴스", @"news"],
        @[@"수업", @"school, teaching"],
        @[@"겨울", @"winter"],
        @[@"층", @"floor, grade, class"],
        @[@"장", @"one piece of sth flat"],
        @[@"식사", @"a meal"],
        @[@"안다", @"to hold, embrace"],
        @[@"잊다", @"to forget"],
        @[@"반", @"group, company, party"],
        @[@"텔레비전", @"television"],
        @[@"씻다", @"to wash, cleanse"],
        @[@"늦다", @"to be late (time)"],
        @[@"편지", @"letter"],
        @[@"센티미터", @"centimeter"],
        @[@"팔", @"an arm"],
        @[@"설명", @"explanation"],
        @[@"세", @"age in years"],
        @[@"티브이", @"tv"],
        @[@"봄", @"spring"],
        @[@"낮다", @"be low"],
        @[@"어깨", @"shoulder"],
        @[@"부부", @"man and wife"],
        @[@"오래", @"long, for a long time"],
        @[@"여행", @"trip"],
        @[@"공", @"ball"],
        @[@"오월", @"may"],
        @[@"쉬다", @"to relax, take a break"],
        @[@"과", @"a lesson or a section or a department"],
        @[@"오빠", @"older brother"],
        @[@"즐겁다", @"be pleasant, agreeable"],
        @[@"사월", @"april"],
        @[@"싸우다", @"to fight"],
        @[@"예쁘다", @"pretty, lovely"],
        @[@"나중", @"the last, the latter part"],
        @[@"맛있다", @"delicious"],
        @[@"며칠", @"how many days"],
        @[@"작년", @"last year"],
        @[@"내려가다", @"to go down"],
        @[@"쓰레기", @"garbage"],
        @[@"고기", @"meat"],
        @[@"가져오다", @"to bring or get"],
        @[@"남녀", @"man and woman"],
        @[@"준비", @"preparation"],
        @[@"구월", @"september"],
        @[@"맑다", @"clean, pure"],
        @[@"유월", @"june"],
        @[@"허리", @"the waist, the small of the back"],
        @[@"새", @"a bird"],
        @[@"영어", @"the english language"],
        @[@"대답하다", @"to answer, reply"],
        @[@"벗다", @"take off, remove"],
        @[@"준비하다", @"to prepare"],
        @[@"달", @"the moon"],
        @[@"사장", @"company boss"],
        @[@"삼월", @"march"],
        @[@"그렇지만", @"but or however"],
        @[@"키", @"stature, height"],
        @[@"걱정", @"worry"],
        @[@"결혼하다", @"get married"],
        @[@"누나", @"older sister"],
        @[@"질문", @"a question, a query"],
        @[@"근처", @"nearby or the vicinity"],
        @[@"부모님", @"parents"],
        @[@"계시다", @"(someone esteemed) to stay or be located"],
        @[@"그", @"that"],
        @[@"마리", @"number of animals"],
        @[@"비행기", @"an airplane"],
        @[@"낮", @"daytime"],
        @[@"일찍", @"early"],
        @[@"찍다", @"stamp with a dojang"],
        @[@"가볍다", @"light"],
        @[@"오전", @"morning"],
        @[@"가게", @"store"],
        @[@"약속", @"a promise"],
        @[@"인사", @"greetings"],
        @[@"소금", @"salt"],
        @[@"자전거", @"bicycle"],
        @[@"그래", @"yes or that’s right"],
        @[@"목", @"the neck"],
        @[@"피우다", @"to make, build, kindle"],
        @[@"교통", @"traffic or transportation"],
        @[@"거리", @"a road or street"],
        @[@"불다", @"blow"],
        @[@"한글", @"korean writing system"],
        @[@"가을", @"autumn or fall"],
        @[@"내일", @"tomorrow"],
        @[@"매일", @"every day"],
        @[@"손가락", @"a finger"],
        @[@"급", @"class or grade or rank"],
        @[@"날씨", @"weather"],
        @[@"의사", @"a doctor, a physician"],
        @[@"건강하다", @"to be healthy"],
        @[@"여러분", @"you (plural, to address a group at speech time)"],
        @[@"왜냐하면", @"because"],
        @[@"네", @"you"],
        @[@"도착하다", @"to arrive"],
        @[@"병", @"sickness"],
        @[@"축구", @"football"],
        @[@"밝다", @"to be promising"],
        @[@"장소", @"place"],
        @[@"적다", @"write down"],
        @[@"코", @"the nose"],
        @[@"고등학교", @"a senior high school"],
        @[@"교실", @"classroom"],
        @[@"별", @"a star"],
        @[@"복잡하다", @"be complicated"],
        @[@"색", @"color"],
        @[@"말씀하다", @"speak"],
        @[@"보통", @"the normal"],
        @[@"식당", @"restaurant"],
        @[@"소개하다", @"to introduce, present"],
        @[@"칠월", @"month of july"],
        @[@"십이월", @"december"],
        @[@"컵", @"cup"],
        @[@"종이", @"paper"],
        @[@"계시다", @"(honorofic) to stay or reside"],
        @[@"재미", @"amusement, enjoyment"],
        @[@"끝내다", @"to end"],
        @[@"대답", @"an answer"],
        @[@"시작", @"the beginning"],
        @[@"일주일", @"one whole day"],
        @[@"춤", @"dance"],
        @[@"깨끗하다", @"to be clean or pure"],
        @[@"물어보다", @"ask"],
        @[@"미안하다", @"to be sorry"],
        @[@"스트레스", @"stress"],
        @[@"인사", @"people, men of society"],
        @[@"과일", @"a fruit"],
        @[@"눈", @"snow"],
        @[@"시월", @"october"],
        @[@"박물관", @"museum"],
        @[@"어서", @"quickly 2) kindly"],
        @[@"팔월", @"august"],
        @[@"가방", @"bag"],
        @[@"호", @"a pen name, a title; a number, an issue"],
        @[@"그릇", @"a vessel or receptacle"],
        @[@"개", @"a dog"],
        @[@"방학", @"school holidays"],
        @[@"남쪽", @"south side"],
        @[@"색깔", @"color"],
        @[@"요리", @"cooking"],
        @[@"유명하다", @"to be famous"],
        @[@"외국인", @"a foreigner, a foreign national"],
        @[@"부인", @"a woman"],
        @[@"숙제", @"homework"],
        @[@"우산", @"an umbrealla"],
        @[@"지난달", @"last month"],
        @[@"책상", @"on the desk"],
        @[@"춥다", @"to be cold"],
        @[@"무겁다", @"heavy ; a stuffy atmosphere"],
        @[@"바람", @"as a result, by the influence of"],
        @[@"침대", @"a bed"],
        @[@"권", @"a volume or a book"],
        @[@"시계", @"clock, timekeeper, timepiece"],
        @[@"잎", @"a leaf"],
        @[@"천천히", @"slowly"],
        @[@"스포츠", @"sports"],
        @[@"저기", @"that place, there"],
        @[@"교회", @"preach or moral instruction"],
        @[@"화", @"anger (get angry)"],
        @[@"일월", @"january"],
        @[@"첫째", @"the first"],
        @[@"도서관", @"library"],
        @[@"선물", @"a present, gift"],
        @[@"아주머니", @"an aunt, a respectable word for a married, older woman"],
        @[@"위험", @"danger"],
        @[@"지하", @"underground"],
        @[@"지하철", @"subway"],
        @[@"사무실", @"office"],
        @[@"이월", @"february"],
        @[@"일요일", @"sunday"],
        @[@"쓰다", @"to wear (a hat)"],
        @[@"강", @"river"],
        @[@"비싸다", @"to be expensive"],
        @[@"왼쪽", @"the left side"],
        @[@"택시", @"taxi"],
        @[@"시원하다", @"be cool, refreshing"],
        @[@"잡지", @"a magazine"],
        @[@"댁", @"you and your family"],
        @[@"반갑다", @"be happy"],
        @[@"다녀오다", @"drop in for a short visit"],
        @[@"비디오", @"video"],
        @[@"이쪽", @"this side, our way"],
        @[@"연습", @"practice, exercise"],
        @[@"오른쪽", @"the right side"],
        @[@"지도", @"map, atlas"],
        @[@"화장실", @"bathroom"],
        @[@"주말", @"weekend"],
        @[@"내년", @"next year"],
        @[@"대학생", @"university student"],
        @[@"닫다", @"to close"],
        @[@"생일", @"a birthday"],
        @[@"걸어가다", @"to go on foot or walk"],
        @[@"백화점", @"department store"],
        @[@"병", @"a bottle"],
        @[@"안녕하다", @"to say hello"],
        @[@"출발하다", @"to depart, leave"],
        @[@"고양이", @"kitten"],
        @[@"중학교", @"middle school"],
        @[@"흰색", @"gray, ash color"],
        @[@"가수", @"singer"],
        @[@"약", @"medicine"],
        @[@"저쪽", @"over there, in that direction"],
        @[@"창문", @"a window"],
        @[@"우유", @"milk"],
        @[@"표", @"a marker, indication"],
        @[@"십일월", @"november"],
        @[@"거울", @"1) mirror 2) a pattern or model or exemplar"],
        @[@"빵", @"bread"],
        @[@"어제", @"yesterday"],
        @[@"위험하다", @"to be dangerous"],
        @[@"졸업하다", @"to graduate"],
        @[@"부엌", @"kitchen"],
        @[@"북쪽", @"the north direction"],
        @[@"쇠고기", @"beef"],
        @[@"카드", @"card"],
        @[@"단어", @"word"],
        @[@"도와주다", @"to help"],
        @[@"신발", @"shoes, footwear"],
        @[@"김치", @"spicy cabbage"],
        @[@"날다", @"to fly"],
        @[@"설탕", @"sugar"],
        @[@"싸다", @"be inexpensive"],
        @[@"점심", @"lunch"],
        @[@"칼", @"a knife"],
        @[@"슬프다", @"to be sad, sorrowful"],
        @[@"의자", @"a chair"],
        @[@"카메라", @"camera"],
        @[@"토요일", @"saturday"],
        @[@"경찰관", @"a policeman"],
        @[@"극장", @"theater or playhouse"],
        @[@"오랜만", @"after a long time"],
        @[@"백", @"hundreds of"],
        @[@"아줌마", @"old or married lady"],
        @[@"추다", @"to dance"],
        @[@"켜다", @"to light, turn on, kindle"],
        @[@"공항", @"airport"],
        @[@"군인", @"sb in the military"],
        @[@"아니요", @"no, that’s not the case"],
        @[@"치마", @"a skirt"],
        @[@"호텔", @"hotel"],
        @[@"깎다", @"cut or trim"],
        @[@"다리", @"bridge"],
        @[@"청소", @"cleaning"],
        @[@"걱정하다", @"to worry or be anxious"],
        @[@"구름", @"a cloud or the clouds"],
        @[@"끄다", @"put out or extinguish"],
        @[@"계절", @"season"],
        @[@"운동장", @"stadium, playground"],
        @[@"잠깐", @"for a little while"],
        @[@"주", @"one week"],
        @[@"요즈음", @"recently, nowadays"],
        @[@"잃어버리다", @"to lose"],
        @[@"잠깐", @"for a little while"],
        @[@"조용하다", @"to be quiet, still"],
        @[@"한복", @"korean traditional clothing"],
        @[@"바지", @"pants"],
        @[@"싫어하다", @"to dislike, be reluctant (to do)"],
        @[@"테이블", @"table"],
        @[@"피곤하다", @"to be very tired, exhausted"],
        @[@"한국어", @"korean (language)"],
        @[@"한자", @"korean character, derived from chinese"],
        @[@"시", @"city"],
        @[@"안경", @"glasses"],
        @[@"약속하다", @"to make a promise"],
        @[@"취미", @"hobby"],
        @[@"덥다", @"be hot, heated"],
        @[@"야구", @"baseball"],
        @[@"이", @"a tooth"],
        @[@"구경", @"an enjoyable sight or spectacle"],
        @[@"그분", @"that person (respectful)"],
        @[@"신다", @"put on, wear"],
        @[@"죄송하다", @"regret, be sorry for"],
        @[@"크다", @"to be big, large"],
        @[@"그럼", @"interjection: “yeh or that’s right”"],
        @[@"셋", @"three"],
        @[@"생선", @"raw fish"],
        @[@"지우다", @"to erase"],
        @[@"졸업", @"graduation"],
        @[@"닭", @"chicken"],
        @[@"맥주", @"beer"],
        @[@"교과서", @"textbook"],
        @[@"수영", @"swimming"],
        @[@"잊어버리다", @"to forget"],
        @[@"기차", @"a train"],
        @[@"식탁", @"dinner table"],
        @[@"공원", @"park"],
        @[@"안되다", @"must not, should not"],
        @[@"날짜", @"date"],
        @[@"샌드위치", @"sandwich"],
        @[@"그쪽", @"those people"],
        @[@"차", @"tea"],
        @[@"검은색", @"black or dark"],
        @[@"여보세요", @"telephone hello"],
        @[@"거", @"that thing"],
        @[@"서쪽", @"the west"],
        @[@"경찰서", @"a police station"],
        @[@"구두", @"shoes or boots"],
        @[@"사과", @"an apple"],
        @[@"여학생", @"female student"],
        @[@"냉장고", @"freezer"],
        @[@"감기", @"a cold"],
        @[@"결혼식", @"wedding"],
        @[@"노래하다", @"to sing"],
        @[@"늦다", @"be late, overdue"],
        @[@"연필", @"pencil"],
        @[@"운전", @"driving"],
        @[@"불고기", @"roast meat"],
        @[@"목욕", @"a bath"],
        @[@"전화번호", @"telephone number"],
        @[@"만", @"10000"],
        @[@"지갑", @"a purse, wallet"],
        @[@"친절하다", @"to be kind, to be nice"],
        @[@"먹다", @"vst + 먹다 , adds no meaning"],
        @[@"저거", @"that thing over there"],
        @[@"걸어오다", @"come on foot or walk"],
        @[@"모자", @"a hat"],
        @[@"소파", @"sofa"],
        @[@"스무", @"20"],
        @[@"역", @"a railroad station/depot"],
        @[@"인사하다", @"to greet, say hello"],
        @[@"여권", @"a passport"],
        @[@"열쇠", @"lock"],
        @[@"오렌지", @"orange"],
        @[@"번호", @"a number"],
        @[@"저것", @"that thing over there"],
        @[@"수박", @"watermelon"],
        @[@"첫째", @"the first"],
        @[@"과자", @"a snack or pastries or candy"],
        @[@"대학교", @"university"],
        @[@"안녕히", @"peacefully"],
        @[@"전화하다", @"to call"],
        @[@"수건", @"handkerchief"],
        @[@"양복", @"western european style clothing"],
        @[@"잠자다", @"fall asleep"],
        @[@"젓가락", @"a pair of chopsticks"],
        @[@"피아노", @"pian"],
        @[@"축하하다", @"to congratulate sb"],
        @[@"기숙사", @"a hostel or residence hall"],
        @[@"산책", @"a walk, stroll"],
        @[@"운동하다", @"to do exercise"],
        @[@"월요일", @"monday"],
        @[@"주소", @"an address"],
        @[@"파티", @"party"],
        @[@"달다", @"to be sweet"],
        @[@"청소하다", @"to clean"],
        @[@"감사하다", @"to thank"],
        @[@"메뉴", @"menu"],
        @[@"셋째", @"the third"],
        @[@"외국어", @"a foreign language; sometimes, only means english"],
        @[@"자장면", @"black chinese noodles"],
        @[@"중학생", @"middle school student"],
        @[@"휴일", @"a day off of work, a holiday"],
        @[@"달력", @"a calendar"],
        @[@"소풍", @"picnic"],
        @[@"춤추다", @"to dance"],
        @[@"테니스", @"tennis"],
        @[@"공책", @"notebook for taking notes and studying"],
        @[@"배", @"pear"],
        @[@"서점", @"a bookstore"],
        @[@"양말", @"a sock"],
        @[@"초대하다", @"to invide"],
        @[@"연습하다", @"to practice, exercise"],
        @[@"경치", @"a scene or scenery"],
        @[@"발음", @"pronunciation"],
        @[@"재미없다", @"boring"],
        @[@"주스", @"juice"],
        @[@"콜라", @"cola"],
        @[@"남학생", @"male student"],
        @[@"식사하다", @"to eat a meal"],
        @[@"우체국", @"a post office"],
        @[@"고프다", @"hungry or famished"],
        @[@"대사관", @"embassy"],
        @[@"배고프다", @"to be hungry"],
        @[@"삼", @"three"],
        @[@"여행하다", @"to travel"],
        @[@"정류장", @"stop, a station, bus-stop"],
        @[@"맵다", @"spicy"],
        @[@"여동생", @"younger sister"],
        @[@"오래간만", @"after a long time"],
        @[@"점심시간", @"lunchtime"],
        @[@"휴지", @"toilet paper"],
        @[@"넷째", @"fourth"],
        @[@"태권도", @"tae kwon do"],
        @[@"햄버거", @"hamburger"],
        @[@"감사", @"thanks"],
        @[@"슈퍼마켓", @"supermarket"],
        @[@"비누", @"soap"],
        @[@"세수", @"hand-washing"],
        @[@"찌개", @"a pot stew"],
        @[@"넥타이", @"necktie"],
        @[@"월", @"a month"],
        @[@"잡수시다", @"eat, drink"],
        @[@"한국말", @"korean (language)"],
        @[@"계란", @"an egg"],
        @[@"넷", @"4"],
        @[@"에어컨", @"air conditioner"],
        @[@"초대", @"an invitation"],
        @[@"사전", @"dictionary"],
        @[@"실례", @"rudeness, impolite"],
        @[@"안녕", @"hello/goodbye"],
        @[@"약국", @"pharmacy"],
        @[@"지난주", @"last week"],
        @[@"간호사", @"nurse"],
        @[@"고등학생", @"high school student"],
        @[@"다섯", @"5"],
        @[@"닭고기", @"chicken meat for eating"],
        @[@"숟가락", @"a spoon"],
        @[@"요일", @"a day of the week not the weekend"],
        @[@"일", @"one"],
        @[@"질문하다", @"ask a person a question"],
        @[@"치약", @"toothpaste"],
        @[@"금요일", @"friday"],
        @[@"김밥", @"roll of rice and vegetables"],
        @[@"바나나", @"banana"],
        @[@"수요일", @"wednesday"],
        @[@"운전하다", @"to drive"],
        @[@"노트", @"a note"],
        @[@"초콜릿", @"chocolate"],
        @[@"피자", @"pizza"],
        @[@"노란색", @"yellow"],
        @[@"달러", @"dollar"],
        @[@"만", @"10000"],
        @[@"이분", @"divide into two"],
        @[@"칫솔", @"a toothbrush"],
        @[@"포도", @"grape(s)"],
        @[@"배부르다", @"to be full"],
        @[@"캐나다", @"canada"],
        @[@"샤워", @"shower"],
        @[@"세탁기", @"washing machine"],
        @[@"그래서", @"so or therefore"],
        @[@"남동생", @"younger brother"],
        @[@"도착", @"arrival"],
        @[@"쇼핑", @"shopping"],
        @[@"스키", @"ski"],
        @[@"열", @"ten"],
        @[@"운동화", @"sports shoes"],
        @[@"짜다", @"to be salty"],
        @[@"초등학교", @"elementary school"],
        @[@"공휴일", @"a legal holiday"],
        @[@"마흔", @"forty"],
        @[@"볼펜", @"a ballpen"],
        @[@"빨간색", @"deep-red, crimson"],
        @[@"이", @"two"],
        @[@"중국", @"china"],
        @[@"스물", @"twenty"],
        @[@"청바지", @"blue jeans"],
        @[@"핸드폰", @"cell phone"],
        @[@"휴지통", @"waste paper basket"],
        @[@"넷째", @"fourth"],
        @[@"칠판", @"the blackboard"],
        @[@"크리스마스", @"christmas"],
        @[@"구", @"9"],
        @[@"목요일", @"thursday"],
        @[@"지우개", @"an eraser"],
        @[@"사", @"four, the fourth"],
        @[@"수영장", @"swimming pool"],
        @[@"일본어", @"japanese"],
        @[@"갈비", @"the ribs"],
        @[@"서른", @"thirty"],
        @[@"아홉", @"nine"],
        @[@"장미", @"a rose"],
        @[@"파란색", @"blue"],
        @[@"냉면", @"cold noodles soup"],
        @[@"비빔밥", @"vegetarian dish of rice and vegetables"],
        @[@"여든", @"eighty"],
        @[@"일흔", @"seventy"],
        @[@"화요일", @"tuesday"],
        @[@"선물하다", @"give a gift"],
        @[@"아이스크림", @"ice cream"],
        @[@"요리하다", @"to cook (food)"],
        @[@"칠", @"seven"],
        @[@"맛없다", @"bad flavor"],
        @[@"백", @"one hundred"],
        @[@"사십", @"40"],
        @[@"팔", @"eight"],
        @[@"실례하다", @"to be impolite"],
        @[@"여섯", @"six"],
        @[@"육", @"the number six"],
        @[@"일곱", @"seven"],
        @[@"삼십", @"30"],
        @[@"오십", @"fifty"],
        @[@"중국어", @"chinese"],
        @[@"칠십", @"seventy"],
        @[@"다섯째", @"fifth"],
        @[@"사탕", @"sugar"],
        @[@"예순", @"sixty"],
        @[@"오", @"five"],
        @[@"십", @"10"],
        @[@"천", @"thousand"],
        @[@"쉰", @"50"],
        @[@"육십", @"sixty"],
        @[@"팔십", @"80"],
        @[@"여덟", @"eight"],
        @[@"아흔", @"ninety"],
        @[@"이십", @"twenty"],
        @[@"독일", @"germany"],
        @[@"영국", @"england"],
        @[@"회사", @"a company"],
        @[@"구십", @"90"],
        @[@"기다리다", @"to wait"],
        @[@"인천", @"incheon city"],
        @[@"거기", @"there (location)"],
        @[@"저곳", @"that place over there"]
    ];
}

@end
