//
//  xxiivvViewController.m
//  nijuniju
//
//  Created by Devine Lu Linvega on 2013-08-06.
//  Copyright (c) 2013 XXIIVV. All rights reserved.
//

#import "xxiivvViewController.h"
#import <QuartzCore/QuartzCore.h>

@implementation xxiivvViewController (Modules)

- (void) nodeStart
{
	nodeContentArray = [[NSMutableArray alloc] init];
	
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"日", @"sun|ひ", @"country|--", @"in|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"一", @"ten|とお", @"two|ふた", @"one|ひと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"国", @"country|--", @"main|--", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"人", @"year|--", @"person|ひと", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"年", @"hour|とき", @"exit|でる", @"year|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"大", @"big|おお", @"main|--", @"hour|とき",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"十", @"big|おお", @"ten|とお", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"二", @"country|--", @"two|ふた", @"three|み",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"本", @"main|--", @"exit|でる", @"in|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"中", @"big|おお", @"going|いく", @"in|なか",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"長", @"one|ひと", @"long|ながい", @"two|ふた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"出", @"long|ながい", @"ten|とお", @"exit|でる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"三", @"three|み", @"ten|とお", @"before|まえ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"時", @"person|ひと", @"one|ひと", @"hour|とき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"行", @"going|いく", @"four|よ", @"country|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"見", @"see|みる", @"back|のち", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"月", @"moon|--", @"hour|とき", @"up|うえ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"後", @"one|ひと", @"back|のち", @"big|おお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"前", @"before|まえ", @"up|うえ", @"long|ながい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"生", @"four|よ", @"life|いきる", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"五", @"one|ひと", @"five|いつ", @"life|いきる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"間", @"going|いく", @"space|あいだ", @"hour|とき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"上", @"going|いく", @"up|うえ", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"東", @"exit|でる", @"long|ながい", @"east|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"四", @"year|--", @"in|なか", @"four|よ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"今", @"now|--", @"moon|--", @"eight|や",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"金", @"life|いきる", @"gold|かね", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"九", @"nine|ここの", @"up|うえ", @"six|む",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"入", @"one|ひと", @"enter|いる", @"gold|かね",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"学", @"study|--", @"person|ひと", @"mind|いき",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"高", @"ten|とお", @"high|たかい", @"six|む",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"円", @"moon|--", @"yen|まるい", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"子", @"in|なか", @"child|こ", @"moon|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"外", @"outside|そと", @"see|みる", @"six|む",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"八", @"high|たかい", @"person|ひと", @"eight|や",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"六", @"study|--", @"six|む", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"下", @"mountain|--", @"talk|はなす", @"low|した",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"来", @"due|くる", @"person|ひと", @"write|かく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"気", @"in|なか", @"mind|いき", @"enter|いる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"小", @"seven|なな", @"talk|はなす", @"small|ちいさい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"七", @"write|かく", @"seven|なな", @"yen|まるい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"山", @"space|あいだ", @"mountain|--", @"four|よ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"話", @"talk|はなす", @"space|あいだ", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"女", @"outside|そと", @"woman|おんな", @"big|おお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"北", @"hundred|--", @"gold|かね", @"north|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"午", @"noon|うま", @"big|おお", @"low|した",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"百", @"due|くる", @"now|--", @"hundred|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"書", @"write|かく", @"male|おとこ", @"exit|でる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"先", @"east|--", @"exam|--", @"ahead|さき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"名", @"nine|ここの", @"half|--", @"name|な",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"川", @"word|かたる", @"wood|き", @"river|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"千", @"big|おお", @"soil|--", @"thousand|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"水", @"water|みず", @"study|--", @"mountain|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"半", @"half|--", @"life|いきる", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"男", @"male|おとこ", @"hour|とき", @"soil|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"西", @"in|なか", @"west|--", @"going|いく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"電", @"big|おお", @"electricity|--", @"enter|いる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"校", @"low|した", @"exam|--", @"four|よ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"語", @"word|かたる", @"west|--", @"going|いく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"土", @"soil|--", @"water|みず", @"long|ながい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"木", @"see|みる", @"exam|--", @"wood|き",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"聞", @"main|--", @"high|たかい", @"ask|きく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"食", @"north|--", @"car|--", @"eat|くう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"車", @"car|--", @"back|のち", @"five|いつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"何", @"south|--", @"what|なに", @"mountain|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"南", @"every|ごと", @"white|しろ", @"south|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"万", @"two|ふた", @"gold|かね", @"ten thousand|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"毎", @"every|ごと", @"water|みず", @"country|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"白", @"white|しろ", @"wood|き", @"high|たかい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"天", @"exam|--", @"sky|あまつ", @"right|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"母", @"life|いきる", @"mama|はは", @"woman|おんな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"火", @"left|--", @"fire|ひ", @"gold|かね",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"右", @"right|--", @"word|かたる", @"mountain|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"読", @"river|--", @"write|かく", @"read|よむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"友", @"rest|やすむ", @"friend|--", @"talk|はなす",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"左", @"read|よむ", @"noon|うま", @"left|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"休", @"rest|やすむ", @"year|--", @"one|ひと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"父", @"firm|--", @"father|ちち", @"woman|おんな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雨", @"long|ながい", @"rain|あめ", @"noon|うま",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"会", @"east|--", @"exit|でる", @"meet|あう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"同", @"same|おなじ", @"fire|ひ", @"river|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"事", @"hundred|--", @"space|あいだ", @"fact|こと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"自", @"oneself|みずから", @"talk|はなす", @"river|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"社", @"firm|--", @"gold|かね", @"thousand|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"発", @"emit|たつ", @"thousand|--", @"mountain|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"者", @"person|もの", @"person|かた", @"oneself|みずから",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"地", @"earth|--", @"six|む", @"person|もの",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"業", @"arts|--", @"what|なに", @"two|ふた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"方", @"north|--", @"ask|きく", @"person|かた",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"新", @"emit|たつ", @"new|あたらしい", @"car|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"場", @"rain|あめ", @"back|のち", @"place|ば",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"員", @"noon|うま", @"due|くる", @"member|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"立", @"stand up|たつ", @"thousand|--", @"country|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"開", @"open|ひらく", @"place|ば", @"now|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"手", @"now|--", @"hour|とき", @"hand|て",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"力", @"exert|--", @"ahead|さき", @"emit|たつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"問", @"main|--", @"ten|とお", @"ask|とう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"代", @"age|かわる", @"earth|--", @"half|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"明", @"body|からだ", @"light|あかり", @"big|おお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"動", @"friend|--", @"move|うごく", @"life|いきる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"京", @"10**16|--", @"space|あいだ", @"ten thousand|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"目", @"eye|め", @"open|ひらく", @"child|こ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"通", @"lord|ぬし", @"rest|やすむ", @"avenue|とおる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"言", @"say|いう", @"stand up|たつ", @"mind|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"理", @"truth|--", @"moon|--", @"going|いく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"体", @"topic|--", @"fire|ひ", @"body|からだ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"田", @"topic|--", @"rice paddy|--", @"mind|いき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"主", @"lord|ぬし", @"word|かたる", @"space|あいだ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"題", @"fact|こと", @"member|--", @"topic|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"意", @"right|--", @"mind|--", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"不", @"bad|--", @"main|--", @"six|む",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"作", @"lord|ぬし", @"yen|まるい", @"make|つくる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"用", @"use|--", @"white|しろ", @"think|おもう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"度", @"time|たび", @"woman|おんな", @"enter|いる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"強", @"strong|つよい", @"white|しろ", @"person|かた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"公", @"ten|とお", @"bad|--", @"prince|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"持", @"have|もつ", @"friend|--", @"wood|き",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"野", @"field|の", @"ten thousand|--", @"avenue|とおる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"以", @"left|--", @"because|--", @"hundred|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"思", @"north|--", @"avenue|とおる", @"think|おもう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"家", @"noon|うま", @"home|いえ", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"世", @"world|よ", @"low|した", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"多", @"topic|--", @"talk|はなす", @"much|おおい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"正", @"nine|ここの", @"year|--", @"10**40|ただしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"安", @"oneself|みずから", @"low|やすい", @"three|み",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"院", @"Inst.|--", @"home|いえ", @"eye|め",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"心", @"mind|りっしんべん", @"going|いく", @"firm|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"界", @"world|--", @"bad|--", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"教", @"picture|えがく", @"faith|おしえる", @"say|いう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"文", @"art|ふみ", @"thousand|--", @"rice paddy|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"元", @"ask|とう", @"river|--", @"origin|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"重", @"half|--", @"emit|たつ", @"-fold|え",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"近", @"akin|--", @"prince|--", @"arts|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"考", @"10**16|--", @"thousand|--", @"consider|かんがえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"画", @"ten thousand|--", @"picture|えがく", @"use|つかう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"海", @"use|--", @"person|ひと", @"sea|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"売", @"see|みる", @"sell|うる", @"child|こ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"知", @"eye|め", @"know|しる", @"new|あたらしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"道", @"name|な", @"stand up|たつ", @"moral|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"集", @"child|こ", @"goods|しな", @"meet|あつまる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"別", @"prince|--", @"fork|わかれる", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"物", @"thing|もの", @"ten thousand|--", @"five|いつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"使", @"use|つかう", @"before|まえ", @"white|しろ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"品", @"goods|しな", @"person|ひと", @"meet|あつまる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"計", @"plan|はかる", @"life|いきる", @"truth|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"死", @"see|みる", @"die|しぬ", @"soil|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"特", @"special|--", @"ask|とう", @"five|いつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"私", @"I|わたくし", @"world|--", @"lot|はこぶ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"始", @"back|のち", @"year|--", @"begin|はじめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"朝", @"read|よむ", @"special|--", @"epoch|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"運", @"lot|はこぶ", @"ahead|さき", @"year|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"終", @"river|--", @"end|おわる", @"what|なに",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"台", @"a stand|うてな", @"exit|でる", @"lord|ぬし",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"広", @"wide|ひろい", @"ten|とお", @"open|ひらく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"住", @"live|すむ", @"strong|つよい", @"half|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"真", @"firm|--", @"true|ま", @"new|あたらしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"有", @"river|--", @"male|おとこ", @"have|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"口", @"mouth|くち", @"eight|や", @"eye|め",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"少", @"emit|たつ", @"rice paddy|--", @"few|すくない",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"町", @"exert|--", @"town|まち", @"father|ちち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"料", @"fee|--", @"life|いきる", @"art|ふみ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"工", @"now|--", @"electricity|--", @"craft|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"建", @"person|ひと", @"build|たてる", @"ease|たのしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"空", @"main|--", @"sky|そら", @"five|いつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"急", @"steep|いそぐ", @"fact|こと", @"moon|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"止", @"halt|とまる", @"world|よ", @"south|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"送", @"electricity|--", @"thing|もの", @"send|おくる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"切", @"make|つくる", @"cut|きる", @"earth|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"転", @"ask|とう", @"talk|はなす", @"change|ころがる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"研", @"10**16|--", @"polish|--", @"person|もの",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"足", @"leg|あし", @"person|もの", @"see|みる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"究", @"country|--", @"low|した", @"study|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"楽", @"ease|たのしい", @"fact|こと", @"matter|たち",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"起", @"now|--", @"rouse|おきる", @"place|ば",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"着", @"gold|かね", @"earth|--", @"don|きる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"店", @"halt|とまる", @"shop|みせ", @"half|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"病", @"main|--", @"ill|やむ", @"space|あいだ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"質", @"matter|たち", @"bad|--", @"child|こ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"待", @"wait|まつ", @"ahead|さき", @"talk|はなす",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"試", @"try|こころみる", @"bad|--", @"wait|まつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"族", @"tribe|--", @"rouse|おきる", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"銀", @"ahead|さき", @"silver|--", @"field|の",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"早", @"fast|はやい", @"tribe|--", @"study|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"映", @"goods|しな", @"emit|たつ", @"reflect|うつる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"親", @"member|--", @"few|すくない", @"parent|おや",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"験", @"father|ちち", @"effect|あかし", @"matter|たち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"英", @"English|--", @"now|--", @"eye|め",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"医", @"meet|あつまる", @"new|あたらしい", @"doctor|いやす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"仕", @"right|--", @"doing|つかえる", @"shop|みせ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"去", @"past|さる", @"light|あかり", @"old|ふるい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"味", @"taste|あじ", @"study|--", @"white|しろ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"写", @"copy|うつす", @"main|--", @"taste|あじ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"字", @"word|あざ", @"every|ごと", @"lot|はこぶ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"答", @"try|こころみる", @"-fold|え", @"answer|こたえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夜", @"mouth|くち", @"night|よ", @"taste|あじ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"音", @"noise|おと", @"word|かたる", @"seven|なな",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"注", @"three|み", @"see|みる", @"pour|そそぐ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"帰", @"have|もつ", @"world|--", @"lead to|かえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"古", @"old|ふるい", @"child|こ", @"high|たかい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歌", @"sing|うた", @"life|いきる", @"rain|あめ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"買", @"buy|かう", @"east|--", @"soil|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"悪", @"few|すくない", @"bad|わるい", @"paper|かみ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"図", @"low|した", @"answer|こたえる", @"map|え",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"週", @"week|--", @"due|くる", @"wait|まつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"室", @"half|--", @"age|かわる", @"room|むろ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歩", @"going|いく", @"ease|たのしい", @"walk|あるく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"風", @"buy|かう", @"air|かぜ", @"person|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"紙", @"seven|なな", @"paper|かみ", @"sell|うる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"黒", @"town|まち", @"fact|こと", @"black|くろ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"花", @"night|よ", @"art|ふみ", @"flower|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"春", @"springtime|--", @"ill|やむ", @"in|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"赤", @"red|あか", @"eat|くう", @"wide|ひろい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"青", @"life|いきる", @"change|ころがる", @"blue|あお",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"館", @"faith|おしえる", @"don|きる", @"palace|やかた",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"屋", @"shop|--", @"tribe|--", @"half|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"色", @"half|--", @"night|よ", @"color|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"走", @"run|--", @"trip|たび", @"lot|はこぶ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"秋", @"origin|--", @"eat|くう", @"autumn|あき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夏", @"summer|なつ", @"person|ひと", @"name|な",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"習", @"every|ごと", @"learn|ならう", @"high|たかい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"駅", @"a stand|うてな", @"west|--", @"station|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"洋", @"two|ふた", @"station|--", @"ocean|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"旅", @"trip|たび", @"shop|みせ", @"see|みる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"服", @"obey|--", @"ten|とお", @"what|なに",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夕", @"craft|--", @"member|--", @"evening|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"借", @"person|もの", @"rent|かりる", @"two|ふた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"曜", @"hour|とき", @"child|こ", @"weekday|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飲", @"take|のむ", @"long|ながい", @"special|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"肉", @"meat|--", @"map|え", @"rent|かりる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"貸", @"copy|うつす", @"use|つかう", @"lend|かす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"堂", @"firm|--", @"hall|--", @"two|ふた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"鳥", @"west|--", @"read|よむ", @"bird|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飯", @"meal|--", @"lead to|かえる", @"springtime|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勉", @"few|すくない", @"autumn|あき", @"exertion|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"冬", @"winter|ふゆ", @"up|うえ", @"fee|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昼", @"yen|まるい", @"noon|ひる", @"low|やすい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"茶", @"study|--", @"make|つくる", @"tea|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"弟", @"exit|でる", @"younger brother|--", @"ocean|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"牛", @"cow|--", @"lend|かす", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"魚", @"west|--", @"lead|つらなる", @"fish|うお",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"兄", @"map|え", @"big brother|--", @"cow|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"犬", @"cow|--", @"hand|て", @"dog|いぬ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"妹", @"have|もつ", @"younger sister|--", @"ten thousand|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"姉", @"elder sister|あね", @"night|よ", @"0.1|あう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"漢", @"China|--", @"wait|まつ", @"gold|かね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"政", @"fork|わかれる", @"politics|まつりごと", @"halt|とまる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"議", @"debate|--", @"wait|まつ", @"rent|かりる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"民", @"matter|たち", @"nation|--", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"連", @"lead|つらなる", @"game|まわる", @"elder sister|あね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"対", @"hand|て", @"four|よ", @"even|あいて",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"部", @"winter|ふゆ", @"father|ちち", @"dept|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"合", @"0.1|あう", @"say|いう", @"woman|おんな",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"市", @"now|--", @"city|--", @"fork|わかれる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"内", @"home|--", @"write|かく", @"what|なに",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"相", @"hall|--", @"phase|あい", @"oneself|みずから",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"定", @"fix|さだめる", @"stand up|たつ", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"回", @"place|ば", @"all|まったく", @"game|まわる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"選", @"space|あいだ", @"truth|--", @"elect|えらぶ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"米", @"reflect|うつる", @"even|あいて", @"USA|こめ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"実", @"arts|--", @"truth|み", @"year|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"関", @"say|いう", @"barrier|せき", @"see|みる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"決", @"pour|そそぐ", @"fix|きめる", @"station|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"全", @"time|たび", @"all|まったく", @"small|ちいさい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"表", @"world|--", @"thousand|--", @"table|おもて",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"戦", @"war|いくさ", @"white|しろ", @"moral|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"経", @"warp|へる", @"two|ふた", @"eat|くう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"最", @"most|もっとも", @"ahead|さき", @"moon|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"現", @"same|おなじ", @"actual|あらわれる", @"taste|あじ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"調", @"tone|しらべる", @"air|かぜ", @"person|もの",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"化", @"long|ながい", @"delude|ばける", @"elect|えらぶ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"当", @"south|--", @"before|まえ", @"hit|あたる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"約", @"mama|はは", @"shrink|--", @"thing|もの",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"首", @"river|--", @"one|ひと", @"neck|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"法", @"main|--", @"city|--", @"law|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"性", @"back|のち", @"sex|さが", @"fire|ひ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"要", @"read|よむ", @"most|もっとも", @"need|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"制", @"word|あざ", @"place|ば", @"law|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"治", @"10**40|ただしい", @"govt|おさめる", @"woman|おんな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"務", @"water|みず", @"task|--", @"avenue|とおる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"成", @"get|なる", @"nation|--", @"politics|まつりごと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"期", @"lead|つらなる", @"epoch|--", @"time|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"取", @"field|の", @"take|とる", @"dept|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"都", @"10**40|ただしい", @"yen|まるい", @"capital|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"和", @"exit|でる", @"fish|うお", @"peace|やわらぐ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"機", @"due|くる", @"machine|はた", @"home|いえ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"平", @"flat|たいら", @"steep|いそぐ", @"eat|くう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"加", @"station|--", @"cut|きる", @"add|くわえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"受", @"get|うける", @"open|ひらく", @"north|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"続", @"series|つづく", @"left|--", @"noon|うま",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"進", @"plan|はかる", @"country|--", @"proceed|すすむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"数", @"law|かず", @"special|--", @"ease|たのしい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"記", @"place|ば", @"scribe|--", @"game|まわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"初", @"USA|こめ", @"rain|あめ", @"beginning|はじめ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"指", @"debate|--", @"finger|ゆび", @"take|のむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"権", @"power|おもり", @"south|--", @"low|やすい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"支", @"fee|--", @"branch|しんよう", @"-fold|え",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"産", @"bear|うむ", @"matter|たち", @"shop|みせ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"点", @"tribe|--", @"rain|あめ", @"mark|つける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"報", @"news|むくいる", @"exertion|--", @"truth|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"済", @"delude|ばける", @"shop|--", @"finish|すむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"活", @"power|おもり", @"sell|うる", @"living|いきる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"原", @"answer|こたえる", @"field|--", @"age|かわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"共", @"world|よ", @"evening|--", @"all|とも",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"得", @"get|える", @"finish|すむ", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"解", @"key|とく", @"fix|きめる", @"time|たび",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"交", @"nine|ここの", @"study|--", @"mixing|まじわる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"資", @"data|--", @"paper|かみ", @"law|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"予", @"I|あらかじめ", @"say|いう", @"time|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"向", @"younger sister|--", @"defy|むく", @"moon|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"際", @"have|--", @"prince|--", @"side|きわ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勝", @"now|--", @"win|かつ", @"0.1|あう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"面", @"right|--", @"going|いく", @"face|おも",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"告", @"take|とる", @"0.1|あう", @"tell|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"反", @"say|いう", @"anti-|そる", @"city|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"判", @"bad|--", @"black|くろ", @"seal|わかる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"認", @"anti-|そる", @"shop|--", @"witness|みとめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"参", @"two|ふた", @"die|まいる", @"epoch|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"利", @"profit|--", @"topic|--", @"epoch|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"組", @"braid|くむ", @"table|おもて", @"mind|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"信", @"truth|--", @"study|--", @"in|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"在", @"braid|くむ", @"exist|--", @"rice paddy|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"件", @"city|--", @"case|くだん", @"place|ところ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"側", @"noon|ひる", @"lean|かわ", @"home|いえ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"任", @"blue|あお", @"duty|まかせる", @"make|つくる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"引", @"tug|ひく", @"war|いくさ", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"求", @"want|もとめる", @"steep|いそぐ", @"woman|おんな",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"所", @"light|あかり", @"place|ところ", @"faith|おしえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"次", @"effect|あかし", @"next|つぐ", @"don|きる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昨", @"previous|--", @"capital|--", @"water|みず",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"論", @"truth|み", @"argument|--", @"effect|あかし",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"官", @"law|--", @"bureaucrat|--", @"peace|やわらぐ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"増", @"add|ます", @"exam|--", @"child|こ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"係", @"duty|かかる", @"woman|おんな", @"eat|くう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"感", @"red|あか", @"rice paddy|--", @"feeling|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"情", @"facts|なさけ", @"exertion|--", @"plan|はかる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"投", @"study|--", @"join|なげる", @"machine|はた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"示", @"war|いくさ", @"show|しめす", @"palace|やかた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"変", @"seven|なな", @"west|--", @"change|かわる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"打", @"hit|うつ", @"series|つづく", @"much|おおい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"直", @"act|--", @"live|すむ", @"fix|ただちに",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"両", @"two|てる", @"sea|--", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"式", @"China|--", @"rite|--", @"high|たかい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"確", @"firm|たしか", @"matter|たち", @"law|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"果", @"end|はたす", @"red|あか", @"taste|あじ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"容", @"week|--", @"male|おとこ", @"form|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"必", @"bad|--", @"certain|かならず", @"shop|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"演", @"answer|こたえる", @"act|--", @"I|わたくし",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歳", @"fork|わかれる", @"ocean|--", @"age|とし",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"争", @"one|ひと", @"ill|やむ", @"argue|あらそう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"談", @"get|うける", @"fact|こと", @"talk|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"能", @"skill|--", @"show|しめす", @"defy|むく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"位", @"some|くらい", @"thing|もの", @"art|ふみ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"置", @"pour|そそぐ", @"study|--", @"put|おく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"流", @"proceed|すすむ", @"flow|ながれる", @"rain|あめ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"格", @"low|やすい", @"meat|--", @"rank|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"疑", @"doubt|うたがう", @"world|--", @"city|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"過", @"I|あらかじめ", @"error|すぎる", @"certain|かならず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"局", @"life|いきる", @"due|くる", @"board|つぼね",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"放", @"three|み", @"fire|はなす", @"certain|かならず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"常", @"politics|まつりごと", @"usual|つね", @"left|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"状", @"change|ころがる", @"life|いきる", @"form|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"球", @"light|あかり", @"English|--", @"ball|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"職", @"moral|--", @"two|てる", @"work|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"与", @"rent|かりる", @"give|あたえる", @"paper|かみ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"供", @"think|おもう", @"offer|そなえる", @"silver|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"役", @"lend|かす", @"age|かわる", @"war|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"構", @"read|よむ", @"build|かまえる", @"air|かぜ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"割", @"cut|わる", @"peace|やわらぐ", @"duty|まかせる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"費", @"cost|ついやす", @"main|--", @"offer|そなえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"付", @"old|ふるい", @"west|--", @"attach|つける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"由", @"up|うえ", @"a reason|よし", @"meal|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"説", @"shop|みせ", @"car|--", @"rumor|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"難", @"sea|--", @"learn|ならう", @"defect|かたい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"優", @"excel|やさしい", @"China|--", @"tug|ひく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夫", @"man|おっと", @"lot|はこぶ", @"lead to|かえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"収", @"male|おとこ", @"use|つかう", @"pay|おさめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"断", @"lot|はこぶ", @"a stand|うてな", @"warn|たつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"石", @"black|くろ", @"stone|--", @"face|おも",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"違", @"exit|でる", @"differ|ちがう", @"light|あかり",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"消", @"evening|--", @"consider|かんがえる", @"cancel|きえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"神", @"board|つぼね", @"ill|やむ", @"mind|かみ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"番", @"eight|や", @"add|くわえる", @"turn|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"規", @"measure|--", @"bad|--", @"see|みる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"術", @"art|すべ", @"effect|あかし", @"rest|やすむ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"備", @"two|てる", @"equip|そなえる", @"defect|かたい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"宅", @"home|--", @"branch|しんよう", @"visit|おとずれる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"害", @"car|--", @"ask|とう", @"harm|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"配", @"bird|--", @"exile|くばる", @"table|おもて",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"警", @"use|つかう", @"admonish|いましめる", @"ask|とう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"育", @"use|--", @"rear|そだつ", @"white|しろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"席", @"have|もつ", @"firm|--", @"mat|むしろ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"訪", @"neck|--", @"visit|おとずれる", @"mat|むしろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"乗", @"join|のる", @"cost|ついやす", @"stone|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"残", @"actual|あらわれる", @"excel|やさしい", @"balance|のこる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"想", @"every|ごと", @"toil|ろうする", @"idea|おもう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"声", @"voice|こえ", @"arts|--", @"move|うごく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"念", @"idea|--", @"pour|そそぐ", @"get|なる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"助", @"bad|わるい", @"argue|あらそう", @"help|たすける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"労", @"gold|かね", @"small|ちいさい", @"toil|ろうする",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"例", @"exile|くばる", @"capital|--", @"usage|たとえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"然", @"so|しか", @"arts|--", @"south|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"限", @"limit|かぎる", @"room|むろ", @"six|む",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"追", @"old|ふるい", @"chase|--", @"five|いつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"商", @"flow|ながれる", @"selling|--", @"phase|あい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"葉", @"lobe|--", @"Inst.|--", @"shrink|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"伝", @"follow|つたわる", @"small|ちいさい", @"life|いきる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"働", @"work|はたらく", @"braid|くむ", @"toil|ろうする",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"形", @"form|かた", @"ask|とう", @"name|な",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"景", @"effect|あかし", @"view|--", @"picture|えがく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"落", @"drop|おちる", @"leg|あし", @"attach|つける",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"好", @"life|いきる", @"rear|そだつ", @"fond|このむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"退", @"member|--", @"light|あかり", @"repel|しりぞく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頭", @"rent|かりる", @"mama|はは", @"head|あたま",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"負", @"mind|--", @"-|まける", @"art|すべ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"渡", @"gold|かね", @"ford|わたる", @"debate|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"失", @"mind|いき", @"loss|うしなう", @"dog|いぬ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"差", @"-|まける", @"differ|ちがう", @"margin|さす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"末", @"Inst.|--", @"tip|すえ", @"beauty|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"守", @"obey|まもる", @"USA|こめ", @"move|うごく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"若", @"fire|はなす", @"if|わかい", @"river|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"種", @"kind|たね", @"town|まち", @"east|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"美", @"get|うける", @"ford|わたる", @"beauty|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"命", @"rank|--", @"oneself|みずから", @"life|いのち",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"福", @"art|すべ", @"argue|あらそう", @"luck|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"望", @"finish|すむ", @"younger brother|--", @"hope|のぞむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"非", @"meal|--", @"un-|あらず", @"know|しる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"観", @"look|みる", @"cow|--", @"dept|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"察", @"judge|--", @"field|--", @"halt|とまる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"段", @"now|--", @"past|さる", @"steps|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"横", @"side|よこ", @"un-|あらず", @"noise|おと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"深", @"deep|ふかい", @"finish|すむ", @"river|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"申", @"3-5PM|もうす", @"elder sister|あね", @"join|のる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"様", @"woman|おんな", @"way|さま", @"ten thousand|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"財", @"money|--", @"walk|あるく", @"child|こ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"港", @"harbor|みなと", @"add|くわえる", @"topic|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"識", @"I|わたくし", @"know|--", @"summer|なつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"呼", @"up|うえ", @"call|--", @"write|かく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"達", @"offer|そなえる", @"politics|まつりごと", @"reach|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"良", @"avenue|とおる", @"two|てる", @"good|よい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"候", @"meet|あつまる", @"season|そうろう", @"idea|おもう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"程", @"change|ころがる", @"law|ほど", @"going|いく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"満", @"station|--", @"full|みちる", @"mark|つける",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"敗", @"defeat|やぶれる", @"form|かた", @"board|つぼね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"値", @"noon|ひる", @"cost|ね", @"black|くろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"突", @"exam|--", @"fix|さだめる", @"stab|つく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"光", @"river|--", @"ray|ひかる", @"head|あたま",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"路", @"effect|あかし", @"margin|さす", @"road|じ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"科", @"course|--", @"if|わかい", @"half|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"積", @"3-5PM|もうす", @"load|つむ", @"task|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"他", @"prince|--", @"world|よ", @"other|ほか",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"処", @"friend|--", @"next|つぐ", @"act|ところ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"太", @"thick|ふとい", @"younger sister|--", @"time|たび",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"客", @"guest|--", @"strong|つよい", @"east|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"否", @"no|いな", @"defeat|やぶれる", @"politics|まつりごと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"師", @"chase|--", @"warp|へる", @"war|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"登", @"take|のむ", @"ascend|のぼる", @"idea|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"易", @"world|--", @"easy|やさしい", @"toil|ろうする",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"速", @"join|なげる", @"work|--", @"fast|はやい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"存", @"take|のむ", @"feel|--", @"barrier|せき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飛", @"fly|とぶ", @"pay|おさめる", @"sex|さが",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"殺", @"space|あいだ", @"mark|つける", @"kill|ころす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"号", @"law|--", @"item|さけぶ", @"bad|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"単", @"rent|かりる", @"prince|--", @"one|ひとえ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"座", @"rouse|おきる", @"sit|すわる", @"effect|あかし",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"破", @"rip|やぶる", @"have|もつ", @"friend|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"除", @"in|なか", @"3)|のぞく", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"完", @"have|もつ", @"end|--", @"rip|やぶる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"降", @"try|こころみる", @"fall|おりる", @"home|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"責", @"member|--", @"harbor|みなと", @"blame|せめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"捕", @"catch|とらえる", @"capital|--", @"topic|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"危", @"fear|あぶない", @"cut|きる", @"10**40|ただしい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"給", @"wide|ひろい", @"win|かつ", @"wage|たまう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"苦", @"steps|--", @"tool|そなえる", @"trial|くるしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"迎", @"witness|みとめる", @"law|ほど", @"meet|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"園", @"tea|--", @"effect|あかし", @"yard|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"具", @"tool|そなえる", @"defect|かたい", @"sea|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"辞", @"previous|--", @"word|やめる", @"law|ほど",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"因", @"cause|よる", @"car|--", @"turn|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"馬", @"exertion|--", @"before|まえ", @"horse|うま",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"愛", @"feeling|--", @"love|--", @"war|いくさ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"富", @"enter|いる", @"springtime|--", @"enrich|とむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"彼", @"send|おくる", @"3-5PM|もうす", @"he|かれ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"未", @"un-|いまだ", @"-|まける", @"show|しめす",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"舞", @"flit|まう", @"yard|--", @"build|たてる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"亡", @"beginning|はじめ", @"strong|つよい", @"dying|ない",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"冷", @"try|こころみる", @"shrink|--", @"cool|つめたい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"適", @"rare|かなう", @"name|な", @"anti-|そる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"婦", @"wife|--", @"emit|たつ", @"repel|しりぞく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寄", @"mark|つける", @"begin|はじめる", @"send|よる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"込", @"arts|--", @"mixture|こむ", @"stone|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"顔", @"doing|つかえる", @"learn|ならう", @"face|かお",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"類", @"sing|うた", @"enrich|とむ", @"kind|たぐい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"余", @"exert|--", @"other|あまる", @"so|しか",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"王", @"rule|--", @"argument|--", @"answer|こたえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"返", @"cancel|きえる", @"two|ふた", @"fade|かえす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"妻", @"member|--", @"field|の", @"wife|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"背", @"tone|しらべる", @"north|--", @"back|せ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"熱", @"die|まいる", @"winter|ふゆ", @"heat|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"宿", @"inn|やど", @"mat|むしろ", @"wife|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"薬", @"attach|つける", @"have|もつ", @"enamel|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"険", @"mind|りっしんべん", @"small|ちいさい", @"sharp eyes|けわしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頼", @"excel|やさしい", @"trust|たのむ", @"mixture|こむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"覚", @"learn|おぼえる", @"effect|あかし", @"paper|かみ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"船", @"boat|ふね", @"machine|はた", @"margin|さす",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"途", @"way|--", @"most|もっとも", @"luck|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"許", @"way|--", @"rule|--", @"permit|ゆるす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"抜", @"excel|やさしい", @"omit|ぬく", @"earth|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"便", @"tea|--", @"bird|--", @"convenience|たより",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"留", @"halt|とめる", @"hope|のぞむ", @"warp|へる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"罪", @"form|--", @"sin|つみ", @"mind|かみ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"努", @"deep|ふかい", @"toil|つとめる", @"series|つづく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"精", @"ghost|--", @"taste|あじ", @"time|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"散", @"kill|ころす", @"doctor|いやす", @"spend|ちる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"静", @"quiet|しず", @"season|そうろう", @"art|すべ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"婚", @"low|した", @"marriage|--", @"home|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"喜", @"tribe|--", @"full|みちる", @"rejoice|よろこぶ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"浮", @"float|うく", @"harm|--", @"wood|き",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"絶", @"sever|たえる", @"ray|ひかる", @"full|みちる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"幸", @"float|うく", @"fortune|さいわい", @"exertion|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"押", @"usage|たとえる", @"stop|おす", @"lean|まがる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"倒", @"wait|まつ", @"fall|たおれる", @"fix|きめる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"等", @"learn|ならう", @"etc.|ひとしい", @"offer|そなえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"老", @"what|なに", @"old age|おいる", @"one|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"曲", @"person|ひと", @"lean|まがる", @"rouse|おきる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"払", @"pay|はらう", @"winter|ふゆ", @"oneself|みずから",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"庭", @"yard|--", @"exert|--", @"meet|あつまる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"徒", @"duty|かかる", @"set|いたずら", @"rejoice|よろこぶ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勤", @"mixture|こむ", @"serve|つとめる", @"trust|たのむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遅", @"late|おくれる", @"anti-|そる", @"he|かれ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"居", @"plan|はかる", @"to be|いる", @"lend|かす",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雑", @"map|え", @"miscellaneous|まじえる", @"younger brother|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"招", @"strong|つよい", @"invite|まねく", @"finish|すむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"困", @"north|--", @"measure|--", @"annoyed|こまる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"欠", @"love|--", @"gap|あくび", @"exam|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"更", @"of course|さら", @"six|む", @"half|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"刻", @"fire|はなす", @"moon|--", @"chop|きざむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"賛", @"feeling|--", @"color|--", @"praise|たすける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"抱", @"hug|だく", @"USA|こめ", @"change|ころがる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"犯", @"pour|そそぐ", @"sin|おかす", @"chase|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"恐", @"sit|すわる", @"have|--", @"awe|おそれる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"息", @"sketch|--", @"rain|あめ", @"son|いき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遠", @"silver|--", @"far|--", @"room|むろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"戻", @"greed|ほっする", @"re-|もどす", @"0.1|あう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"願", @"vow|ねがう", @"serve|つとめる", @"palace|やかた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"絵", @"sketch|--", @"big brother|--", @"far|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"越", @"exceed|こす", @"mouth|くち", @"sell|うる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"欲", @"going|いく", @"sketch|--", @"greed|ほっする",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"痛", @"hurt|いたい", @"up|うえ", @"law|ほど",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"笑", @"eye|め", @"laugh|わらう", @"ten thousand|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"互", @"living|いきる", @"together|たがい", @"late|おくれる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"束", @"of course|さら", @"ream|たば", @"exert|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"似", @"pour|そそぐ", @"face|おも", @"imitate|にる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"列", @"flee|にげる", @"branch|しんよう", @"row|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"探", @"war|--", @"gold|かね", @"grope|さぐる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"逃", @"flee|にげる", @"together|たがい", @"balance|のこる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遊", @"play|あそぶ", @"need|--", @"field|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"迷", @"west|--", @"err|まよう", @"idea|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夢", @"dream|ゆめ", @"war|--", @"person|かた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"君", @"east|--", @"old boy|きみ", @"mixing|まじわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"閉", @"enamel|--", @"name|な", @"shut|とじる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"緒", @"age|とし", @"end|お", @"judge|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"折", @"miscellaneous|まじえる", @"ghost|--", @"bend|おる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"草", @"back|せ", @"hug|だく", @"weeds|くさ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"暮", @"elder sister|あね", @"spend time|くれる", @"seven|なな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"酒", @"big brother|--", @"sake|さけ", @"earth|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"悲", @"tea|--", @"sad|かなしい", @"rumor|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"晴", @"ball|--", @"clear up|はれる", @"he|かれ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"掛", @"live|すむ", @"to be|いる", @"tax|かける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"到", @"item|さけぶ", @"car|--", @"reach|いたる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寝", @"country|--", @"I|あらかじめ", @"bed|ねる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"暗", @"shrink|--", @"late|おくれる", @"shade|くらい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"盗", @"rob|ぬすむ", @"yard|--", @"younger brother|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"吸", @"fix|ただちに", @"want|もとめる", @"sip|すう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"陽", @"learn|おぼえる", @"male|--", @"game|まわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"御", @"task|--", @"fee|--", @"govern|おん",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歯", @"make|つくる", @"walk|あるく", @"cog|よわい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"忘", @"delude|ばける", @"forget|わすれる", @"tip|すえ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雪", @"fix|さだめる", @"take|のむ", @"snow|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"吹", @"shop|みせ", @"hundred|--", @"puff|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"娘", @"set|いたずら", @"girl|むすめ", @"seven|なな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"誤", @"road|じ", @"err|あやまる", @"sex|さが",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"洗", @"big|おお", @"wash|--", @"ask|きく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"慣", @"truth|--", @"accustomed|なれる", @"consider|かんがえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"礼", @"all|まったく", @"enamel|--", @"bow|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"窓", @"pane|まど", @"low|した", @"color|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昔", @"most|もっとも", @"head|あたま", @"antiquity|むかし",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"貧", @"fly|とぶ", @"poor|まずしい", @"judge|--",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"怒", @"mountain|--", @"blame|せめる", @"angry|いかる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"泳", @"news|むくいる", @"swim|およぐ", @"table|おもて",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"祖", @"field|--", @"want|もとめる", @"pioneer|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"杯", @"glass|さかずき", @"faith|おしえる", @"four|よ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"疲", @"outside|そと", @"winter|ふゆ", @"tire|つかれる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"皆", @"hit|あたる", @"map|え", @"all|みな",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"鳴", @"back|のち", @"six|む", @"cry|なく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"腹", @"bend|おる", @"shop|--", @"belly|はら",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"煙", @"firm|--", @"smoke|けむる", @"back|せ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"眠", @"home|いえ", @"mouth|くち", @"die|ねむる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"怖", @"wife|--", @"fearful|こわい", @"lend|かす",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"耳", @"black|くろ", @"ear|--", @"side|きわ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頂", @"top|いただく", @"finger|ゆび", @"because|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"箱", @"inn|やど", @"body|からだ", @"bin|はこ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"晩", @"night|--", @"love|--", @"visit|おとずれる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寒", @"cold|--", @"ask|きく", @"hand|て",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"髪", @"look|みる", @"die|ねむる", @"hair of the head|--",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"忙", @"busy|いそがしい", @"study|--", @"give|あたえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"才", @"lord|ぬし", @"genius|--", @"get|うける",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"靴", @"shoes|くつ", @"bin|はこ", @"bend|おる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"恥", @"shame|はじる", @"what|なに", @"shrink|--",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"偶", @"leg|あし", @"couple|たま", @"mama|はは",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"偉", @"lend|かす", @"famous|--", @"drop|おちる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"猫", @"serve|つとめる", @"cat|ねこ", @"dying|ない",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"幾", @"how far|いく", @"judge|--", @"hit|あたる",@"1", nil]];
}

- (void) userStart
{
	userProgress = 1;
	userContentRecords = [[NSMutableArray alloc] init];
}


- (void) userSaveRecord :(int)location :(float)record
{
	NSLog(@"> Save  | Saved Record: %f", record);
	[userContentRecords addObject:[NSArray arrayWithObjects: [NSString stringWithFormat:@"%d",location], [NSString stringWithFormat:@"%f",record], nil]];
}



- (void) userReset
{
	NSLog(@"> Reset | Reset User Records");
	userContentRecords = [[NSMutableArray alloc] init];
	[userContentRecords addObject:[NSArray arrayWithObjects: @"1",@"1",nil]];
	self.interfaceMenuProgress.text = @"Press \"Next\" to begin";
	[self gameFinish];
	[self userStart];
}

@end