//
//  xxiivvViewController.m
//  nijuniju
//
//  Created by Devine Lu Linvega on 2013-08-06.
//  Copyright (c) 2013 XXIIVV. All rights reserved.
//

#import "xxiivvViewController.h"
#import <QuartzCore/QuartzCore.h>

@implementation xxiivvViewController (Modules)

- (void) nodeStart
{
	nodeContentArray = [[NSMutableArray alloc] init];
	
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"日", @"sun|ひ", @"one|ひと", @"ten|とお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"一", @"one|ひと", @"year|ネン", @"two|ふた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"国", @"ten|とお", @"person|ひと", @"country|コク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"人", @"inside|なか", @"country|コク", @"person|ひと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"年", @"person|ひと", @"year|ネン", @"hour|とき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"大", @"ten|とお", @"three|み", @"big|おお",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"十", @"long|ながい", @"ten|とお", @"one|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"二", @"person|ひと", @"three|み", @"two|ふた",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"本", @"going|いく", @"book|ホン", @"one|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"中", @"exit|でる", @"inside|なか", @"see|みる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"長", @"long|ながい", @"inside|なか", @"person|ひと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"出", @"hour|とき", @"exit|でる", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"三", @"three|み", @"going|いく", @"ten|とお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"時", @"three|み", @"hour|とき", @"going|いく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"行", @"two|ふた", @"life|いきる", @"going|いく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"見", @"hour|とき", @"see|みる", @"one|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"月", @"inside|なか", @"moon|ゲツ", @"space|あいだ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"後", @"inside|なか", @"one|ひと", @"back|のち",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"前", @"before|まえ", @"gold|かね", @"long|ながい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"生", @"big|おお", @"four|よ", @"life|いきる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"五", @"country|コク", @"above|うえ", @"five|いつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"間", @"space|あいだ", @"gold|かね", @"ten|とお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"上", @"one|ひと", @"study|ガク", @"above|うえ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"東", @"high|たかい", @"east|トウ", @"inside|なか",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"四", @"country|コク", @"four|よ", @"enter|いる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"今", @"year|ネン", @"now|コン", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"金", @"gold|かね", @"exit|でる", @"now|コン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"九", @"gold|かね", @"nine|ここの", @"three|み",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"入", @"study|ガク", @"enter|いる", @"east|トウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"学", @"child|こ", @"study|ガク", @"exit|でる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"高", @"above|うえ", @"two|ふた", @"high|たかい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"円", @"gold|かね", @"yen|まるい", @"come|くる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"子", @"six|む", @"talk|はなす", @"child|こ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"外", @"exit|でる", @"outside|そと", @"moon|ゲツ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"八", @"three|み", @"enter|いる", @"eight|や",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"六", @"six|む", @"high|たかい", @"east|トウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"下", @"low|した", @"year|ネン", @"gold|かね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"来", @"come|くる", @"small|ちいさい", @"gold|かね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"気", @"write|かく", @"spirit|いき", @"country|コク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"小", @"small|ちいさい", @"hundred|ヒャク", @"country|コク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"七", @"seven|なな", @"big|おお", @"book|ホン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"山", @"six|む", @"nine|ここの", @"mountain|サン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"話", @"talk|はなす", @"river|セン", @"six|む",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"女", @"child|こ", @"inside|なか", @"woman|おんな",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"北", @"hour|とき", @"woman|おんな", @"north|ホク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"午", @"eight|や", @"noon|うま", @"two|ふた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"百", @"hundred|ヒャク", @"long|ながい", @"exit|でる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"書", @"ten|とお", @"hour|とき", @"write|かく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"先", @"life|いきる", @"gold|かね", @"before|さき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"名", @"name|な", @"thousand|セン", @"west|セイ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"川", @"name|な", @"river|セン", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"千", @"hundred|ヒャク", @"now|コン", @"thousand|セン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"水", @"three|み", @"six|む", @"water|みず",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"半", @"before|まえ", @"one|ひと", @"half|ハン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"男", @"male|おとこ", @"come|くる", @"country|コク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"西", @"west|セイ", @"space|あいだ", @"before|まえ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"電", @"thousand|セン", @"study|ガク", @"electricity|デン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"校", @"exam|コウ", @"country|コク", @"west|セイ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"語", @"talk|はなす", @"speech|かたる", @"eight|や",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"土", @"gold|かね", @"soil|ド", @"now|コン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"木", @"yen|まるい", @"back|のち", @"wood|き",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"聞", @"before|まえ", @"ask|きく", @"write|かく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"食", @"eat|くう", @"before|さき", @"thousand|セン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"車", @"right|ウ", @"car|シャ", @"male|おとこ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"何", @"what|なに", @"eight|や", @"thousand|セン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"南", @"south|ナン", @"speech|かたる", @"mama|はは",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"万", @"10000|マン", @"east|トウ", @"hundred|ヒャク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"毎", @"river|セン", @"three|み", @"every|ごと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"白", @"white|しろ", @"above|うえ", @"exit|でる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"天", @"friend|ユウ", @"sky|あまつ", @"seven|なな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"母", @"above|うえ", @"hundred|ヒャク", @"mama|はは",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"火", @"gold|かね", @"half|ハン", @"fire|ひ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"右", @"right|ウ", @"study|ガク", @"person|ひと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"読", @"four|よ", @"read|よむ", @"high|たかい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"友", @"friend|ユウ", @"talk|はなす", @"life|いきる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"左", @"ten|とお", @"left|サ", @"woman|おんな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"休", @"five|いつ", @"ask|きく", @"rest|やすむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"父", @"before|まえ", @"rest|やすむ", @"father|ちち",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雨", @"seven|なな", @"study|ガク", @"rain|あめ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"会", @"meet|あう", @"thousand|セン", @"write|かく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"同", @"same|おなじ", @"river|セン", @"come|くる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"事", @"friend|ユウ", @"fact|こと", @"fire|ひ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"自", @"oneself|みずから", @"stand up|たつ", @"eat|くう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"社", @"firm|シャ", @"moon|ゲツ", @"car|シャ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"発", @"emit|たつ", @"place|ば", @"exit|でる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"者", @"person|もの", @"before|まえ", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"地", @"before|さき", @"earth|チ", @"country|コク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"業", @"stand up|たつ", @"water|みず", @"arts|ギョウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"方", @"book|ホン", @"back|のち", @"person|かた",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"新", @"new|あたらしい", @"emit|たつ", @"male|おとこ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"場", @"emit|たつ", @"above|うえ", @"place|ば",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"員", @"member|イ", @"space|あいだ", @"four|よ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"立", @"see|みる", @"low|した", @"stand up|たつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"開", @"open|ひらく", @"before|まえ", @"four|よ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"手", @"exam|コウ", @"hand|て", @"water|みず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"力", @"oneself|みずから", @"enter|いる", @"exert|リョク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"問", @"ask|とう", @"rain|あめ", @"seven|なな",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"代", @"high|たかい", @"age|かわる", @"three|み",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"明", @"light|あかり", @"person|ひと", @"exert|リョク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"動", @"study|ガク", @"move|うごく", @"before|さき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"京", @"river|セン", @"capital|キョウ", @"see|みる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"目", @"mama|はは", @"back|のち", @"eye|め",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"通", @"avenue|とおる", @"friend|ユウ", @"eye|め",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"言", @"say|いう", @"spirit|いき", @"thousand|セン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"理", @"truth|リ", @"oneself|みずから", @"speech|かたる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"体", @"ask|とう", @"prince|コウ", @"body|からだ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"田", @"eye|め", @"father|ちち", @"rice paddy|デン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"主", @"three|み", @"lord|ぬし", @"water|みず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"題", @"capital|キョウ", @"book|ホン", @"topic|ダイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"意", @"nine|ここの", @"think|おもう", @"mind|",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"不", @"bad|フ", @"south|ナン", @"topic|ダイ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"作", @"rice paddy|デン", @"make|つくる", @"north|ホク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"用", @"two|ふた", @"body|からだ", @"use|ヨウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"度", @"rice paddy|デン", @"nine|ここの", @"time|たび",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"強", @"topic|ダイ", @"rice paddy|デン", @"strong|つよい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"公", @"fire|ひ", @"prince|コウ", @"soil|ド",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"持", @"nine|ここの", @"have|もつ", @"water|みず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"野", @"field|の", @"two|ふた", @"mountain|サン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"以", @"rest|やすむ", @"because|イ", @"hundred|ヒャク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"思", @"right|ウ", @"think|おもう", @"ten|とお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"家", @"left|サ", @"home|いえ", @"what|なに",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"世", @"going|いく", @"high|たかい", @"world|よ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"多", @"long|ながい", @"much|おおい", @"low|やすい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"正", @"justice|ただしい", @"male|おとこ", @"book|ホン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"安", @"one|ひと", @"low|やすい", @"place|ば",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"院", @"Inst.|イン", @"picture|えがく", @"use|ヨウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"心", @"enter|いる", @"now|コン", @"mind|りっしんべん",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"界", @"justice|ただしい", @"world|カイ", @"river|セン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"教", @"white|しろ", @"faith|おしえる", @"Inst.|イン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"文", @"art|ふみ", @"book|ホン", @"meet|あう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"元", @"art|ふみ", @"fire|ひ", @"origin|ゲン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"重", @"art|ふみ", @"think|おもう", @"-fold|え",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"近", @"north|ホク", @"home|いえ", @"akin|キン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"考", @"consider|かんがえる", @"write|かく", @"-fold|え",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"画", @"friend|ユウ", @"picture|えがく", @"time|たび",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"海", @"three|み", @"sea|カイ", @"faith|おしえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"売", @"sell|うる", @"prince|コウ", @"now|コン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"知", @"justice|ただしい", @"topic|ダイ", @"know|しる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"道", @"moral|ドウ", @"one|ひと", @"avenue|とおる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"集", @"meet|あつまる", @"faith|おしえる", @"inside|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"別", @"body|からだ", @"fork|わかれる", @"die|しぬ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"物", @"sea|カイ", @"thing|もの", @"emit|たつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"使", @"west|セイ", @"use|つかう", @"justice|ただしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"品", @"read|よむ", @"goods|しな", @"country|コク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"計", @"plan|はかる", @"enter|いる", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"死", @"die|しぬ", @"strong|つよい", @"inside|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"特", @"prince|コウ", @"special|トク", @"hundred|ヒャク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"私", @"I|わたくし", @"west|セイ", @"prince|コウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"始", @"plan|はかる", @"bad|フ", @"begin|はじめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"朝", @"stand up|たつ", @"wood|き", @"epoch|チョウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"運", @"lot|はこぶ", @"one|ひと", @"wood|き",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"終", @"end|おわる", @"car|シャ", @"truth|リ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"台", @"stand up|たつ", @"a stand|うてな", @"left|サ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"広", @"begin|はじめる", @"wide|ひろい", @"say|いう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"住", @"woman|おんな", @"a stand|うてな", @"live|すむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"真", @"true|ま", @"mouth|くち", @"gold|かね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"有", @"lord|ぬし", @"have|ユウ", @"low|した",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"口", @"mouth|くち", @"now|コン", @"long|ながい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"少", @"person|かた", @"mountain|サン", @"few|すくない",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"町", @"town|まち", @"year|ネン", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"料", @"oneself|みずから", @"fee|リョウ", @"leg|あし",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"工", @"say|いう", @"north|ホク", @"craft|コウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"建", @"build|たてる", @"picture|えがく", @"akin|キン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"空", @"send|おくる", @"mama|はは", @"sky|そら",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"急", @"topic|ダイ", @"truth|リ", @"steep|いそぐ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"止", @"halt|とまる", @"thousand|セン", @"mouth|くち",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"送", @"low|した", @"know|しる", @"send|おくる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"切", @"I|わたくし", @"have|もつ", @"cut|きる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"転", @"field|の", @"seven|なな", @"change|ころがる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"研", @"origin|ゲン", @"polish|ケン", @"big|おお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"足", @"rouse|おきる", @"leg|あし", @"emit|たつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"究", @"study|キュウ", @"read|よむ", @"wait|まつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"楽", @"open|ひらく", @"sell|うる", @"ease|たのしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"起", @"rouse|おきる", @"mind|りっしんべん", @"don|きる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"着", @"don|きる", @"east|トウ", @"polish|ケン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"店", @"plan|はかる", @"shop|みせ", @"going|いく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"病", @"plan|はかる", @"ill|やむ", @"car|シャ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"質", @"much|おおい", @"matter|たち", @"doctor|いやす",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"待", @"wait|まつ", @"arts|ギョウ", @"reflect|うつる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"試", @"sky|そら", @"try|こころみる", @"south|ナン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"族", @"consider|かんがえる", @"gold|かね", @"tribe|ゾ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"銀", @"silver|ギン", @"above|うえ", @"effect|あかし",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"早", @"fast|はやい", @"leg|あし", @"make|つくる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"映", @"reflect|うつる", @"mind|りっしんべん", @"earth|チ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"親", @"space|あいだ", @"end|おわる", @"parent|おや",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"験", @"enter|いる", @"sell|うる", @"effect|あかし",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"英", @"English|エイ", @"every|ごと", @"pour|そそぐ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"医", @"speech|かたる", @"every|ごと", @"doctor|いやす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"仕", @"doing|つかえる", @"mind|", @"use|つかう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"去", @"akin|キン", @"sell|うる", @"past|さる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"味", @"time|たび", @"child|こ", @"taste|あじ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"写", @"sky|そら", @"mama|はは", @"copy|うつす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"字", @"word|あざ", @"tribe|ゾ", @"know|しる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"答", @"think|おもう", @"long|ながい", @"answer|こたえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夜", @"same|おなじ", @"three|み", @"night|よ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"音", @"fact|こと", @"nine|ここの", @"noise|おと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"注", @"fork|わかれる", @"pour|そそぐ", @"outside|そと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"帰", @"going|いく", @"lead to|かえる", @"before|さき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"古", @"doing|つかえる", @"enter|いる", @"old|ふるい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歌", @"eye|め", @"sing|うた", @"akin|キン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"買", @"buy|かう", @"what|なに", @"reflect|うつる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"悪", @"friend|ユウ", @"pour|そそぐ", @"bad|わるい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"図", @"black|くろ", @"map|え", @"new|あたらしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"週", @"noise|おと", @"week|シュウ", @"river|セン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"室", @"move|うごく", @"room|むろ", @"sing|うた",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歩", @"walk|あるく", @"eight|や", @"outside|そと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"風", @"car|シャ", @"cut|きる", @"air|かぜ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"紙", @"paper|かみ", @"same|おなじ", @"oneself|みずから",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"黒", @"black|くろ", @"half|ハン", @"origin|ゲン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"花", @"flower|カ", @"moral|ドウ", @"cut|きる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"春", @"springtime|シュン", @"small|ちいさい", @"strong|つよい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"赤", @"exam|コウ", @"send|おくる", @"red|あか",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"青", @"blue|あお", @"English|エイ", @"half|ハン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"館", @"palace|やかた", @"arts|ギョウ", @"every|ごと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"屋", @"low|した", @"inside|なか", @"shop|オク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"色", @"color|ショク", @"age|かわる", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"走", @"a stand|うてな", @"I|わたくし", @"run|ソウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"秋", @"eat|くう", @"noise|おと", @"autumn|あき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夏", @"summer|なつ", @"strong|つよい", @"one|ひと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"習", @"exam|コウ", @"learn|ならう", @"one|ひと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"駅", @"rouse|おきる", @"west|セイ", @"station|エキ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"洋", @"die|しぬ", @"ten|とお", @"ocean|ヨ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"旅", @"before|まえ", @"trip|たび", @"open|ひらく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"服", @"obey|フ", @"use|ヨウ", @"mountain|サン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夕", @"sea|カイ", @"evening|セキ", @"because|イ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"借", @"exertion|ベン", @"rent|かりる", @"bad|フ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"曜", @"weekday|ヨ", @"try|こころみる", @"don|きる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飲", @"tribe|ゾ", @"enter|いる", @"take|のむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"肉", @"parent|おや", @"thing|もの", @"meat|ニク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"貸", @"I|わたくし", @"age|かわる", @"lend|かす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"堂", @"rent|かりる", @"hall|ドウ", @"write|かく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"鳥", @"bird|チョウ", @"new|あたらしい", @"fast|はやい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飯", @"stand up|たつ", @"meal|ハン", @"special|トク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勉", @"lord|ぬし", @"exertion|ベン", @"flower|カ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"冬", @"bad|わるい", @"winter|ふゆ", @"matter|たち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昼", @"don|きる", @"noon|ひる", @"thing|もの",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"茶", @"small|ちいさい", @"before|さき", @"tea|チャ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"弟", @"I|わたくし", @"younger brother|テイ", @"strong|つよい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"牛", @"book|ホン", @"cow|ギュウ", @"hour|とき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"魚", @"ten|とお", @"fish|うお", @"lead to|かえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"兄", @"see|みる", @"big brother|ケイ", @"word|あざ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"犬", @"dog|いぬ", @"mouth|くち", @"yen|まるい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"妹", @"west|セイ", @"palace|やかた", @"younger sister|マイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"姉", @"body|からだ", @"elder sister|あね", @"avenue|とおる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"漢", @"China|カ", @"wide|ひろい", @"earth|チ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"政", @"akin|キン", @"politics|まつりごと", @"word|あざ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"議", @"prince|コウ", @"debate|", @"north|ホク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"民", @"have|ユウ", @"nation|ミン", @"study|キュウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"連", @"lead|つらなる", @"talk|はなす", @"flower|カ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"対", @"even|あいて", @"four|よ", @"much|おおい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"部", @"lead|つらなる", @"dept|ブ", @"thing|もの",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"合", @"paper|かみ", @"0.1|あう", @"year|ネン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"市", @"city|シ", @"eat|くう", @"fish|うお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"内", @"truth|み", @"home|いえ", @"home|ナイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"相", @"send|おくる", @"phase|あい", @"say|いう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"定", @"book|ホン", @"fix|さだめる", @"lead|つらなる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"回", @"exam|コウ", @"game|まわる", @"politics|まつりごと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"選", @"evening|セキ", @"truth|リ", @"elect|えらぶ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"米", @"springtime|シュン", @"USA|こめ", @"before|さき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"実", @"friend|ユウ", @"thousand|セン", @"truth|み",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"関", @"prince|コウ", @"barrier|せき", @"all|まったく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"決", @"member|イ", @"try|こころみる", @"fix|きめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"全", @"evening|セキ", @"few|すくない", @"all|まったく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"表", @"rouse|おきる", @"-fold|え", @"table|おもて",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"戦", @"war|いくさ", @"because|イ", @"stand up|たつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"経", @"rent|かりる", @"warp|へる", @"winter|ふゆ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"最", @"eight|や", @"most|もっとも", @"before|さき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"現", @"soil|ド", @"actual|あらわれる", @"eight|や",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"調", @"big|おお", @"tone|しらべる", @"hour|とき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"化", @"flower|カ", @"delude|ばける", @"earth|チ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"当", @"hall|ドウ", @"hit|あたる", @"because|イ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"約", @"open|ひらく", @"shrink|ヤク", @"oneself|みずから",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"首", @"neck|シュ", @"matter|たち", @"rouse|おきる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"法", @"send|おくる", @"origin|ゲン", @"law|ホウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"性", @"know|しる", @"hit|あたる", @"sex|さが",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"要", @"need|ヨウ", @"south|ナン", @"hand|て",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"制", @"law|セイ", @"lord|ぬし", @"origin|ゲン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"治", @"ill|やむ", @"govt|おさめる", @"silver|ギン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"務", @"ill|やむ", @"going|いく", @"task|ム",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"成", @"peace|やわらぐ", @"get|なる", @"use|つかう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"期", @"bird|チョウ", @"time|キ", @"epoch|チョウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"取", @"take|とる", @"emit|たつ", @"now|コン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"都", @"capital|ト", @"electricity|デン", @"shop|オク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"和", @"much|おおい", @"before|まえ", @"peace|やわらぐ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"機", @"machine|はた", @"truth|み", @"bird|チョウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"平", @"flat|たいら", @"justice|ただしい", @"fork|わかれる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"加", @"know|しる", @"add|くわえる", @"electricity|デン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"受", @"get|うける", @"bad|わるい", @"meal|ハン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"続", @"series|つづく", @"arts|ギョウ", @"walk|あるく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"進", @"rouse|おきる", @"bird|チョウ", @"proceed|すすむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"数", @"proceed|すすむ", @"law|かず", @"mountain|サン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"記", @"before|さき", @"scribe|キ", @"yen|まるい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"初", @"beginning|はじめ", @"tone|しらべる", @"word|あざ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"指", @"stand up|たつ", @"outside|そと", @"finger|ゆび",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"権", @"meet|あつまる", @"few|すくない", @"power|おもり",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"支", @"wood|き", @"field|ゲン", @"branch|しんよう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"産", @"person|もの", @"news|むくいる", @"bear|うむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"点", @"lend|かす", @"air|かぜ", @"mark|つける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"報", @"younger brother|テイ", @"lead|つらなる", @"news|むくいる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"済", @"strong|つよい", @"exam|コウ", @"finish|すむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"活", @"above|うえ", @"living|いきる", @"govt|おさめる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"原", @"fact|こと", @"mama|はは", @"field|ゲン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"共", @"exertion|ベン", @"rice paddy|デン", @"all|とも",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"得", @"avenue|とおる", @"get|える", @"flat|たいら",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"解", @"bear|うむ", @"10000|マン", @"key|とく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"交", @"govt|おさめる", @"mixing|まじわる", @"justice|ただしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"資", @"data|", @"epoch|チョウ", @"tribe|ゾ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"予", @"paper|かみ", @"nine|ここの", @"I|あらかじめ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"向", @"left|サ", @"defy|むく", @"study|ガク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"際", @"sky|あまつ", @"right|ウ", @"side|きわ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勝", @"tribe|ゾ", @"add|くわえる", @"win|かつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"面", @"task|ム", @"barrier|せき", @"face|おも",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"告", @"ten|とお", @"all|とも", @"tell|コク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"反", @"life|いきる", @"flat|たいら", @"anti-|そる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"判", @"seal|わかる", @"six|む", @"person|かた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"認", @"eat|くう", @"witness|みとめる", @"winter|ふゆ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"参", @"field|の", @"die|まいる", @"finish|すむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"利", @"exit|でる", @"profit|リ", @"shop|みせ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"組", @"big|おお", @"goods|しな", @"braid|くむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"信", @"truth|シ", @"braid|くむ", @"weekday|ヨ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"在", @"news|むくいる", @"speech|かたる", @"exist|ザイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"件", @"life|いきる", @"case|くだん", @"face|おも",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"側", @"war|いくさ", @"mama|はは", @"lean|かわ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"任", @"answer|こたえる", @"woman|おんな", @"duty|まかせる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"引", @"anti-|そる", @"topic|ダイ", @"tug|ひく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"求", @"epoch|チョウ", @"want|もとめる", @"doing|つかえる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"所", @"craft|コウ", @"going|いく", @"place|ところ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"次", @"country|コク", @"two|ふた", @"next|つぐ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昨", @"previous|サク", @"north|ホク", @"finger|ゆび",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"論", @"task|ム", @"argument|ロン", @"obey|フ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"官", @"big|おお", @"bureaucrat|カン", @"room|むろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"増", @"add|ます", @"country|コク", @"tribe|ゾ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"係", @"use|ヨウ", @"hour|とき", @"duty|かかる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"感", @"enter|いる", @"feeling|カン", @"father|ちち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"情", @"cow|ギュウ", @"answer|こたえる", @"facts|なさけ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"投", @"buy|かう", @"new|あたらしい", @"join|なげる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"示", @"show|しめす", @"build|たてる", @"book|ホン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"変", @"change|かわる", @"tea|チャ", @"flat|たいら",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"打", @"USA|こめ", @"die|しぬ", @"hit|うつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"直", @"I|わたくし", @"thing|もの", @"fix|ただちに",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"両", @"true|ま", @"two|てる", @"silver|ギン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"式", @"time|キ", @"rite|シ", @"study|ガク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"確", @"body|からだ", @"world|カイ", @"firm|たしか",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"果", @"autumn|あき", @"need|ヨウ", @"end|はたす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"容", @"arts|ギョウ", @"form|ヨウ", @"read|よむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"必", @"certain|かならず", @"inside|なか", @"flat|たいら",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"演", @"mouth|くち", @"younger sister|マイ", @"act|エン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歳", @"high|たかい", @"age|とし", @"autumn|あき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"争", @"argue|あらそう", @"north|ホク", @"moon|ゲツ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"談", @"talk|ダン", @"noon|うま", @"tribe|ゾ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"能", @"skill|ノウ", @"politics|まつりごと", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"位", @"send|おくる", @"politics|まつりごと", @"some|くらい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"置", @"Inst.|イン", @"mind|", @"put|おく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"流", @"because|イ", @"book|ホン", @"flow|ながれる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"格", @"fix|さだめる", @"law|かず", @"rank|カク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"疑", @"doubt|うたがう", @"emit|たつ", @"use|ヨウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"過", @"faith|おしえる", @"error|すぎる", @"father|ちち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"局", @"board|つぼね", @"picture|えがく", @"some|くらい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"放", @"fire|はなす", @"life|いきる", @"law|ホウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"常", @"male|おとこ", @"usual|つね", @"live|すむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"状", @"politics|まつりごと", @"small|ちいさい", @"form|ジョウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"球", @"previous|サク", @"old|ふるい", @"ball|キュウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"職", @"speech|かたる", @"work|ショク", @"room|むろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"与", @"ill|やむ", @"younger brother|テイ", @"give|あたえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"供", @"law|セイ", @"offer|そなえる", @"mind|",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"役", @"strong|つよい", @"stand up|たつ", @"war|ヤク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"構", @"make|つくる", @"build|かまえる", @"law|かず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"割", @"get|える", @"cut|わる", @"facts|なさけ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"費", @"cost|ついやす", @"lead|つらなる", @"electricity|デン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"付", @"fire|ひ", @"attach|つける", @"duty|まかせる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"由", @"a reason|よし", @"end|おわる", @"need|ヨウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"説", @"three|み", @"rouse|おきる", @"rumor|セツ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"難", @"epoch|チョウ", @"truth|リ", @"defect|かたい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"優", @"old|ふるい", @"task|ム", @"excel|やさしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夫", @"outside|そと", @"ask|きく", @"man|おっと",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"収", @"consider|かんがえる", @"pay|おさめる", @"sell|うる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"断", @"mixing|まじわる", @"answer|こたえる", @"warn|たつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"石", @"three|み", @"phase|あい", @"stone|セキ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"違", @"differ|ちがう", @"see|みる", @"act|エン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"消", @"taste|あじ", @"two|てる", @"cancel|きえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"神", @"exam|コウ", @"mind|かみ", @"obey|フ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"番", @"warp|へる", @"warn|たつ", @"turn|バン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"規", @"write|かく", @"measure|", @"game|まわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"術", @"facts|なさけ", @"art|すべ", @"spirit|いき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"備", @"sing|うた", @"equip|そなえる", @"dog|いぬ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"宅", @"ocean|ヨ", @"home|タ", @"say|いう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"害", @"measure|", @"harm|ガイ", @"sex|さが",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"配", @"exile|くばる", @"shop|オク", @"-fold|え",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"警", @"admonish|いましめる", @"fire|はなす", @"argument|ロン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"育", @"end|はたす", @"field|の", @"rear|そだつ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"席", @"person|ひと", @"winter|ふゆ", @"mat|むしろ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"訪", @"visit|おとずれる", @"color|ショク", @"lead to|かえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"乗", @"ill|やむ", @"mountain|サン", @"join|のる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"残", @"exit|でる", @"error|すぎる", @"balance|のこる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"想", @"idea|おもう", @"home|いえ", @"wait|まつ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"声", @"voice|こえ", @"tell|コク", @"person|かた",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"念", @"shrink|ヤク", @"idea|ネン", @"bad|わるい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"助", @"sell|うる", @"help|たすける", @"walk|あるく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"労", @"year|ネン", @"toil|ろうする", @"same|おなじ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"例", @"night|よ", @"time|キ", @"usage|たとえる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"然", @"lean|かわ", @"art|ふみ", @"so|しか",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"限", @"limit|かぎる", @"flower|カ", @"argument|ロン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"追", @"duty|かかる", @"chase|ツイ", @"prince|コウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"商", @"person|ひと", @"walk|あるく", @"selling|ショウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"葉", @"obey|フ", @"taste|あじ", @"lobe|ヨウ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"伝", @"cost|ついやす", @"scribe|キ", @"follow|つたわる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"働", @"work|はたらく", @"leg|あし", @"walk|あるく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"形", @"small|ちいさい", @"left|サ", @"form|かた",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"景", @"air|かぜ", @"admonish|いましめる", @"view|ケ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"落", @"drop|おちる", @"room|むろ", @"equip|そなえる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"好", @"key|とく", @"oneself|みずから", @"fond|このむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"退", @"repel|しりぞく", @"doubt|うたがう", @"leg|あし",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頭", @"head|あたま", @"phase|あい", @"woman|おんな",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"負", @"faith|おしえる", @"consider|かんがえる", @"-|まける",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"渡", @"data|", @"elder sister|あね", @"ford|わたる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"失", @"loss|うしなう", @"eight|や", @"finger|ゆび",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"差", @"person|ひと", @"margin|さす", @"help|たすける",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"末", @"cut|わる", @"tip|すえ", @"beginning|はじめ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"守", @"before|まえ", @"dog|いぬ", @"obey|まもる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"若", @"don|きる", @"I|あらかじめ", @"if|わかい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"種", @"sell|うる", @"kind|たね", @"home|タ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"美", @"craft|コウ", @"beauty|ビ", @"mountain|サン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"命", @"war|いくさ", @"visit|おとずれる", @"life|いのち",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"福", @"elect|えらぶ", @"noon|ひる", @"luck|フ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"望", @"hope|のぞむ", @"ask|きく", @"usual|つね",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"非", @"fire|はなす", @"un-|あらず", @"mouth|くち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"観", @"anti-|そる", @"look|みる", @"certain|かならず",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"察", @"judge|サツ", @"summer|なつ", @"next|つぐ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"段", @"ease|たのしい", @"steps|ダン", @"blue|あお",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"横", @"selling|ショウ", @"side|よこ", @"limit|かぎる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"深", @"deep|ふかい", @"hand|て", @"ask|とう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"申", @"3-5PM|もうす", @"selling|ショウ", @"before|まえ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"様", @"east|トウ", @"art|すべ", @"way|さま",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"財", @"world|よ", @"selling|ショウ", @"money|ザイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"港", @"harbor|みなと", @"above|うえ", @"doctor|いやす",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"識", @"elder sister|あね", @"left|サ", @"know|シ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"呼", @"tea|チャ", @"call|コ", @"sea|カイ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"達", @"age|かわる", @"reach|タツ", @"tell|コク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"良", @"good|よい", @"act|エン", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"候", @"offer|そなえる", @"parent|おや", @"season|そうろう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"程", @"3-5PM|もうす", @"going|いく", @"law|ほど",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"満", @"origin|ゲン", @"full|みちる", @"mat|むしろ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"敗", @"craft|コウ", @"defeat|やぶれる", @"toil|ろうする",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"値", @"eight|や", @"a reason|よし", @"cost|ね",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"突", @"stab|つく", @"weekday|ヨ", @"luck|フ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"光", @"color|ショク", @"ray|ひかる", @"act|エン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"路", @"road|じ", @"side|よこ", @"some|くらい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"科", @"course|", @"luck|フ", @"lobe|ヨウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"積", @"stack|つむ", @"mind|かみ", @"rain|あめ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"他", @"other|ほか", @"moon|ゲツ", @"warp|へる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"処", @"act|ところ", @"springtime|シュン", @"branch|しんよう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"太", @"mind|りっしんべん", @"thick|ふとい", @"fix|ただちに",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"客", @"arts|ギョウ", @"guest|キャク", @"facts|なさけ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"否", @"know|しる", @"evening|セキ", @"no|いな",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"師", @"lead to|かえる", @"talk|はなす", @"war|",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"登", @"ten|とお", @"cut|わる", @"ascend|のぼる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"易", @"series|つづく", @"easy|やさしい", @"ask|とう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"速", @"fast|はやい", @"war|ヤク", @"meal|ハン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"存", @"make|つくる", @"feel|ソン", @"prince|コウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"飛", @"fly|とぶ", @"kill|ころす", @"beauty|ビ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"殺", @"key|とく", @"beginning|はじめ", @"kill|ころす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"号", @"before|さき", @"item|さけぶ", @"living|いきる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"単", @"one|ひとえ", @"game|まわる", @"fork|わかれる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"座", @"have|ユウ", @"ill|やむ", @"sit|すわる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"破", @"finger|ゆび", @"Inst.|イン", @"rip|やぶる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"除", @"3)|のぞく", @"mat|むしろ", @"speech|かたる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"完", @"ascend|のぼる", @"shop|みせ", @"end|カン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"降", @"halt|とまる", @"next|つぐ", @"fall|おりる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"責", @"special|トク", @"blame|せめる", @"course|",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"捕", @"autumn|あき", @"catch|とらえる", @"road|じ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"危", @"male|おとこ", @"fear|あぶない", @"finish|すむ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"給", @"wage|たまう", @"next|つぐ", @"effect|あかし",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"苦", @"no|いな", @"rite|シ", @"trial|くるしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"迎", @"phase|あい", @"meet|ゲイ", @"world|カイ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"園", @"get|うける", @"now|コン", @"yard|エン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"具", @"tool|そなえる", @"nine|ここの", @"guest|キャク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"辞", @"city|シ", @"beauty|ビ", @"word|やめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"因", @"blue|あお", @"cause|よる", @"China|カ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"馬", @"horse|うま", @"wood|き", @"he|かれ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"愛", @"join|のる", @"tribe|ゾ", @"love|アイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"富", @"low|した", @"enrich|とむ", @"doubt|うたがう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"彼", @"he|かれ", @"dying|ない", @"small|ちいさい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"未", @"before|まえ", @"change|ころがる", @"un-|いまだ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"舞", @"noise|おと", @"light|あかり", @"flit|まう",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"亡", @"yen|まるい", @"dying|ない", @"call|コ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"冷", @"cool|つめたい", @"taste|あじ", @"space|あいだ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"適", @"rare|かなう", @"going|いく", @"black|くろ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"婦", @"pour|そそぐ", @"wife|", @"east|トウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寄", @"send|よる", @"art|すべ", @"outside|そと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"込", @"stone|セキ", @"right|ウ", @"mixture|こむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"顔", @"elder sister|あね", @"duty|かかる", @"face|かお",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"類", @"3-5PM|もうす", @"English|エイ", @"kind|たぐい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"余", @"other|あまる", @"fix|ただちに", @"springtime|シュン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"王", @"study|ガク", @"rule|オウ", @"dog|いぬ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"返", @"politics|まつりごと", @"guest|キャク", @"fade|かえす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"妻", @"wife|サイ", @"item|さけぶ", @"ill|やむ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"背", @"certain|かならず", @"back|せ", @"soil|ド",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"熱", @"heat|ネツ", @"barrier|せき", @"strong|つよい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"宿", @"inn|やど", @"usage|たとえる", @"blame|せめる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"薬", @"meet|あう", @"offer|そなえる", @"enamel|ヤク",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"険", @"sing|うた", @"sharp eyes|けわしい", @"moon|ゲツ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頼", @"trust|たのむ", @"barrier|せき", @"year|ネン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"覚", @"learn|おぼえる", @"stack|つむ", @"avenue|とおる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"船", @"selling|ショウ", @"boat|ふね", @"arts|ギョウ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"途", @"rule|オウ", @"way|", @"sit|すわる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"許", @"repel|しりぞく", @"what|なに", @"permit|ゆるす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"抜", @"omit|ぬく", @"debate|", @"big|おお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"便", @"light|あかり", @"convenience|たより", @"call|コ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"留", @"halt|とめる", @"guest|キャク", @"three|み",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"罪", @"old|ふるい", @"moon|ゲツ", @"sin|つみ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"努", @"fear|あぶない", @"fire|はなす", @"toil|つとめる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"精", @"ghost|セイ", @"spirit|いき", @"fact|こと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"散", @"spend|ちる", @"study|ガク", @"cost|ついやす",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"静", @"quiet|しず", @"sell|うる", @"every|ごと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"婚", @"home|タ", @"fire|ひ", @"marriage|コン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"喜", @"half|ハン", @"rejoice|よろこぶ", @"war|いくさ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"浮", @"float|うく", @"law|セイ", @"case|くだん",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"絶", @"beginning|はじめ", @"sever|たえる", @"see|みる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"幸", @"fortune|さいわい", @"rule|オウ", @"father|ちち",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"押", @"person|ひと", @"stop|おす", @"time|たび",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"倒", @"doctor|いやす", @"fall|たおれる", @"sex|さが",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"等", @"exert|リョク", @"rite|シ", @"etc.|ひとしい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"老", @"ford|わたる", @"view|ケ", @"old age|おいる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"曲", @"lobe|ヨウ", @"lean|まがる", @"polish|ケン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"払", @"kill|ころす", @"pay|はらう", @"one|ひとえ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"庭", @"going|いく", @"horse|うま", @"yard|テイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"徒", @"defeat|やぶれる", @"two|ふた", @"set|いたずら",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"勤", @"change|ころがる", @"serve|つとめる", @"say|いう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遅", @"late|おくれる", @"mind|かみ", @"body|からだ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"居", @"to be|いる", @"reach|タツ", @"yen|まるい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雑", @"miscellaneous|まじえる", @"un-|いまだ", @"country|コク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"招", @"invite|まねく", @"rouse|おきる", @"float|うく",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"困", @"annoyed|こまる", @"cost|ね", @"law|ホウ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"欠", @"home|タ", @"gap|あくび", @"hundred|ヒャク",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"更", @"springtime|シュン", @"trust|たのむ", @"of course|さら",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"刻", @"late|おくれる", @"field|ゲン", @"chop|きざむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"賛", @"thing|もの", @"praise|たすける", @"noon|うま",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"抱", @"sing|うた", @"rest|やすむ", @"hug|だく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"犯", @"sin|おかす", @"limit|かぎる", @"lot|はこぶ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"恐", @"awe|おそれる", @"low|やすい", @"word|あざ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"息", @"four|よ", @"catch|とらえる", @"son|いき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遠", @"low|やすい", @"far|エン", @"mouth|くち",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"戻", @"seal|わかる", @"re-|もどす", @"change|ころがる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"願", @"mind|", @"vow|ねがう", @"all|まったく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"絵", @"home|いえ", @"sketch|カイ", @"outside|そと",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"越", @"home|タ", @"good|よい", @"exceed|こす",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"欲", @"proceed|すすむ", @"greed|ほっする", @"laugh|わらう",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"痛", @"hurt|いたい", @"English|エイ", @"un-|いまだ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"笑", @"truth|リ", @"laugh|わらう", @"no|いな",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"互", @"north|ホク", @"together|たがい", @"long|ながい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"束", @"loss|うしなう", @"silver|ギン", @"ream|たば",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"似", @"imitate|にる", @"cut|わる", @"learn|ならう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"列", @"because|イ", @"home|ナイ", @"row|レツ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"探", @"picture|えがく", @"polish|ケン", @"grope|さぐる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"逃", @"flee|にげる", @"form|ヨウ", @"effect|あかし",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"遊", @"play|あそぶ", @"topic|ダイ", @"age|かわる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"迷", @"err|まよう", @"key|とく", @"voice|こえ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"夢", @"witness|みとめる", @"night|よ", @"dream|ゆめ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"君", @"old boy|きみ", @"judge|サツ", @"face|かお",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"閉", @"fact|こと", @"shut|とじる", @"station|エキ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"緒", @"end|お", @"steep|いそぐ", @"trial|くるしい",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"折", @"etc.|ひとしい", @"bend|おる", @"sea|カイ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"草", @"weeds|くさ", @"old|ふるい", @"warp|へる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"暮", @"bear|うむ", @"spend time|くれる", @"ford|わたる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"酒", @"friend|ユウ", @"dog|いぬ", @"sake|さけ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"悲", @"sad|かなしい", @"evening|セキ", @"lean|かわ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"晴", @"clear up|はれる", @"elder sister|あね", @"most|もっとも",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"掛", @"tax|かける", @"mixture|こむ", @"way|",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"到", @"reach|いたる", @"follow|つたわる", @"shrink|ヤク",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寝", @"bed|ねる", @"view|ケ", @"argument|ロン",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"暗", @"study|ガク", @"shade|くらい", @"ease|たのしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"盗", @"ball|キュウ", @"long|ながい", @"rob|ぬすむ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"吸", @"sip|すう", @"a reason|よし", @"0.1|あう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"陽", @"male|ヨウ", @"snow|セツ", @"time|キ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"御", @"big brother|ケイ", @"ream|たば", @"govern|おん",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"歯", @"item|さけぶ", @"doctor|いやす", @"cog|よわい",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"忘", @"forget|わすれる", @"selling|ショウ", @"reach|いたる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"雪", @"hall|ドウ", @"snow|セツ", @"finger|ゆび",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"吹", @"puff|スイ", @"fall|おりる", @"person|ひと",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"娘", @"girl|むすめ", @"small|ちいさい", @"ream|たば",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"誤", @"-|まける", @"color|ショク", @"err|あやまる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"洗", @"flower|カ", @"sketch|カイ", @"wash|セン",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"慣", @"toil|つとめる", @"accustomed|なれる", @"admonish|いましめる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"礼", @"harm|ガイ", @"stop|おす", @"bow|レイ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"窓", @"feeling|カン", @"case|くだん", @"pane|まど",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"昔", @"noon|うま", @"antiquity|むかし", @"exertion|ベン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"貧", @"poor|まずしい", @"noon|ひる", @"other|あまる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"怒", @"angry|いかる", @"no|いな", @"taste|あじ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"泳", @"friend|ユウ", @"swim|およぐ", @"late|おくれる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"祖", @"view|ケ", @"pioneer|", @"plan|はかる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"杯", @"wood|き", @"hug|だく", @"glass|さかずき",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"疲", @"tire|つかれる", @"fast|はやい", @"0.1|あう",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"皆", @"silver|ギン", @"all|みな", @"polish|ケン",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"鳴", @"cry|なく", @"lobe|ヨウ", @"inside|なか",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"腹", @"small|ちいさい", @"belly|はら", @"have|もつ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"煙", @"work|ショク", @"side|きわ", @"smoke|けむる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"眠", @"sky|そら", @"firm|たしか", @"die|ねむる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"怖", @"map|え", @"fearful|こわい", @"mark|つける",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"耳", @"ear|ジ", @"head|あたま", @"make|つくる",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"頂", @"actual|あらわれる", @"war|ヤク", @"top|いただく",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"箱", @"hair of the head|ハツ", @"deep|ふかい", @"bin|はこ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"晩", @"lend|かす", @"night|バン", @"swim|およぐ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"寒", @"pioneer|", @"cold|カン", @"swim|およぐ",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"髪", @"form|かた", @"idea|おもう", @"hair of the head|ハツ",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"忙", @"world|カイ", @"busy|いそがしい", @"son|いき",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"才", @"genius|サイ", @"weekday|ヨ", @"ear|ジ",@"1", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"靴", @"enter|いる", @"shoes|くつ", @"walk|あるく",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"恥", @"3)|のぞく", @"fall|おりる", @"shame|はじる",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"偶", @"flat|たいら", @"room|むろ", @"couple|たま",@"3", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"偉", @"take|とる", @"famous|イ", @"change|ころがる",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"猫", @"harbor|みなと", @"cat|ねこ", @"busy|いそがしい",@"2", nil]];
	[nodeContentArray addObject:[NSArray arrayWithObjects: @"幾", @"how far|いく", @"mouth|くち", @"fast|はやい",@"1", nil]];
}

- (void) userStart
{
	userProgress = 1;
	userContentRecords = [[NSMutableArray alloc] init];
}

- (void) userSaveRecord :(int)location :(float)record
{
	NSLog(@"> Save  | Saved Record: %f", record);
	[userContentRecords addObject:[NSArray arrayWithObjects: [NSString stringWithFormat:@"%d",location], [NSString stringWithFormat:@"%f",record], nil]];
}

- (void) userReset
{
	NSLog(@"> Reset | Reset User Records");
	userContentRecords = [[NSMutableArray alloc] init];
	[userContentRecords addObject:[NSArray arrayWithObjects: @"1",@"1",nil]];
	self.interfaceMenuProgress.text = @"Press \"Next\" to begin";
	[self userErase];
	[self gameFinish];
	[self userStart];
}

- (void)userErase
{
	NSString *domainName = [[NSBundle mainBundle] bundleIdentifier];
	[[NSUserDefaults standardUserDefaults] removePersistentDomainForName:domainName];
}

- (void)userLoad
{
	
	if( [ [[NSUserDefaults standardUserDefaults] objectForKey:@"userLesson"] intValue] > 0 ){
		
		NSLog(@"= User  | Loading..");
		
		userLesson	= [ [[NSUserDefaults standardUserDefaults] objectForKey:@"userLesson"] intValue];
		userNextType	= [ [[NSUserDefaults standardUserDefaults] objectForKey:@"userNextType"] intValue];
		userProgress	= [ [[NSUserDefaults standardUserDefaults] objectForKey:@"userProgress"] intValue];
		
		NSLog(@"= User  | Loaded.");
		
	}
	
}

- (void)userSave
{
	
	NSLog(@"= User  | Saving..");
	
	[[NSUserDefaults standardUserDefaults] setObject:[NSString stringWithFormat:@"%d",userLesson] forKey:@"userLesson"];
	[[NSUserDefaults standardUserDefaults] setObject:[NSString stringWithFormat:@"%d",userNextType] forKey:@"userNextType"];
	[[NSUserDefaults standardUserDefaults] setObject:[NSString stringWithFormat:@"%d",userProgress] forKey:@"userProgress"];
	
	NSLog(@"= User  | Saved.");
	
}

@end